<?php
// Autogenerated by Translator Builder

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\CompanyKeyword;

class CompanyKeywordTableSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker\Factory::create();
        
            CompanyKeyword::create([                
                
                    'en' => 'Account Collector, Accounting Clerk, Administrative Assistant, Administrative Coordinator, Administrative Director, Administrative Manager, Administrative Services Manager, Administrative Services Officer, Administrative Specialist, Administrative Support Manager, Administrative Support Supervisor, Administrator, Auditing Clerk, Assistant Director, Billing Clerk, Billing Collector, Billing Coordinator, Bookkeeper, Client Relations Manager, Contract Administrator, Credit Clerk, Data Entry, Executive Assistant, Executive Services Administrator, Facility Manager, File Clerk, Financial Clerk, General Office Clerk, Human Resources Administrator, Information Clerk, Legal Secretary, Mail Clerk, Mail Clerk Leader, Material Recording Clerk, Medical Secretary, Office Assistant, Office Clerk, Office Manager, Office Support Manager, Office Support Supervisor, Program Administrator, Program Manager, Receptionist, Records Management Analyst, Secretary, Senior Administrative Analyst, Senior Administrative Coordinator, Senior Administrative Services Officer, Senior Coordinator, Senior Executive Assistant, Senior Special Events Coordinator, Senior Support Assistant, Senior Support Specialist, Special Events Coordinator, Special Programs Coordinator, Staff Assistant, Support Assistant, Support Specialist, Typist, Virtual Assistant, Virtual Receptionist, Word Processor,Corporate Secretary,Treasurer/Chief Financial Officer,General / Operations Manager,Office Manager,Environmental Health & Safety Manager,Safety Manager, Functional Manager,Human Resources Manager,Project Coordinator',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'administration',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Architect, Civil engineer,Quantity surveyor, Interior designer,Construction manager,Landscape architect,Electrician,Architectural drafter,Land surveyor,Urban and regional planner, Designer, Project Architect,Job Captain,CAD Coordinator,Land Planner,Erosion Control Specialist,Carpenter,Drywall Finisher,General Labor,Glazier,Electrician,Flagger,Traffic Control Supervisor,Mason,Millwright,Painter,Pipefitter,Plumbing,Sheetmetal,Roofer,Structural Ironworker,Reinforcing Ironworker,Welder,Equipment Manager,Project Manager,Project Engineer,Foreman,Field Superintendent,Field Office Manager,Estimator,Preconstruction Manager,Detailer,Purchasing Agent,Vice President of Construction',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'architecture-amp-construction',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Actor, Animator, Art therapist, Arts administrator, Ceramics designer, Community arts worker, Dancer, Exhibition designer, Fashion designer, Fine artist, Furniture conservator/restorer, Furniture designer, Glass blower/designer, Graphic designer, Illustrator, Industrial/product designer, Interior and spatial designer, Jewellery designer, Make-up artist, Medical illustrator, Museum/gallery conservator, Museum/gallery curator, Museum/gallery exhibitions officer, Musician, Photographer, Press photographer, Printmaker, Production designer, theatre/television/film, Textile designer, Web designer,',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'art-amp-culture',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Accounting technician, Actuarial analyst, Actuary, Chartered accountant, Chartered certified accountant, Chartered loss adjuster, Chartered management accountant, Chartered public finance accountant, Corporate investment banker, Corporate treasurer, Financial adviser, Financial manager, Financial risk analyst, Financial trader, Forensic accountant, Insurance account manager, Insurance broker, Insurance claims handler, Insurance risk surveyor, Insurance underwriter, Internal auditor, Investment analyst, Operational investment banker, Pension scheme manager, Pensions consultant, Retail banker, Risk manager, Senior tax professional/tax inspector, Stockbroker, Tax adviser',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'banking-and-or-finance-amp-insurance',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Chartered management accountant, Civil Service fast streamer, Economist, Environmental consultant, Ergonomist, Fast food restaurant manager, Financial manager, Financial risk analyst, Health service manager, Hotel manager, Internal auditor, IT consultant, Management consultant, Office manager, Operational researcher, Product manager, Project manager, Public affairs consultant, Recruitment consultant, Retail manager, Risk manager, Secretary/administrator, Statistician',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'business-amp-consulting',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'PR Agency',                    
                
                    'es' => '',                    
                
                    'it' => 'Agenzia PR',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'communication-amp-media-amp-pr',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Supermarket',                    
                
                    'es' => '',                    
                
                    'it' => 'Supermercato',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'consumer-goods',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Customer Support',                    
                
                    'es' => '',                    
                
                    'it' => 'Assistenza clienti',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'customer-service',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Design Agency',                    
                
                    'es' => '',                    
                
                    'it' => 'Agenzia di design',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'design',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Early years teacher, Education administrator, Educational psychologist, English as a foreign language teacher, Environmental education officer, Further education teacher, Higher education lecturer, Learning mentor, Museum education officer, Primary school teacher, Private music teacher, Secondary school teacher, Special educational needs teacher',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'education-amp-training',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Aerospace engineer, Automotive engineer, Biomedical engineer, Chemical engineer, Communications engineer, Consulting civil engineer, Contracting civil engineer, Control and instrumentation engineer, Drilling engineer, Electrical engineer, Electronics engineer, Energy engineer, Engineering geologist, Geochemist, Maintenance engineer, Manufacturing engineer, Manufacturing systems engineer, Materials engineer, Mechanical engineer, Naval architect, Petroleum engineer, Production manager, Quality manager, Structural engineer, Technical brewer, Technical sales engineer, Water engineer',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'engineering',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Accommodation manager, Catering manager, Conference centre manager, Customer service manager, Event organiser, Exhibition designer, Fast food restaurant manager, Hotel manager, Human resources officer, Marketing executive, Public house manager, Restaurant manager, Holiday representative, Theme park manager, Tour manager, Tourism officer, Tourist information centre manager, Travel agency manager',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'hospitality-amp-tourism',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Careers adviser, Human resources officer, IT trainer, Management consultant, Occupational psychologist, Office manager, Recruitment consultant, Sales executive, Training and development officer',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'human-resources',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Applications developer, Business analyst, Cartographer, Database administrator, Games developer, Geographical information systems officer, Information security specialist, Information systems manager, IT consultant, IT sales professional, IT technical support officer, Network engineer, SEO specialist, Software tester, Systems analyst, Systems developer, Technical author, Web designer, Web developer',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'it-amp-web',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Barrister, Barrister&apos;s clerk, Chartered legal executive (England and Wales), Company secretary, Licensed conveyancer, Patent attorney, Solicitor, Solicitor, Scotland, Tax adviser, Trade mark attorney',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'legal',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Air cabin crew, Air traffic controller, Airline pilot, Electrical engineer, Freight forwarder, IT consultant, Logistics and distribution manager, Maintenance engineer, Marketing executive, Merchant navy officer, Passenger transport manager, Transport planner,',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'logistics',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Factory',                    
                
                    'es' => '',                    
                
                    'it' => 'Fabbrica',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'manufacturing',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Advertising account executive, Advertising account planner, Advertising art director, Advertising copywriter, Digital marketer, Market researcher, Marketing executive, Media buyer, Media planner, Public affairs consultant, Public relations account executive, Public relations officer, Sales promotion account executive',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'marketing-amp-advertising',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Acupuncturist, Adult nurse, Art therapist, Biomedical scientist, Children&apos;s nurse, Chiropractor, Clinical psychologist, Community pharmacist, Counselling psychologist, Dance movement psychotherapist, Dentist, Diagnostic radiographer, Dietitian, Dispensing optician, Dramatherapist, Epidemiologist, Exercise physiologist, Forensic psychologist, General practice doctor, Health promotion specialist, Health service manager, Health visitor, Healthcare scientist, audiology, Healthcare scientist, clinical biochemistry, Healthcare scientist, clinical embryology, Healthcare scientist, genetics, Healthcare scientist, haematology, Healthcare scientist, histocompatibility and immunogenetics, Healthcare scientist, immunology, Healthcare scientist, medical physics, Healthcare scientist, physiology, Herbalist, Homeopath, Horticultural therapist, Hospital doctor, Hospital pharmacist, Learning disability nurse, Medical sales representative, Mental health nurse, Microbiologist, Midwife, Music therapist, Nutritional therapist, Nutritionist, Occupational therapist, Ophthalmologist, Optometrist, Orthoptist, Osteopath, Paramedic, Physiotherapist, Podiatrist, Radiation protection practitioner, Speech and language therapist, Sports therapist, Therapeutic radiographer',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'medicine-amp-pharmaceutics',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Civil Service fast streamer,Government social research officer,Politician&apos;s assistant,Public affairs consultant,Public relations account executive,Social researcher,Charity officer,Diplomatic Services operational officer,Forensic accountant,Human resources officer,Local government officer,Market researcher,Marketing executive,Newspaper journalist,Public relations officer,Stockbroker',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'politics',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Quality Assurance & Safety',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'quality-assurance-amp-safety',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Real Estate',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'real-estate',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Laboratories',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'research-amp-development',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Bookseller, Call centre manager, Commercial art gallery manager, Customer service manager, Dispensing optician, Financial adviser, Logistics and distribution manager, Purchasing manager, Retail buyer, Retail manager, Retail merchandiser, Sales executive, Visual merchandiser, Warehouse manager',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'retail-amp-wholesale',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Sales representative, sales professional, district sales manager, regional sales manager, VP of sales, account executive, account manager, sales executive, sales engineer, director of sales, sales support manager, regional sales representative, regional sales manager, channel sales manager, manufacturer representative, technical sales, medical sales representative, pharmaceutical sales, e-business sales manager, IT sales,solution selling, relationship building, relationship selling, relationship sales, customer service, customer relations, client relations, territory expansion, consultative sales, product marketing, negotiating and closing, channel sales, B2B/B2C, lead generation, OEMs, VARs, communication skills, new business development, sales presentations, PowerPoint, meeting and exceeding sales quotas, outside sales, inside sales, sales expansion',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'sales',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Adult guidance worker, Advice worker, Care manager, Child psychotherapist, Community arts worker, Community development worker, Community education officer, Counselling psychologist, Counsellor, Educational psychologist, Equality and diversity officer, Family support worker, Play therapist, Primary care graduate mental health worker, Probation officer, Psychotherapist, Social worker, Youth worker',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'social-work',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Fitness centre manager, Outdoor activities/education manager, Sport and exercise psychologist, Sports administrator, Sports coach, Sports development officer, Sports therapist',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'sport-and-or-health-amp-wellness',                    
                
            ]);
        
            CompanyKeyword::create([                
                
                    'en' => 'Technology & Telecommunications',                    
                
                    'es' => '',                    
                
                    'it' => 'Tecnologia e telecomunicazione',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'technology-amp-telecommunications',                    
                
            ]);
            
    }
}
