<?php
// Autogenerated by Translator Builder

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\PersonalSkill;

class PersonalSkillTableSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker\Factory::create();
        
            PersonalSkill::create([                
                
                    'en' => 'Accurate',                    
                
                    'es' => 'riguroso',                    
                
                    'it' => 'preciso',                    
                
                    'de' => 'präzise',                    
                
                    'fr' => 'précis',                    
                
                    'sk' => 'precízny',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Adaptable',                    
                
                    'es' => 'adaptable',                    
                
                    'it' => 'versatile',                    
                
                    'de' => 'anpassungsfähig',                    
                
                    'fr' => 'adaptable',                    
                
                    'sk' => 'adaptabilný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Ambitious',                    
                
                    'es' => 'ambicioso',                    
                
                    'it' => 'ambizioso',                    
                
                    'de' => 'ehrgeizig',                    
                
                    'fr' => 'ambitieux',                    
                
                    'sk' => 'ambiciózny',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Amiable',                    
                
                    'es' => 'amigable',                    
                
                    'it' => 'amichevole',                    
                
                    'de' => 'freundlich',                    
                
                    'fr' => 'aimable',                    
                
                    'sk' => 'priateľský',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Analytical',                    
                
                    'es' => 'analítico',                    
                
                    'it' => 'analitico',                    
                
                    'de' => 'analytisch',                    
                
                    'fr' => 'analytique',                    
                
                    'sk' => 'analytický',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Assertive',                    
                
                    'es' => 'asertivo',                    
                
                    'it' => 'assertivo',                    
                
                    'de' => 'assertiv',                    
                
                    'fr' => 'qui a de l´assurance',                    
                
                    'sk' => 'asertívny',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Broad-minded',                    
                
                    'es' => 'tolerante',                    
                
                    'it' => 'tollerante',                    
                
                    'de' => 'tolerant',                    
                
                    'fr' => 'tolérant',                    
                
                    'sk' => 'tolerantný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Businesslike',                    
                
                    'es' => 'comercial',                    
                
                    'it' => 'commerciale',                    
                
                    'de' => 'kommerziell',                    
                
                    'fr' => 'qui a l´esprit d´entreprise',                    
                
                    'sk' => 'podnikateľský',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Calm',                    
                
                    'es' => 'tranquilo',                    
                
                    'it' => 'tranquillo',                    
                
                    'de' => 'ruhig',                    
                
                    'fr' => 'calme',                    
                
                    'sk' => 'pokojný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Capable',                    
                
                    'es' => 'capaz',                    
                
                    'it' => 'capace',                    
                
                    'de' => 'fähig',                    
                
                    'fr' => 'capable',                    
                
                    'sk' => 'schopný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Careful',                    
                
                    'es' => 'sistemático',                    
                
                    'it' => 'meticoloso',                    
                
                    'de' => 'pedant',                    
                
                    'fr' => 'systématique',                    
                
                    'sk' => 'dôsledný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Competent',                    
                
                    'es' => 'competente',                    
                
                    'it' => 'competente',                    
                
                    'de' => 'komplet',                    
                
                    'fr' => 'compétent',                    
                
                    'sk' => 'kompetentný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Confident',                    
                
                    'es' => 'seguro de si mismo',                    
                
                    'it' => 'sicuro di sé',                    
                
                    'de' => 'selbstbewusst',                    
                
                    'fr' => 'assuré',                    
                
                    'sk' => 'sebavedomý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Cooperative',                    
                
                    'es' => 'colaborador',                    
                
                    'it' => 'collaborativo',                    
                
                    'de' => 'kooperativ',                    
                
                    'fr' => 'coopératif',                    
                
                    'sk' => 'kooperujúci',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Critical thinking',                    
                
                    'es' => 'pensador crítico',                    
                
                    'it' => 'senso critico',                    
                
                    'de' => 'kritisch denkend',                    
                
                    'fr' => 'esprit critique',                    
                
                    'sk' => 'schopný kritického myslenia',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Dedicated',                    
                
                    'es' => 'entregado',                    
                
                    'it' => 'dedito a ',                    
                
                    'de' => 'begeistert',                    
                
                    'fr' => 'dévoué',                    
                
                    'sk' => 'zanietený',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Determined',                    
                
                    'es' => 'tenaz',                    
                
                    'it' => 'determinato',                    
                
                    'de' => 'ausdauerfähig',                    
                
                    'fr' => 'déterminé',                    
                
                    'sk' => 'vytrvalý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Efficient',                    
                
                    'es' => 'eficiente',                    
                
                    'it' => 'efficiente',                    
                
                    'de' => 'leistungsstark',                    
                
                    'fr' => 'efficace',                    
                
                    'sk' => 'výkonný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Energetic',                    
                
                    'es' => 'enérgico',                    
                
                    'it' => 'energico',                    
                
                    'de' => 'energisch',                    
                
                    'fr' => 'énergique',                    
                
                    'sk' => 'energický',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Flexible',                    
                
                    'es' => 'flexible',                    
                
                    'it' => 'flessibile',                    
                
                    'de' => 'flexibel',                    
                
                    'fr' => 'flexible',                    
                
                    'sk' => 'flexibilný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Hardworking',                    
                
                    'es' => 'trabajador',                    
                
                    'it' => 'diligente',                    
                
                    'de' => 'arbeitsam',                    
                
                    'fr' => 'travailleur',                    
                
                    'sk' => 'pracovitý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Honest',                    
                
                    'es' => 'honesto',                    
                
                    'it' => 'onesto',                    
                
                    'de' => 'ehrlich',                    
                
                    'fr' => 'honnête',                    
                
                    'sk' => 'čestný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Independent',                    
                
                    'es' => 'independiente',                    
                
                    'it' => 'indipendente',                    
                
                    'de' => 'unabhängig',                    
                
                    'fr' => 'indépendant',                    
                
                    'sk' => 'nezávislý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Innovative',                    
                
                    'es' => 'innovador',                    
                
                    'it' => 'innovativo',                    
                
                    'de' => 'innovativ',                    
                
                    'fr' => 'innovateur',                    
                
                    'sk' => 'inovatívny',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Leadership',                    
                
                    'es' => 'liderazgo',                    
                
                    'it' => 'Leadership',                    
                
                    'de' => 'Führungskraft',                    
                
                    'fr' => 'leader',                    
                
                    'sk' => 'líder',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Motivated',                    
                
                    'es' => 'motivado',                    
                
                    'it' => 'motivato',                    
                
                    'de' => 'motiviert',                    
                
                    'fr' => 'motivé',                    
                
                    'sk' => 'motivovaný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Multicultural sensitive',                    
                
                    'es' => 'multiculturalmente sensible',                    
                
                    'it' => 'sensibile alla multiculturalità',                    
                
                    'de' => 'multikulturell sensibel',                    
                
                    'fr' => 'sensibilité multiculturelle',                    
                
                    'sk' => 'multikultúrne citlivý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Optimistic',                    
                
                    'es' => 'optimista',                    
                
                    'it' => 'ottimista',                    
                
                    'de' => 'optimistisch',                    
                
                    'fr' => 'optimiste',                    
                
                    'sk' => 'optimistický',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Organized',                    
                
                    'es' => 'organizado',                    
                
                    'it' => 'organizzato',                    
                
                    'de' => 'organisiert',                    
                
                    'fr' => 'organisé',                    
                
                    'sk' => 'organizovaný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Persevering',                    
                
                    'es' => 'perseverante',                    
                
                    'it' => 'perseverante',                    
                
                    'de' => 'zäh',                    
                
                    'fr' => 'persévérant',                    
                
                    'sk' => 'húževnatý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Practical',                    
                
                    'es' => 'práctico',                    
                
                    'it' => 'pratico',                    
                
                    'de' => 'praktisch',                    
                
                    'fr' => 'qui a le sens pratique',                    
                
                    'sk' => 'praktický',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Productive',                    
                
                    'es' => 'productivo',                    
                
                    'it' => 'produttivo',                    
                
                    'de' => 'produktiv',                    
                
                    'fr' => 'productif',                    
                
                    'sk' => 'poduktívny',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Professional',                    
                
                    'es' => 'profesional',                    
                
                    'it' => 'professionale',                    
                
                    'de' => 'professionell',                    
                
                    'fr' => 'professionnel',                    
                
                    'sk' => 'profesionálny',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Realistic',                    
                
                    'es' => 'realista',                    
                
                    'it' => 'realista',                    
                
                    'de' => 'realistisch',                    
                
                    'fr' => 'réaliste',                    
                
                    'sk' => 'realistický',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Reliable',                    
                
                    'es' => 'fiable',                    
                
                    'it' => 'affidabile',                    
                
                    'de' => 'verlässlich',                    
                
                    'fr' => 'sur qui on peut compter',                    
                
                    'sk' => 'spoľahlivý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Resourceful',                    
                
                    'es' => 'imaginativo',                    
                
                    'it' => 'intraprendente',                    
                
                    'de' => 'erfinderisch',                    
                
                    'fr' => 'débrouillard',                    
                
                    'sk' => 'vynaliezavý',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Responsible',                    
                
                    'es' => 'responsable',                    
                
                    'it' => 'responsabile',                    
                
                    'de' => 'verantwortungsvoll',                    
                
                    'fr' => 'responsable',                    
                
                    'sk' => 'zodpovedný',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Team-workable',                    
                
                    'es' => 'apto para trabajar en equipo',                    
                
                    'it' => 'disposto a lavorare in gruppo',                    
                
                    'de' => 'teamfähig',                    
                
                    'fr' => 'qui a l´esprit d´équipe',                    
                
                    'sk' => 'tímový hráč',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Versatile',                    
                
                    'es' => 'versátil',                    
                
                    'it' => 'versatile',                    
                
                    'de' => 'universell',                    
                
                    'fr' => 'aux talents variés',                    
                
                    'sk' => 'univerzálny',                    
                
            ]);
        
            PersonalSkill::create([                
                
                    'en' => 'Willingness to learn',                    
                
                    'es' => 'dispuesto a aprender',                    
                
                    'it' => 'desideroso di imparare',                    
                
                    'de' => 'willig / willig zu lernen',                    
                
                    'fr' => 'prêt à apprendre',                    
                
                    'sk' => 'ochota/ochotný učiť sa ',                    
                
            ]);
            
    }
}
