<?php
// Autogenerated by Translator Builder

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\StudyKeyword;

class StudyKeywordTableSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker\Factory::create();
        
            StudyKeyword::create([                
                
                    'en' => 'Brand, Brand image, Market Research, Customer, Consumer, Customer needs, Market segment, Price sensitive, Market map, Gap in the market, Added value, Entrepreneur, Risks, Services, Innovation, Patent, Copyright,Trademarks,Calculated Risk, Financial Objectives, SMART, Initiative, Taking risks,',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'business-studies-and-or-management-science',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Mechanical Engineering, Electrical Engineering, Chemical Engineering, Civil Engineering, Electronic Engineering, Telecommunications, Materials Science.,Automation, Robotics Control Systems,Digital Systems, Digital Representation,Electronic circuits components and equipment,Electronic engineering,Embedded Systems and Real Time Systems,High Frequency Technology, Microwaves,Magnetic and superconductory materials/devices,Microengineering,Micromachining,Nanotechnologies related to electronics and microelectronics,Optical Networks and Systems,Peripherals Technologies (Mass Data Storage, Display Technologies) related to electronics and microelectronics, Printed circuits and integrated circuits,Quantum Informatics,Semiconductors,Smart cards and access systems,Environmental and Biometrics Sensors,Actuators,Audiovisual Equipment and Communication, Broadband Technologies, Mobile Communications, Radar, Narrow Band Technologies, Satellite Technology/Systems/Positioning/, Communication in GPS - Global Positioning System, e-Government, CRM - Customer relationship Management, ',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'engineering-and-or-technology',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Political Science, Sociology, Economics, Psychology and Behavioural Sciences, Social Work, International Relations, European Studies, Area Studies.,Abstract,Academic,Brand,Capital,Celebrity,Civil Society,Community,Corporate,Design,Diversity,Emotion,Empathy,Enlightenment,Enterprise,Environment,Ethical,European,Excellence,Fair,Faith,Freedom / Liberty,Fundamentalism,Global / International ,Identity,Independent,Information,Legitimate,Life,Market,Marriage,Mentor,Opinion,Perform / Performance,Political,Property,Queer,Relativism',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'social-sciences',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Modern EC Languages, Linguistics, Translation, Interpretation, Classical Philology, Non EC Languages, Less Widely Taught Languages',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'languages-and-philological-sciences',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Journalism, Radio/TV Broadcasting, Public Relations, Publicity, Advertising, Library Science, Documentation, Archiving, Museum Studies, Conservation,E-Publishing, Digital Content',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'communication-and-information-sciences',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Philosophy,Theology,History,Archaeology',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'humanities',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Teacher Training, Primary Education, Secondary Education, Special Education, Educational Science, Comparative Education, Educational Psychology.',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'education-and-or-teacher-training',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Comparative Law, Law with Languages, International Law, Civil Law, Criminal Law, Criminology, Constitutional /Public Law, Public Administration, European Community/EU Law',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'law',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Fine Art, Music and Musicology, Design, History of Art.',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'art-and-design',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Urban Planning, Regional Planning',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'architecture-and-or-urban-and-regional-planning',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Biology, Physics, Chemistry, Microbiology, Biotechnology, Nuclear and High Energy Physics, Biochemistry, Astronomy, Astrophysics',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'natural-sciences',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Mathematics, Statistics; Informatics, Computer Science',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'mathematics-and-or-informatics',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Medicine, Public Health, Medical Technology',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'medical-sciences',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Geography, Environmental Sciences, Ecology, Geology, Soil and Water Sciences, Geodesy, Cartography, Remote Sensing',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'geography-and-or-geology',                    
                
            ]);
        
            StudyKeyword::create([                
                
                    'en' => 'Agriculture, Food Science and Technology, Fisheries, Forestry,Farming, tractors, ',                    
                
                    'es' => '',                    
                
                    'it' => '',                    
                
                    'de' => '',                    
                
                    'fr' => '',                    
                
                    'sk' => '',                    
                
                    'key' => 'agriculture-sciences',                    
                
            ]);
            
    }
}
