<?php
// Autogenerated by Translator Builder

return [
    
        'accountActivated_subject_1' => 'Azione richiesta: Attiva il tuo account.',
    
        'accountActivated_line_2' => 'Grazie per la tua registrazione su Talented Europe',
    
        'accountActivated_line_3' => 'Verificare l\'indirizzo email cliccando sul link qui sotto',
    
        'accountActivated_action_4' => 'Confermare il mio account',
    
        'accountActivated_line_5' => 'Grazie per utilizzare la nostra applicazione',
    
        'changeInstitution_subject_1' => '%s Ti ha invitato come vidimatore su Talented Europe.',
    
        'changeInstitution_line_2' => '%s Ti ha invitato come vidimatore su Talented Europe.',
    
        'changeInstitution_line_3' => 'Dato che sei già un vidimatore su Talented Europe, abbiamo bisogno che confermi questa modifica.',
    
        'changeInstitution_action_4' => 'Confermare le modifiche',
    
        'changeInstitution_line_5' => 'Grazie per utilizzare la nostra applicazione',
    
        'institutionRemoved.subject_1' => '%s L\'ha rimosso dalla sua istituzione su Talented Europe.',
    
        'institutionRemoved.line_2' => '%s Ti ha rimosso dalla sua istituzione su Talented Europe. Se sei stato rimosso per errore, contattali per risolvere la situazione.',
    
        'institutionRemoved.line_3' => 'Grazie per utilizzare la nostra applicazione',
    
        'inviteCreated_subject_1' => '%s Ti ha invitato come vidimatore su Talented Europe.',
    
        'inviteCreated_line_2' => '%s Ti ha invitato come vidimatore su Talented Europe.',
    
        'inviteCreated_line_3' => 'Crea il tuo account cliccando sul seguente link.',
    
        'inviteCreated_action_4' => 'Creare il mio account',
    
        'inviteCreated_line_5' => 'Grazie per utilizzare la nostra applicazione',
    
        'validatorRequested_subject_1' => '%s Ti ha invitato come vidimatore su Talented Europe.',
    
        'validatorRequested_line_2' => 'Ciao %s',
    
        'validatorRequested_line_3' => '%s Ti ha invitato come vidimatore su Talented Europe.',
    
        'validatorRequested_line_4' => 'Inviate questo link all\'istituzione nella quale lavorate affinché possano registrarsi.',
    
        'validatorRequested_line_5' => 'Se la vostra istituzione si registra utilizzando il seguente link, sarete invitati automaticamente a iscrivervi nel registro dell\'istituzione.',
    
        'validatorRequested_action_6' => 'Creare l\'account dell\'istituzione',
    
        'validatorRequested_line_7' => 'Grazie per utilizzare la nostra applicazione',
    
        'newAlerts_subject_1' => 'New alerts from students',
    
        'newAlerts_line_2' => 'Hello we\'re reminding you that some students alerted you on our platform',
    
        'newAlerts_line_3' => 'Please click the following button to log in and see your panel',
    
        'validationsPending_subject_1' => 'Referees pending on Talented Europe',
    
        'validationsPending_line_2' => 'Hello we\'re reminding you that you have some referee\'s pending on our platform',
    
        'validationsPending_line_3' => 'Please click the following button to log in and see your panel',
    
];
