<?php
// Autogenerated by Translator Builder

return [
    
        'not_allowed' => 'Non autorizzato',
    
        'not_allowed_to_do_this_action' => 'Non sei autorizzato ad eseguire questa azione',
    
        'can_try_searching_for' => 'Puoi provare a cercare',
    
        'page_not_found' => 'Pagina non trovata',
    
        'we_didnt_find_the_page' => 'Non troviamo la pagina che stai cercando',
    
        'internal_server_error' => 'Errore Interno del Server',
    
        'an_error_happened' => 'Si é verificato un errore, gli amministratori hanno ricevuto la notifica e il problema sarà risolto al piú presto, per favore riprova piú tardi.',
    
        'meanwhile_can_searching_for' => 'Intanto puoi provare a cercare ',
    
        'be_right_back' => 'Torniamo subito',
    
        'not_found' => 'Non trovato',
    
        'unauthorized_action' => 'Azione non autorizzata',
    
];
