<?php
// Autogenerated by Translator Builder

return [
    
        'meta_title' => 'Talented Europe | Unisce i giovani talenti e i datori di lavoro di tutta Europa',
    
        'tagline' => 'Unisce<br/> <strong>i giovani talenti</strong> e <strong>i datori di lavoro</strong><br/> di tutta <strong>Europa</strong>',
    
        'days' => 'giorni',
    
        'hours' => 'ore',
    
        'minutes' => 'minuti',
    
        'seconds' => 'secondi',
    
        'more' => 'per saperne di più',
    
        'what_is_title' => 'Che cosa è Talented Europe?',
    
        'what_is_cta' => '<strong>Scopri di più!</strong> Scarica la brochure!',
    
        'what_is_text_1' => 'Ti piacerebbe entrare in contatto con i migliori studenti e aziende in Europa? Talented Europe è un\'applicazione multi-piattaforma specificamente progettata per mettere in contatto studenti universitari e laureati di vari campi dell\'istruzione con datori di lavoro o istituzioni in tutta l ́Europa per trovare lavoro dei loro sogni.',
    
        'what_is_text_2' => 'Grazie a Talented Europe, le aziende avranno accesso diretto alle informazioni di contatto e alla classifica degli studenti, rendendola una piattaforma di lavoro facile da usare e un punto d\'incontro con eccellenza.',
    
        'subscribe_title' => 'Registrati e segui i nostri aggiornamenti.',
    
        'subscribe_text' => 'Ricevi notifiche di tutti gli eventi e le novità su Talented Europe',
    
        'subscribe_form_placeholder' => 'Inserisci indirizzo email',
    
        'subscribe_btn_text' => 'registrati',
    
        'subscribe_follow_text' => 'oppure seguici su',
    
        'subscribe_text_question' => 'Ricevi news di Talented Europe nella tua casella di posta elettronica. <br/> Sentiti di libero di rispondere alla nostra domanda: Che cosa significa talento per te?',
    
        'meta_description' => 'Un progetto Erasmus Plus che permette ai migliori studenti di trovare posti di lavoro e stage in tutta Europa molto più facilmente.',
    
        'coming_soon' => 'Prossimamente',
    
        'search_placeholder' => 'Che cosa stai cercando?',
    
        'search_where' => 'Dove',
    
        'search_btn' => 'Cerca',
    
        'statistics_title' => 'Statistiche',
    
        'contacts' => 'Contatti tra studenti e imprese',
    
        'companies_institutions' => 'Imprese e istituzioni',
    
        'students_title' => 'Studenti di talento',
    
        'no_students' => 'Nessuno studente disponibile',
    
        'join_talented_europe_today' => 'Unisciti a Talented Europe ancora oggi!',
    
        'talented_for_students' => '<strong>Per studenti e laureati</strong> - Sostenere la mobilità degli studenti e laureati di qualsiasi tipo di ambiente accademico per la ricerca di stage o lavoro, promuovere la qualità e la pertinenza dell\'istruzione universitario, migliorando l\'occupabilità con l\'appoggio dei professori delle università competenti.',
    
        'talented_for_employers' => '<strong>Per i datori di lavoro</strong>​ - possibilità di trovare giovani in tutta Europa, in base ai criteri personali, che possano contribuire alla tua squadra con il loro talento e in precedenza hanno dimostrato ottimi risultati accademici. Eventuali nuovi membri dello staff possono essere contattati direttamente attraverso la piattaforma, e anche i datori di lavoro sono in grado di visualizzare le loro informazioni personali come voti, CV, approvazione, ecc.
',
    
        'talented_for_institutions' => '<strong>Per le istituzioni educative</strong>​ - private o pubbliche, università, centri di formazione professionale, ecc. possono partecipare e creare fiducia negli studenti, aiutandoli così a scoprire i loro talenti e promuoverli ai datori di lavoro. Prendendo solo un paio di minuti, insegnanti e professori hanno diritto di scrivere una breve approvazione per il ranking più alto degli studenti sulla piattaforma.',
    
        'what_is_talent_title' => 'Che cosa e il talento?',
    
        'what_is_talent_text' => '<strong>Lo sapevi che tutti abbiamo dei talenti primari?</strong>​ La maggior parte di noi non ha ancora imparato a conoscerli, ma sulla nostra strada potremmo scoprirli. Nella sua definizione più semplice, un\'abilità può essere appresa attraverso la guida e, dedicando ore di lavoro e impegno, sarà in grado di affinare le tue capacità e raggiungere il pieno potenziale, trasformandole infine in un talento. Grazie a Talented Europe, ​<strong>le persone con talento avranno la possibilità di impressionare i loro potenziali datori di lavoro, mentre i datori di lavoro costruiranno competenze in studenti che scelgono</strong>.',
    
        'go_to_app' => 'Passare all\'app',
    
        'what_is_text_1_txt' => 'Potete immaginare la possibilità di poter assumere i migliori studenti di qualsiasi paese d\'Europa? Vorreste far parte di un\'élite studentesca in Europa? Migliaia di compagnie avranno un accesso diretto alle vostre informazioni di contatto; migliore sarà la vostra valutazione, maggiori saranno le vostre opportunità di trovare un buon lavoro.',
    
        'what_is_text_2_txt' => 'Questa è l’offerta che Talented Europe ti propone. Una vetrina in cui vengono messi in mostra i migliori studenti di tutta Europa. Un’idea semplice che unisce i datori di lavoro agli studenti. Il punto d’incontro per eccellenza.',
    
        'download_app' => 'Scarica l\'applicazione',
    
];