<?php
// Autogenerated by Translator Builder

return [
    
        'meta_title' => 'Talented Europe | Unisce i talenti giovani e i datori di lavoro di tutta l&apos;Europa',
    
        'tagline' => 'Unisce<br/> <strong>i talenti giovani</strong> e <strong>i datori di lavoro</strong><br/> di tutta <strong>l&apos;Europa</strong>',
    
        'days' => 'giorni',
    
        'hours' => 'ore',
    
        'minutes' => 'minuti',
    
        'seconds' => 'secondi',
    
        'more' => 'per saperne di più',
    
        'what_is_title' => 'Che cos&apos;è la Talented Europe?',
    
        'what_is_cta' => '<strong>Scopri di più!</strong> Richiedi opuscolo!',
    
        'what_is_text_1' => 'Ti immagini di poter assumere i migliori studenti di qualsiasi paese europeo? Ti piacerebbe far parte di un elite studentesca in Europa? Migliaia di compagnie avranno un accesso diretto ai tuoi contatti e alle tue informazioni, migliori saranno i tuoi voti, maggiori saranno le possibilità di trovare un buon lavoro.',
    
        'what_is_text_2' => 'Questa è l’offerta che Talented Europe ti propone. Una vetrina in cui vengono messi in mostra i migliori studenti di tutta Europa. Un’idea semplice che unisce i datori di lavoro agli studenti. Il punto d’incontro per eccellenza.',
    
        'subscribe_title' => 'Registrati e segui i nostri aggiornamenti.',
    
        'subscribe_text' => 'Ricevi notifiche circa tutti gli eventi e le novità su Talented Europe',
    
        'subscribe_form_placeholder' => 'Inserisci indirizzo email',
    
        'subscribe_btn_text' => 'registrati',
    
        'subscribe_follow_text' => 'oppure seguici su',
    
        'subscribe_text_question' => 'Ricevi news circa Talented Europe nella tua casella di posta elettronica. <br/> Sentiti di libero di rispondere alla nostra domanda: Che cosa significa talento per te?',
    
        'meta_description' => 'Un progetto Erasmus Plus che permette ai migliori studenti di trovare posti di lavoro e stage in tutta Europa molto più facilmente.',
    
        'coming_soon' => 'prossimamente',
    
        'search_placeholder' => 'Che cosa stai cercando?',
    
        'search_where' => 'dove',
    
        'search_btn' => 'Cerca',
    
        'statistics_title' => 'Statistiche',
    
        'contacts' => 'Contatti tra studenti e aziende',
    
        'companies_institutions' => 'Aziende e istituzioni',
    
        'students_title' => 'Studenti di talento',
    
        'no_students' => 'Nessuno studente disponibili',
    
        'join_talented_europe_today' => 'Join Talented Europe today!',
    
        'talented_for_students' => 'For students - Talented Europe will enhance your employability with the endorsement of your tutors and put you in touch with employers across Europe for internships or first career jobs.',
    
        'talented_for_employers' => 'For employers - Talented Europe will link you with talented young students across Europe and help you find the right person who can contribute to your organisation’s success with the special talents and skills that you are looking for.',
    
];