<?php
// Autogenerated by Translator Builder

return [
    
        'remember_me' => 'Ricordami',
    
        'sign_in' => 'Registrati',
    
        'login_title' => 'Login',
    
        'login_btn' => 'Accedere',
    
];