<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'istruzione terziaria di ciclo breve',
    
        'studies_level_6' => 'laurea di primo grado o equivalente',
    
        'studies_level_7' => 'laurea magistrale o equivalente',
    
        'studies_level_8' => 'dottorato di ricerca o equivalente',
    
];