<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'istruzione terziaria di ciclo breve',
    
        'studies_level_6' => 'laurea di primo grado o equivalente',
    
        'studies_level_7' => 'laurea magistrale o equivalente',
    
        'studies_level_8' => 'dottorato di ricerca o equivalente',
    
        'company_activity' => 'Settore di attività',
    
        'company_contact_person' => 'Persona di contatto',
    
        'company_representative' => 'Rappresentante legale (responsabile)',
    
        'company_what_is_talent' => 'Che cosa significa il talento per te?',
    
        'institution_certificate' => 'Certificato di autenticità',
    
        'city' => 'Paese',
    
        'country' => 'Stato',
    
        'institution_certificate_template_download' => 'Scarica il modello',
    
        'fiscal_id' => 'Codice fiscale',
    
        'institution_hei' => 'Istituto di educazione superiore',
    
        'institution_ufa' => 'Università, Facoltà',
    
        'insitution_his' => 'Scuola secondaria',
    
        'legal_representative' => 'Rappresentante legale (responsabile)',
    
        'institution_pic' => 'Foto',
    
        'postal_code' => 'CAP',
    
        'institution_sig_stamp_text' => 'Firma e timbro',
    
        'institution_vet' => 'Formazione professionale e tirocinio',
    
        'student_academic_info' => 'Informazioni accademiche',
    
        'address' => 'Indirizzo',
    
        'student_certificate' => 'Certificato',
    
        'clear_btn' => 'Elimina',
    
        'student_experience_company' => 'Compagnia',
    
        'student_completed_studies' => 'Studi terminati',
    
        'student_course' => 'Corso',
    
        'student_date' => 'Data',
    
        'student_birthdate' => 'Data di nascita',
    
        'student_study_level' => 'Livello',
    
        'student_describe_talent' => 'Descrivi in breve il tuo talento',
    
        'email' => 'Email',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Indirizzo di studi',
    
        'student_study_from' => 'di',
    
        'student_study_grade_card' => 'Scheda di valutazione',
    
        'student_languages' => 'Lingue',
    
        'load_btn' => 'Caricare',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Nome',
    
        'nationality' => 'Nazionalità',
    
        'student_personal_information' => 'Informazioni personali',
    
        'student_personal_skills' => 'Abilità personali',
    
        'phone' => 'Telefono',
    
        'position' => 'Posizione',
    
        'student_professional_skills' => 'Abilità professionali',
    
        'student_proposed_validator' => 'Valutatore proposto',
    
        'save_btn' => 'Salva',
    
        'student_study_scanned_document' => 'Documento scansito',
    
        'student_validator' => 'Se non specifichi un valutatore, ti sarà assegnato automaticamente',
    
        'surname' => 'Cognome',
    
        'student_study_to' => 'a',
    
        'student_training' => 'Tirocinio',
    
        'upload_btn' => 'Caricare',
    
        'student_work_experience' => 'Esperienze lavorative',
    
        'validator_department' => 'Dipartimento',
    
        'password' => 'password',
    
        'confirm_password' => 'Conferma la password',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Accetto le condizioni d&apos;uso',
    
        'create_account' => 'Crea un nuovo account',
    
        'forgot_password' => 'Pasword dimenticata?',
    
        'administration' => '',
    
        'architecture-amp-construction' => '',
    
        'art-amp-culture' => '',
    
        'banking-and-or-finance-amp-insurance' => '',
    
        'business-amp-consulting' => '',
    
        'communication-amp-media-amp-pr' => '',
    
        'consumer-goods' => '',
    
        'customer-service' => '',
    
        'design' => '',
    
        'education-amp-training' => '',
    
        'engineering' => '',
    
        'hospitality-amp-tourism' => '',
    
        'human-resources' => '',
    
        'it-amp-web' => '',
    
        'legal' => '',
    
        'logistics' => '',
    
        'manufacturing' => '',
    
        'marketing-amp-advertising' => '',
    
        'medicine-amp-pharmaceutics' => '',
    
        'politics' => '',
    
        'quality-assurance-amp-safety' => '',
    
        'real-estate' => '',
    
        'research-amp-development' => '',
    
        'retail-amp-wholesale' => '',
    
        'sales' => '',
    
        'social-work' => '',
    
        'sport-and-or-health-amp-wellness' => '',
    
        'technology-amp-telecommunications' => '',
    
        'business-studies-and-or-management-science' => '',
    
        'engineering-and-or-technology' => '',
    
        'social-sciences' => '',
    
        'languages-and-philological-sciences' => '',
    
        'communication-and-information-sciences' => '',
    
        'humanities' => '',
    
        'education-and-or-teacher-training' => '',
    
        'law' => '',
    
        'art-and-design' => '',
    
        'architecture-and-or-urban-and-regional-planning' => '',
    
        'natural-sciences' => '',
    
        'mathematics-and-or-informatics' => '',
    
        'medical-sciences' => '',
    
        'geography-and-or-geology' => '',
    
        'agriculture-sciences' => '',
    
        'Lang_level_A1' => '',
    
        'Lang_level_A2' => '',
    
        'Lang_level_B1' => '',
    
        'Lang_level_B2' => '',
    
        'Lang_level_C1' => '',
    
        'Lang_level_C2' => '',
    
];