<?php
// Autogenerated by Translator Builder

return [
    
        'company_activity' => '',
    
        'company_contact_person' => '',
    
        'company_representative' => '',
    
        'company_what_is_talent' => '',
    
        'institution_certificate' => '',
    
        'city' => '',
    
        'country' => '',
    
        'institution_certificate_template_download' => '',
    
        'fiscal_id' => '',
    
        'institution_hei' => '',
    
        'institution_ufa' => '',
    
        'insitution_his' => '',
    
        'legal_representative' => '',
    
        'institution_pic' => '',
    
        'postal_code' => '',
    
        'institution_sig_stamp_text' => '',
    
        'institution_vet' => '',
    
        'student_academic_info' => '',
    
        'address' => '',
    
        'student_certificate' => '',
    
        'clear_btn' => '',
    
        'student_experience_company' => '',
    
        'student_completed_studies' => '',
    
        'student_course' => '',
    
        'student_date' => '',
    
        'student_birthdate' => '',
    
        'student_study_level' => '',
    
        'student_describe_talent' => '',
    
        'email' => '',
    
        'student_europass' => '',
    
        'student_study_field' => '',
    
        'student_study_from' => '',
    
        'student_study_grade_card' => '',
    
        'student_languages' => '',
    
        'load_btn' => '',
    
        'input_max_characters' => '',
    
        'name' => '',
    
        'nationality' => '',
    
        'student_personal_information' => '',
    
        'student_personal_skills' => '',
    
        'phone' => '',
    
        'position' => '',
    
        'student_professional_skills' => '',
    
        'student_proposed_validator' => '',
    
        'save_btn' => '',
    
        'student_study_scanned_document' => '',
    
        'student_validator' => '',
    
        'surname' => '',
    
        'student_study_to' => '',
    
        'student_training' => '',
    
        'upload_btn' => '',
    
        'student_work_experience' => '',
    
        'validator_department' => '',
    
        'password' => '',
    
        'confirm_password' => '',
    
        'captcha' => '',
    
        'terms_of_use' => '',
    
        'create_account' => '',
    
        'forgot_password' => '',
    
];