<?php
// Autogenerated by Translator Builder

return [
    
        'thank_you_for_signing_up' => 'Grazie per esserti registrato!',
    
        'you_will_receive_an_email' => 'A breve riceverai una email con le istruzioni per confermare la tua registrazione ',
    
        'go_back_to_home' => 'Torna alla pagina principale',
    
        'search_students' => 'Cerca studenti',
    
        'search_companies' => 'Ceca imprese',
    
        'register_as_validator' => 'Registrati come vidimatore',
    
        'there_have_been_some_errors' => 'Sono stati rilevati degli errori',
    
        'i_am_a' => 'Sono un',
    
        'all_fields_are_required' => 'Tutti i campi sono obbligatori',
    
        'confirmation_email_may_take_few_minutes' => 'La mail di conferma richiederá qualche minuto per essere ricevuta, per essere sicuro del suo arrivo puoi controllare la tua cartella spam',
    
        'registration_complete_successfully' => 'Registrazione completata con successo',
    
        'register_success' => 'Registrazione completata',
    
        'register' => 'Iscriversi',
    
        'invited_by' => 'Sei stato invitato da',
    
];