<?php
// Autogenerated by Translator Builder

return [
    
        'reset_password' => 'Reimpostare la password',
    
        'send_password_reset' => 'invio link di richiesta reimpostazione password',
    
        'set_password' => 'Impostare la password',
    
];