<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Data della richiesta',
    
        'pending' => 'Pendente',
    
        'validated' => 'Vidimato',
    
        'not_validated' => 'Non vidimato',
    
        'no_students' => 'Senza studenti',
    
        'confirm_validation' => 'Confermare la vidimazione',
    
        'are_you_sure_you_want_to_finish_refereeing' => 'Sei sicuro di voler concludere la vidimazione di questo studente?',
    
        'reason' => 'Reason',
    
        'criteria' => 'Student does not meet criteria',
    
        'nostudent' => 'Student hasn\'t attended this school/institution',
    
];
