<?php
// Autogenerated by Translator Builder

return [
    
        'my_students' => 'I miei studenti',
    
        'enable' => 'Abilitato',
    
        'disable' => 'Disabilitato',
    
        'add_new' => 'Aggiungere un nuovo vidimatore',
    
        'send_invitation' => 'Inviare un invito al vidimatore',
    
        'validating' => 'Vidimizzando',
    
        'student_already_validated' => 'Hai giá vidimato questo studente',
    
        'jump_to_results' => 'Andare ai risultati',
    
        'you_are_validating_following_student' => 'Stai vidimando il seguente studente',
    
        'jump_to_validation' => 'Vai alla vidimazione',
    
        'student_validation' => 'Vidimazione dello studente',
    
        'valid' => 'Valido',
    
        'student_passed_validation_successfully' => 'Lo studente ha superato con successo la tua vidimazione ',
    
        'your_comments' => 'I tuoi commenti',
    
        'your_chosen_skills' => 'Le tue competenze scelte',
    
        'invalid' => 'Non valido',
    
        'student_didnt_meet_criteria' => 'Lo studente non ha soddisfatto i criteri ',
    
        'make_sure_you_have_reviewed_student' => 'Per favore assicurati di aver revisionato attentamente il profilo dello studente prima di vidimarlo',
    
        'this_student_is' => 'Questo studente é',
    
        'finish_validation' => 'Vidimazione terminata',
    
        'give_us_explanation_of_student_is_not_valid' => 'Per favore, fornisci una spiegazione del motivo per cui lo/la studente/ssa non é valido/a',
    
        'note_if_validation_is_passed_as_no_student' => 'Nota: se la vidimazione ha come esito "Nessun studente" lo studente avrá la possibilitá di far vidimare il suo profilo di nuovo',
    
        'user_hasnt_complete_filling_its_profile' => 'L\'usuario non ha completato la compilazione del profilo. Fino a quando questo processo non é completo non é possibile vidimare gli studenti.',
    
        'manage_validators' => 'Gestire attestatori',
    
        'validators' => 'Attestatori',
    
        'invites_pending' => 'Inviti pendenti',
    
        'date_sent' => 'Data di invio',
    
        'note_invites_are_only_valid_14_days' => 'Nota: gli inviti sono validi solamente 14 giorni dopo l\' invio e spariranno da questa lista dopo tale periodo',
    
        'cancel' => 'Cancellare',
    
        'cannot_change_institution' => 'Non e´possibile cambiare l´istituzione',
    
        'invitation_is_not_valid_or_you_accepted_it' => 'O il tuo invito non é piú valido o é stato giá accettato',
    
        'changed_institution_successfully' => 'Il cambio di Istituzione é avvenuto con successo',
    
        'youll_receive_notifications_from' => 'Da adesso riceverai notiche di approvazione da',
    
        'cannot_complete_invitation' => 'Non si puó completare l\'invito',
    
        'no_alerts_found' => 'Nessun avviso trovato',
    
        'study_level' => 'Livello di studio',
    
        'when_it_was_sent' => 'Quando é stato inviato?',
    
        'no_referees' => 'Senza attestatori',
    
        'remove_referee' => 'Eliminare vidimatore',
    
        'do_you_want_to_remove_referee' => 'Vuoi rimuovere %s dalla tua Istituzione?',
    
        'remove' => 'Eliminare',
    
        'removing' => 'Eliminando',
    
        'validation_was_removed' => 'La valutazione è stata rimossa perché avevate indicato che %s non era uno studente di questa istituzione.',
    
        'validation_complete' => '%s valutazione completata',
    
        'cannot_invite' => 'Impossibile invitare: o questa e-mail è registrata a un altro tipo di utente, o egli ha già un invito in sospeso dall’istituzione.',
    
        'send_invitation_to' => 'Inviare l’invito a %s',
    
        'cannot_find_user' => 'Impossibile trovare l‘utente',
    
        'deleted_invitation_successfully' => 'Invito eliminato con successo',
    
        'cannot_find_invitation_to_delete' => 'Impossibile trovare l’invito da cancellare; si prega di riprovare più tardi.',
    
        'comment' => 'Commento',
    
        'confirm' => 'Confermare',
    
        'confirmed_invitation_successfully' => 'Invito confermato con successo',
    
];