<?php
// Autogenerated by Translator Builder

return [
    
        'accountActivated_subject_1' => 'Action required: Activate your account',
    
        'accountActivated_line_2' => 'Thank you for signing up on Talented Europe.',
    
        'accountActivated_line_3' => 'Please verify Your Email Address by clicking the link below.',
    
        'accountActivated_action_4' => 'Confirm my account',
    
        'accountActivated_line_5' => 'Thank you for using our application',
    
        'changeInstitution_subject_1' => '%s has invited you as referee on Talented Europe.',
    
        'changeInstitution_line_2' => '%s has invited you as referee on Talented Europe.',
    
        'changeInstitution_line_3' => 'Since you\'re already a Talented Europe referee we need to you to confirm your change to this institution',
    
        'changeInstitution_action_4' => 'Confirm change',
    
        'changeInstitution_line_5' => 'Thank you for using our application!',
    
        'institutionRemoved.subject_1' => '%s has removed you from his Institution on Talented Europe',
    
        'institutionRemoved.line_2' => '%s has removed you from his Institution on Talented Europe. Please get in contact with them if you were removed by error, so they can fix this situation',
    
        'institutionRemoved.line_3' => 'Thank you for using our application!',
    
        'inviteCreated_subject_1' => '%s has invited you as referee on Talented Europe',
    
        'inviteCreated_line_2' => '%s has invited you as referee on Talented Europe',
    
        'inviteCreated_line_3' => 'We need you to create your user clicking the following link.',
    
        'inviteCreated_action_4' => 'Create my account',
    
        'inviteCreated_line_5' => 'Thank you for using our application!',
    
        'validatorRequested_subject_1' => '%s has asked you as referee his profile in Talented europe',
    
        'validatorRequested_line_2' => 'Hello %s',
    
        'validatorRequested_line_3' => '%s has invited you as referee on Talented Europe.',
    
        'validatorRequested_line_4' => 'We need you to resend this email to the institution you work for so they can register using the following link',
    
        'validatorRequested_line_5' => 'Please note that if they register using clicking the following button you will be invited automatically into their institution',
    
        'validatorRequested_action_6' => 'Create Institution account',
    
        'validatorRequested_line_7' => 'Thank you for using our application!',
    
];
