<?php
// Autogenerated by Translator Builder

return [
    
        'meta_title' => 'Talented Europe | Links young talent to employers across europe',
    
        'tagline' => 'Links <br/> <strong>young talent</strong> to <strong>employers</strong> <br/> across <strong>europe</strong>',
    
        'days' => 'days',
    
        'hours' => 'hours',
    
        'minutes' => 'minutes',
    
        'seconds' => 'seconds',
    
        'more' => 'Find more',
    
        'what_is_title' => 'What is Talented Europe?',
    
        'what_is_cta' => '<strong>Discover more!</strong> Get the brochure',
    
        'what_is_text_1' => 'Can you imagine being able to hire the best students in whichever European country? Would you like to be part of the elite student sector in Europe? <strong>Thousands of companies will have direct access to your contact information</strong>, and the better marks you get the greater choices you will have to get a nice job.',
    
        'what_is_text_2' => 'That is what Talented Europe offers. A showcase with a ranking of the best students in Europe. A simple idea which joins employers and students. <strong>The meeting point of excellence.</strong>',
    
        'subscribe_title' => 'Subscribe to follow our updates',
    
        'subscribe_text' => 'Get notified about all the events and news happening around Talented Europe',
    
        'subscribe_form_placeholder' => 'Enter email address',
    
        'subscribe_btn_text' => 'subscribe',
    
        'subscribe_follow_text' => 'or follow us on:',
    
        'subscribe_text_question' => 'Get Talented Europe news into your inbox.<br/>Feel free to give us your answer for: What is talent for you?',
    
        'meta_description' => 'An Erasmus Plus project which makes the business of matching top students to job and internship opportunities across Europe much easier',
    
        'coming_soon' => 'Coming Soon',
    
        'search_placeholder' => 'What are you looking for',
    
        'search_where' => 'Where',
    
        'search_btn' => 'Search',
    
        'statistics_title' => 'Statistics',
    
        'contacts' => 'Contacts between students and companies',
    
        'companies_institutions' => 'Companies and Institutions',
    
        'students_title' => 'Talented students',
    
        'no_students' => 'No students available',
    
        'join_talented_europe_today' => 'Join Talented Europe today!',
    
        'talented_for_students' => '<strong>For students</strong> - Talented Europe will enhance your employability with the endorsement of your tutors and put you in touch with employers across Europe for internships or first career jobs.',
    
        'talented_for_employers' => '<strong>For employers</strong> - Talented Europe will link you with talented young students across Europe and help you find the right person who can contribute to your organisation’s success with the special talents and skills that you are looking for.',
    
        'go_to_app' => 'Go to application',
    
];