<?php
// Autogenerated by Translator Builder

return [
    
        'remember_me' => 'Remember Me',
    
        'sign_in' => 'Sign in',
    
        'login_title' => 'Login',
    
        'login_btn' => 'Login',
    
        'sign_in_features' => 'Sign in to access',
    
];