<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'Short-cycle tertiary education',
    
        'studies_level_6' => 'Bachelor’s or equivalent',
    
        'studies_level_7' => 'Master’s or equivalent',
    
        'studies_level_8' => 'Doctoral or equivalent',
    
        'company_activity' => 'Activity sector',
    
        'company_contact_person' => 'Contact person',
    
        'company_representative' => 'Legal representative (Person in charge)',
    
        'company_what_is_talent' => 'What is talent for you?',
    
        'institution_certificate' => 'Certificate of authenticity',
    
        'city' => 'City',
    
        'country' => 'Country',
    
        'institution_certificate_template_download' => 'Download template',
    
        'fiscal_id' => 'Fiscal ID',
    
        'institution_hei' => 'Higher education institution',
    
        'institution_ufa' => 'University Faculty',
    
        'insitution_his' => 'Highschool',
    
        'legal_representative' => 'Legal representative (person in charge)',
    
        'institution_pic' => 'PIC',
    
        'postal_code' => 'Postal code',
    
        'institution_sig_stamp_text' => 'Signature and stamp',
    
        'institution_vet' => 'Vocational education and training',
    
        'student_academic_info' => 'Academic information',
    
        'address' => 'Address',
    
        'student_certificate' => 'Certificate',
    
        'clear_btn' => 'Clear',
    
        'student_experience_company' => 'Company',
    
        'student_completed_studies' => 'Completed studies',
    
        'student_course' => 'Course',
    
        'student_date' => 'Date',
    
        'student_birthdate' => 'Date of birth',
    
        'student_study_level' => 'Level',
    
        'student_describe_talent' => 'Describe briefly your talent',
    
        'email' => 'Email',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Field of studies',
    
        'student_study_from' => 'From',
    
        'student_study_grade_card' => 'Grade card',
    
        'student_languages' => 'Languages',
    
        'load_btn' => 'Load',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Name',
    
        'nationality' => 'Nationality',
    
        'student_personal_information' => 'Personal information',
    
        'student_personal_skills' => 'Personal skills',
    
        'phone' => 'Phone',
    
        'position' => 'Position',
    
        'student_professional_skills' => 'Professional skills',
    
        'student_proposed_validator' => 'Proposed validator',
    
        'save_btn' => 'Save',
    
        'student_study_scanned_document' => 'Scanned document',
    
        'student_validator' => 'If you don\'t specify a validator it will be automatically asigned',
    
        'surname' => 'Surname',
    
        'student_study_to' => 'To',
    
        'student_training' => 'Training',
    
        'upload_btn' => 'Upload',
    
        'student_work_experience' => 'Work experience',
    
        'validator_department' => 'Department',
    
        'password' => 'Password',
    
        'confirm_password' => 'Confirm password',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'I agree with the terms of use',
    
        'i_agree_with' => 'I agree with',
    
        'the_terms_of_use' => 'the terms of use',
    
        'create_account' => 'Create a new account',
    
        'forgot_password' => 'Forgot your password?',
    
        'administration' => 'Administration',
    
        'architecture-amp-construction' => 'Architecture & Construction',
    
        'art-amp-culture' => 'Art & Culture',
    
        'banking-and-or-finance-amp-insurance' => 'Banking and/or Finance & Insurance',
    
        'business-amp-consulting' => 'Business & Consulting',
    
        'communication-amp-media-amp-pr' => 'Communication & Media & PR',
    
        'consumer-goods' => 'Consumer Goods',
    
        'customer-service' => 'Customer Service',
    
        'design' => 'Design',
    
        'education-amp-training' => 'Education & Training',
    
        'engineering' => 'Engineering',
    
        'hospitality-amp-tourism' => 'Hospitality & tourism',
    
        'human-resources' => 'Human Resources',
    
        'it-amp-web' => 'IT & Web',
    
        'legal' => 'Legal',
    
        'logistics' => 'Logistics',
    
        'manufacturing' => 'Manufacturing',
    
        'marketing-amp-advertising' => 'Marketing & Advertising',
    
        'medicine-amp-pharmaceutics' => 'Medicine & Pharmaceutics',
    
        'politics' => 'Politics',
    
        'quality-assurance-amp-safety' => 'Quality Assurance & Safety',
    
        'real-estate' => 'Real Estate',
    
        'research-amp-development' => 'Research & Development',
    
        'retail-amp-wholesale' => 'Retail & Wholesale',
    
        'sales' => 'Sales',
    
        'social-work' => 'Social Work',
    
        'sport-and-or-health-amp-wellness' => 'Sport and/or Health & Wellness',
    
        'technology-amp-telecommunications' => 'Technology & Telecommunications',
    
        'business-studies-and-or-management-science' => 'Business Studies and/or Management Science',
    
        'engineering-and-or-technology' => 'Engineering and/or Technology',
    
        'social-sciences' => 'Social Sciences',
    
        'languages-and-philological-sciences' => 'Languages and Philological Sciences',
    
        'communication-and-information-sciences' => 'Communication and Information Sciences',
    
        'humanities' => 'Humanities',
    
        'education-and-or-teacher-training' => 'Education and/or Teacher Training',
    
        'law' => 'Law',
    
        'art-and-design' => 'Art and Design',
    
        'architecture-and-or-urban-and-regional-planning' => 'Architecture and/or Urban and Regional Planning',
    
        'natural-sciences' => 'Natural Sciences',
    
        'mathematics-and-or-informatics' => 'Mathematics and/or Informatics',
    
        'medical-sciences' => 'Medical Sciences',
    
        'geography-and-or-geology' => 'Geography and/or Geology',
    
        'agriculture-sciences' => 'Agriculture Sciences',
    
        'Lang_level_A1' => 'A1: Breakthrough or beginner',
    
        'Lang_level_A2' => 'A2: Waystage or elementary',
    
        'Lang_level_B1' => 'B1: Threshold or intermediate        ',
    
        'Lang_level_B2' => 'B2: Vantage or upper intermediate',
    
        'Lang_level_C1' => 'C1: Effective operational proficiency or advanced',
    
        'Lang_level_C2' => 'C2: Mastery or proficiency',
    
        'logo' => 'Logo',
    
        'my_profile' => 'My profile',
    
        'profile' => 'Profile',
    
        'profile_visibility' => 'Profile Visibility',
    
        'profile_visibility_visible' => 'Visible. Can be searched, viewed',
    
        'profile_visibility_hidden' => 'Hidden. Cannot be searched or viewed',
    
        'notifications' => 'Notifications',
    
        'notifications_enabled' => 'Enabled. You\'ll receive emails once a day if a student wants to get in contact with you',
    
        'notifications_disabled' => 'Disabled. You won\'t receive any emails, except for announcements about the service',
    
        'about' => 'About',
    
        'company_logo' => 'Company Logo',
    
        'social_and_web' => 'Social networks and website',
    
        'facebook_page_url' => 'Facebook page url',
    
        'twitter_page_url' => 'Twitter page url',
    
        'linkedin_page_url' => 'Linkedin page url',
    
        'web_url' => 'Website url',
    
        'what_is_talent_for_you_in_a_few_words' => 'Explain us what is talent for you in a few words',
    
        'most_valuable_skills_for_company' => 'A list of the most valuable skills for the company',
    
        'setup_alternative_contact' => 'Setup an alternative contact user that will receive all the notifications instead of the main account',
    
        'update_settings' => 'Update settings',
    
        'change_your_password' => 'Change your password',
    
        'new_password' => 'New password',
    
        'repeat_new_password' => 'Repeat new password',
    
        'save_new_password' => 'Save new password',
    
        'career_and_skills' => 'Career and Skills',
    
        'my_photo' => 'My Photo',
    
        'download_curriculum' => 'Download curriculum',
    
        'my_talent' => 'My talent',
    
        'referee_name' => 'Referee name',
    
        'referee_email' => 'Referee email',
    
        'get_your_profile_refereed' => 'Get your profile refereed',
    
        'want_to_view_all_details_of_student' => 'Do you want to view all the details of this student?',
    
        'education' => 'Education',
    
        'lives_in' => 'Lives in',
    
        'born_on' => 'Born on',
    
        'studied_in' => 'Studied in',
    
        'skilled_in' => 'Skilled in',
    
        'refereed_by' => 'Refereed by',
    
        'refereeing_pending' => 'Refereeing pending',
    
        'skills' => 'Skills',
    
        'professional' => 'Professional',
    
        'personal' => 'Personal',
    
        'legend' => 'Legend',
    
        'set_by_both_parties' => 'Set by both parties',
    
        'set_by_referee_or_student' => 'Set by either the referee or the student',
    
        'study' => 'Study|Studies',
    
        'date_not_specified' => 'Date not specified',
    
        'get_in_contact' => 'Get in contact',
    
        'want_to_show_this_company_how_talented_you_are' => 'Do you want to show this company how talented you are?',
    
        'we_are_in' => 'We are in',
    
        'we_are_looking_for_people_skilled_in' => 'We\'re looking for people skilled in',
    
        'we_think_that_talent_is' => 'We think that talent is',
    
        'not_enough_information' => 'Not enough information',
    
        'fix_the_following_errors' => 'You\'ll need to fix the following errors',
    
        'click_on_button_to_fill_required_fields' => 'Please click the following button to fill the required fields.',
    
        'institution_fix_the_following_errors' => 'You\'ll need to fix the following errors or your referees won\'t be able to validate profiles',
    
        'my_institution' => 'My Institution',
    
        'required' => 'Required',
    
        'remove_btn' => 'Remove',
    
        'student_study_institution_name' => 'Institution name',
    
        'student_study_course_studies_name' => 'Course/Studies name',
    
        'student_download_certificate' => 'Download Certificate',
    
        'student_download_grade_card' => 'Download Gradecard',
    
        'student_study_add_more' => 'add more studies',
    
        'student_training_course_name' => 'Course name',
    
        'student_training_add' => 'add a training',
    
        'student_training_add_more' => 'add more trainings',
    
        'student_language' => 'Language',
    
        'student_language_name' => 'Language name',
    
        'student_language_level' => 'Language level',
    
        'student_language_add' => 'add a language',
    
        'student_language_add_more' => 'add more languages',
    
        'student_work_experience_to' => 'Work to',
    
        'student_work_experience_from' => 'Work from',
    
        'student_work_experience_add' => 'add a work experience',
    
        'student_work_experience_add_more' => 'add more work experiences',
    
        'add_btn' => 'Add',
    
        'student_professional_skills_remove' => 'Remove professional skill',
    
        'student_professional_skills_add' => 'Add a professional skill',
    
        'profile_readiness' => 'Profile readiness',
    
        'profile_readiness_explanation' => 'Getting your profile refereed gives a third party opinion of you and helps increasing the possibilities of contact from a company',
    
        'get_a_better_refeer' => 'Get a better refeer improving your profile readiness and improve possibility of company contact',
    
        'request_is_managed_by' => 'Your request is being managed by',
    
        'cant_find_your_institution' => 'Can\'t find your institution? ask your referee and institution to join Talented Europe',
    
        'this_step_sends_an_email_to_your_referee' => 'This step sends an email to your referee with instructions on how to join Talented Europe, automatically registers him as referee once his institution joins, and adds you to the refeeral queue',
    
        'send_invitation' => 'Send invitation',
    
        'profile_validated_successfully' => 'Your profile was validated successfully',
    
        'referee_said_about_you' => 'This is what your referee said about you',
    
        'profile_validated_denied' => 'Your profile was denied',
    
        'not_enough_data_to_do_a_refeer' => 'We don\'t have enough data from you to be able to do a refeer.',
    
        'progress_account_setup' => 'Account setup',
    
        'progress_refer_your_profile' => 'Refer your profile',
    
        'progress_not_refereed' => 'Not refereed',
    
        'progress_completed' => 'Completed',
    
        'you_must_put_referee_email' => '<strong>Please note:</strong> You must put the referee email, not the one form the institution',
    
        'leave_institution' => 'Leave institution?',
    
        'do_you_want_to_leave_institution' => 'Do you want to leave the institution? this will send the pending validation requests back to it, and you won\'t be able to validate anyone until another institution invites you back',
    
        'leave_institution_button' => 'Yes! Leave this academic institution',
    
        'your_profile_is_empty' => 'Your profile is empty!',
    
        'tab_changes_not_saved' => 'Tab changes haven\'t been saved, you may lose some data',
    
        'save_changes' => 'Save changes',
    
        'continue_without_saving' => 'Continue without saving',
    
        'im_here' => 'I\'m here!',
    
        'cannot_send_more_alerts_to_this_company_today' => 'You cannot send more alerts to this company today',
    
        'tell_the_company_that_you_be_interested' => 'Tell the company that you may be interested to work for them',
    
        'alert_sent_successfully' => 'Alert sent successfully to the company',
    
        'you_have_already_sent_an_alert_to_this_company' => 'You have already sent an alert to this company',
    
        'no_matches' => 'No matches',
    
        'find_your_academic_institution' => 'Find your Academic Institution',
    
        'choose_referee' => 'Choose referee',
    
        'refer_request' => 'Refer request',
    
        'any_referee' => 'Any referee',
    
];
