<?php
// Autogenerated by Translator Builder

return [
    
        'thank_you_for_signing_up' => 'Thank You for Signing Up!',
    
        'you_will_receive_an_email' => 'You will receive an email with instructions about how to confirm your account in a few minutes.',
    
        'go_back_to_home' => 'Go back to home',
    
        'search_students' => 'Search students',
    
        'search_companies' => 'Search companies',
    
        'register_as_validator' => 'Register as referee',
    
        'there_have_been_some_errors' => 'There have been some errors',
    
        'i_am_a' => 'I am a',
    
        'all_fields_are_required' => 'All fields are required',
    
        'confirmation_email_may_take_few_minutes' => 'Your confirmation email may take a few minutes to arrive, make sure you also check out your spam folder',
    
        'registration_complete_successfully' => 'Registration complete successfully you may log in now.',
    
        'register_success' => 'Register success',
    
        'register' => 'Register',
    
        'invited_by' => 'You have been invited by',
    
];
