<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Date of request',
    
        'pending' => 'Pending',
    
        'validated' => 'Validated',
    
        'not_validated' => 'Not validated',
    
        'no_students' => 'No students',
    
        'confirm_validation' => 'Confirm refereeing',
    
        'are_you_sure_you_want_to_finish_refereeing' => 'Are you sure you want to finish refereeing this student?',
    
        'reason' => 'Reason',
    
        'criteria' => 'Student does not meet criteria',
    
        'nostudent' => 'Student hasn\'t attended this school/institution',
    
];