<?php
// Autogenerated by Translator Builder

return [
    
        'not_allowed' => 'Interdit',
    
        'not_allowed_to_do_this_action' => 'Vous n&apos;êtes pas autorisé à faire cette action.',
    
        'can_try_searching_for' => 'Vous pouvez essayer de rechercher',
    
        'page_not_found' => 'Page non trouvée',
    
        'we_didnt_find_the_page' => 'Nous n&apos;avons pas trouvé la page que vous recherchiez.',
    
        'internal_server_error' => 'Erreur du Serveur Interne ',
    
        'an_error_happened' => 'Une erreur s&apos;est produite, les administrateurs ont été informés et ce problème sera résolu rapidement, veuillez essayer plus tard.',
    
        'meanwhile_can_searching_for' => 'Pendant ce temps, vous pouvez essayer de chercher',
    
        'be_right_back' => 'On revient tout de suite',
    
        'not_found' => 'Non trouvé',
    
        'unauthorized_action' => 'Action non autorisée',
    
];