<?php
// Autogenerated by Translator Builder

return [
    
        'AT' => 'l´Autriche',
    
        'BE' => 'la Belgique',
    
        'BG' => 'la Bulgarie',
    
        'HR' => 'la Croatie',
    
        'CY' => 'Chypre',
    
        'CZ' => 'la République tchèque',
    
        'DK' => 'le Danemark',
    
        'EE' => 'l´Estonie',
    
        'FI' => 'la Finlande',
    
        'FR' => 'la France',
    
        'DE' => 'l´Allemagne',
    
        'GR' => 'la Grèce',
    
        'HU' => 'la Hongrie',
    
        'IE' => 'l´Irlande',
    
        'IT' => 'l´Italie',
    
        'LV' => 'la Lettonie',
    
        'LT' => 'la Lituanie',
    
        'LU' => 'le Luxembourg',
    
        'MT' => 'Malte',
    
        'NL' => 'les Pays-Bas',
    
        'PL' => 'la Pologne',
    
        'PT' => 'le Portugal',
    
        'RO' => 'la Roumanie',
    
        'SK' => 'la Slovaquie',
    
        'SI' => 'la Slovénie',
    
        'ES' => 'l´Espagne',
    
        'SE' => 'la Suède',
    
        'GB' => 'le Royaume-Uni',
    
        'follow_us' => 'Suivez nous',
    
        'login_btn' => 'le logiciel',
    
        'register_btn' => 'connectez-vous',
    
        'search_info' => 'recherche',
    
        'company_plural' => 'Les sociétés',
    
        'institution_plural' => 'Les institutions',
    
        'student_plural' => 'Les étudiants',
    
        'company' => 'la société|Les sociétés',
    
        'institution' => 'L\'institution|Les institutions',
    
        'student' => 'L\'étudiant|Les étudiants',
    
        'more_btn' => 'voir plus',
    
        'home' => 'Accueil',
    
        'blog' => 'Blog',
    
        'cookies' => 'Informations sur les cookies',
    
        'privacy_policy' => 'Politique de confidentialité',
    
        'footer_partners' => 'Partenaires',
    
        'cookie_text' => 'Ce site utilise des cookies pour améliorer votre expérience en visitant le site. En utilisant ce site, vous acceptez de leur utilisation. Plus d\'informations sur nous et comment nous utilisons ces fichiers, et la façon dont nous traitons, voir notre vie privée <a href="/vyhlásení notification cookies </a>',
    
        'cookie_accept' => 'fermer',
    
        'logout_btn' => 'Se déconnecter',
    
        'less_btn' => 'Voir moins',
    
        'status' => 'Statut',
    
        'not_enough_data_to_show_profile' => 'Nous ne disposons pas de suffisamment de données pour pouvoir afficher votre profil.',
    
        'click_on_link_to_fill_required_fields' => 'Veuillez cliquer sur le lien suivant pour remplir les champs obligatoires.',
    
        'set_up_my_profile' => 'Créer mon profil',
    
        'or' => 'Ou bien',
    
        'error' => 'Erreur',
    
        'successfully_done' => 'Successfully done',
    
        'success' => 'Réussi',
    
        'older' => 'Précedents',
    
        'next' => 'Suivants',
    
        'yes' => 'Oui',
    
        'no' => 'Non',
    
        'AF' => 'Afghanistan',
    
        'AX' => 'Åland Islands',
    
        'AL' => 'Albania',
    
        'DZ' => 'Algeria',
    
        'AS' => 'American Samoa',
    
        'AD' => 'Andorra',
    
        'AO' => 'Angola',
    
        'AI' => 'Anguilla',
    
        'AQ' => 'Antarctica',
    
        'AG' => 'Antigua and Barbuda',
    
        'AR' => 'Argentina',
    
        'AM' => 'Armenia',
    
        'AW' => 'Aruba',
    
        'AU' => 'Australia',
    
        'AZ' => 'Azerbaijan',
    
        'BS' => 'Bahamas',
    
        'BH' => 'Bahrain',
    
        'BD' => 'Bangladesh',
    
        'BB' => 'Barbados',
    
        'BY' => 'Belarus',
    
        'BZ' => 'Belize',
    
        'BJ' => 'Benin',
    
        'BM' => 'Bermuda',
    
        'BT' => 'Bhutan',
    
        'BO' => 'Bolivia (Plurinational State of)',
    
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
    
        'BA' => 'Bosnia and Herzegovina',
    
        'BW' => 'Botswana',
    
        'BV' => 'Bouvet Island',
    
        'BR' => 'Brazil',
    
        'IO' => 'British Indian Ocean Territory',
    
        'BN' => 'Brunei Darussalam',
    
        'BF' => 'Burkina Faso',
    
        'BI' => 'Burundi',
    
        'CV' => 'Cabo Verde',
    
        'KH' => 'Cambodia',
    
        'CM' => 'Cameroon',
    
        'CA' => 'Canada',
    
        'KY' => 'Cayman Islands',
    
        'CF' => 'Central African Republic',
    
        'TD' => 'Chad',
    
        'CL' => 'Chile',
    
        'CN' => 'China',
    
        'CX' => 'Christmas Island',
    
        'CC' => 'Cocos (Keeling) Islands',
    
        'CO' => 'Colombia',
    
        'KM' => 'Comoros',
    
        'CG' => 'Congo',
    
        'CD' => 'Congo (Democratic Republic of the)',
    
        'CK' => 'Cook Islands',
    
        'CR' => 'Costa Rica',
    
        'CI' => 'Côte d\'Ivoire',
    
        'CU' => 'Cuba',
    
        'CW' => 'Curaçao',
    
        'DJ' => 'Djibouti',
    
        'DM' => 'Dominica',
    
        'DO' => 'Dominican Republic',
    
        'EC' => 'Ecuador',
    
        'EG' => 'Egypt',
    
        'SV' => 'El Salvador',
    
        'GQ' => 'Equatorial Guinea',
    
        'ER' => 'Eritrea',
    
        'ET' => 'Ethiopia',
    
        'FK' => 'Falkland Islands (Malvinas)',
    
        'FO' => 'Faroe Islands',
    
        'FJ' => 'Fiji',
    
        'GF' => 'French Guiana',
    
        'PF' => 'French Polynesia',
    
        'TF' => 'French Southern Territories',
    
        'GA' => 'Gabon',
    
        'GM' => 'Gambia',
    
        'GE' => 'Georgia',
    
        'GH' => 'Ghana',
    
        'GI' => 'Gibraltar',
    
        'GL' => 'Greenland',
    
        'GD' => 'Grenada',
    
        'GP' => 'Guadeloupe',
    
        'GU' => 'Guam',
    
        'GT' => 'Guatemala',
    
        'GG' => 'Guernsey',
    
        'GN' => 'Guinea',
    
        'GW' => 'Guinea-Bissau',
    
        'GY' => 'Guyana',
    
        'HT' => 'Haiti',
    
        'HM' => 'Heard Island and McDonald Islands',
    
        'VA' => 'Holy See',
    
        'HN' => 'Honduras',
    
        'HK' => 'Hong Kong',
    
        'IS' => 'Iceland',
    
        'IN' => 'India',
    
        'ID' => 'Indonesia',
    
        'IR' => 'Iran (Islamic Republic of)',
    
        'IQ' => 'Iraq',
    
        'IM' => 'Isle of Man',
    
        'IL' => 'Israel',
    
        'JM' => 'Jamaica',
    
        'JP' => 'Japan',
    
        'JE' => 'Jersey',
    
        'JO' => 'Jordan',
    
        'KZ' => 'Kazakhstan',
    
        'KE' => 'Kenya',
    
        'KI' => 'Kiribati',
    
        'KP' => 'Korea (Democratic People\'s Republic of)',
    
        'KR' => 'Korea (Republic of)',
    
        'KW' => 'Kuwait',
    
        'KG' => 'Kyrgyzstan',
    
        'LA' => 'Lao People\'s Democratic Republic',
    
        'LB' => 'Lebanon',
    
        'LS' => 'Lesotho',
    
        'LR' => 'Liberia',
    
        'LY' => 'Libya',
    
        'LI' => 'Liechtenstein',
    
        'MO' => 'Macao',
    
        'MK' => 'Macedonia (the former Yugoslav Republic of)',
    
        'MG' => 'Madagascar',
    
        'MW' => 'Malawi',
    
        'MY' => 'Malaysia',
    
        'MV' => 'Maldives',
    
        'ML' => 'Mali',
    
        'MH' => 'Marshall Islands',
    
        'MQ' => 'Martinique',
    
        'MR' => 'Mauritania',
    
        'MU' => 'Mauritius',
    
        'YT' => 'Mayotte',
    
        'MX' => 'Mexico',
    
        'FM' => 'Micronesia (Federated States of)',
    
        'MD' => 'Moldova (Republic of)',
    
        'MC' => 'Monaco',
    
        'MN' => 'Mongolia',
    
        'ME' => 'Montenegro',
    
        'MS' => 'Montserrat',
    
        'MA' => 'Morocco',
    
        'MZ' => 'Mozambique',
    
        'MM' => 'Myanmar',
    
        'NA' => 'Namibia',
    
        'NR' => 'Nauru',
    
        'NP' => 'Nepal',
    
        'NC' => 'New Caledonia',
    
        'NZ' => 'New Zealand',
    
        'NI' => 'Nicaragua',
    
        'NE' => 'Niger',
    
        'NG' => 'Nigeria',
    
        'NU' => 'Niue',
    
        'NF' => 'Norfolk Island',
    
        'MP' => 'Northern Mariana Islands',
    
        'NO' => 'Norway',
    
        'OM' => 'Oman',
    
        'PK' => 'Pakistan',
    
        'PW' => 'Palau',
    
        'PS' => 'Palestine, State of',
    
        'PA' => 'Panama',
    
        'PG' => 'Papua New Guinea',
    
        'PY' => 'Paraguay',
    
        'PE' => 'Peru',
    
        'PH' => 'Philippines',
    
        'PN' => 'Pitcairn',
    
        'PR' => 'Puerto Rico',
    
        'QA' => 'Qatar',
    
        'RE' => 'Réunion',
    
        'RU' => 'Russian Federation',
    
        'RW' => 'Rwanda',
    
        'BL' => 'Saint Barthélemy',
    
        'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
    
        'KN' => 'Saint Kitts and Nevis',
    
        'LC' => 'Saint Lucia',
    
        'MF' => 'Saint Martin (French part)',
    
        'PM' => 'Saint Pierre and Miquelon',
    
        'VC' => 'Saint Vincent and the Grenadines',
    
        'WS' => 'Samoa',
    
        'SM' => 'San Marino',
    
        'ST' => 'Sao Tome and Principe',
    
        'SA' => 'Saudi Arabia',
    
        'SN' => 'Senegal',
    
        'RS' => 'Serbia',
    
        'SC' => 'Seychelles',
    
        'SL' => 'Sierra Leone',
    
        'SG' => 'Singapore',
    
        'SX' => 'Sint Maarten (Dutch part)',
    
        'SB' => 'Solomon Islands',
    
        'SO' => 'Somalia',
    
        'ZA' => 'South Africa',
    
        'GS' => 'South Georgia and the South Sandwich Islands',
    
        'SS' => 'South Sudan',
    
        'LK' => 'Sri Lanka',
    
        'SD' => 'Sudan',
    
        'SR' => 'Suriname',
    
        'SJ' => 'Svalbard and Jan Mayen',
    
        'SZ' => 'Swaziland',
    
        'CH' => 'Switzerland',
    
        'SY' => 'Syrian Arab Republic',
    
        'TW' => 'Taiwan, Province of China',
    
        'TJ' => 'Tajikistan',
    
        'TZ' => 'Tanzania, United Republic of',
    
        'TH' => 'Thailand',
    
        'TL' => 'Timor-Leste',
    
        'TG' => 'Togo',
    
        'TK' => 'Tokelau',
    
        'TO' => 'Tonga',
    
        'TT' => 'Trinidad and Tobago',
    
        'TN' => 'Tunisia',
    
        'TR' => 'Turkey',
    
        'TM' => 'Turkmenistan',
    
        'TC' => 'Turks and Caicos Islands',
    
        'TV' => 'Tuvalu',
    
        'UG' => 'Uganda',
    
        'UA' => 'Ukraine',
    
        'AE' => 'United Arab Emirates',
    
        'US' => 'United States of America',
    
        'UM' => 'United States Minor Outlying Islands',
    
        'UY' => 'Uruguay',
    
        'UZ' => 'Uzbekistan',
    
        'VU' => 'Vanuatu',
    
        'VE' => 'Venezuela (Bolivarian Republic of)',
    
        'VN' => 'Viet Nam',
    
        'VG' => 'Virgin Islands (British)',
    
        'VI' => 'Virgin Islands (U.S.)',
    
        'WF' => 'Wallis and Futuna',
    
        'EH' => 'Western Sahara',
    
        'YE' => 'Yemen',
    
        'ZM' => 'Zambia',
    
        'ZW' => 'Zimbabwe',
    
];
