<?php
// Autogenerated by Translator Builder

return [
    
        'AT' => 'l´Autriche',
    
        'BE' => 'la Belgique',
    
        'BG' => 'la Bulgarie',
    
        'HR' => 'la Croatie',
    
        'CY' => 'Chypre',
    
        'CZ' => 'la République tchèque',
    
        'DK' => 'le Danemark',
    
        'EE' => 'l´Estonie',
    
        'FI' => 'la Finlande',
    
        'FR' => 'la France',
    
        'DE' => 'l´Allemagne',
    
        'GR' => 'la Grèce',
    
        'HU' => 'la Hongrie',
    
        'IE' => 'l´Irlande',
    
        'IT' => 'l´Italie',
    
        'LV' => 'la Lettonie',
    
        'LT' => 'la Lituanie',
    
        'LU' => 'le Luxembourg',
    
        'MT' => 'Malte',
    
        'NL' => 'les Pays-Bas',
    
        'PL' => 'la Pologne',
    
        'PT' => 'le Portugal',
    
        'RO' => 'la Roumanie',
    
        'SK' => 'la Slovaquie',
    
        'SI' => 'la Slovénie',
    
        'ES' => 'l´Espagne',
    
        'SE' => 'la Suède',
    
        'GB' => 'le Royaume-Uni',
    
        'follow_us' => 'Suivez nous',
    
        'login_btn' => 'le logiciel',
    
        'register_btn' => 'connectez-vous',
    
        'search_info' => 'recherche',
    
        'company_plural' => 'Les sociétés',
    
        'institution_plural' => 'Les institutions',
    
        'student_plural' => 'Les étudiants',
    
        'company' => 'la société|Les sociétés',
    
        'institution' => 'L\'institution|Les institutions',
    
        'student' => 'L\'étudiant|Les étudiants',
    
        'more_btn' => 'voir plus',
    
        'home' => 'Accueil',
    
        'blog' => 'Blog',
    
        'cookies' => 'Informations sur les cookies',
    
        'privacy_policy' => 'Politique de confidentialité',
    
        'footer_partners' => 'Partenaires',
    
        'cookie_text' => 'This website uses cookies to help us give you the best experience when you visit. By using this website you consent to our use of these cookies. Find out more about how we use cookies and how to manage them by reading our <a href="/privacy-policy">cookie notice</a>',
    
        'cookie_accept' => 'fermer',
    
        'logout_btn' => 'Se déconnecter',
    
        'less_btn' => 'Voir moins',
    
        'status' => 'Statut',
    
        'not_enough_data_to_show_profile' => 'Nous ne disposons pas de suffisamment de données pour pouvoir afficher votre profil.',
    
        'click_on_link_to_fill_required_fields' => 'Veuillez cliquer sur le lien suivant pour remplir les champs obligatoires.',
    
        'set_up_my_profile' => 'Créer mon profil',
    
        'or' => 'Ou bien',
    
        'error' => 'Erreur',
    
        'successfully_done' => 'Successfully done',
    
        'success' => 'Réussi',
    
        'older' => 'Précedents',
    
        'next' => 'Suivants',
    
        'yes' => 'Oui',
    
        'no' => 'Non',
    
];
