<?php
// Autogenerated by Translator Builder

return [
    
        'AT' => 'l´Autriche',
    
        'BE' => 'la Belgique',
    
        'BG' => 'la Bulgarie',
    
        'HR' => 'la Croatie',
    
        'CY' => 'Chypre',
    
        'CZ' => 'la République tchèque',
    
        'DK' => 'le Danemark',
    
        'EE' => 'l´Estonie',
    
        'FI' => 'la Finlande',
    
        'FR' => 'la France',
    
        'DE' => 'l´Allemagne',
    
        'GR' => 'la Grèce',
    
        'HU' => 'la Hongrie',
    
        'IE' => 'l´Irlande',
    
        'IT' => 'l´Italie',
    
        'LV' => 'la Lettonie',
    
        'LT' => 'la Lituanie',
    
        'LU' => 'le Luxembourg',
    
        'MT' => 'Malte',
    
        'NL' => 'les Pays-Bas',
    
        'PL' => 'la Pologne',
    
        'PT' => 'le Portugal',
    
        'RO' => 'la Roumanie',
    
        'SK' => 'la Slovaquie',
    
        'SI' => 'la Slovénie',
    
        'SP' => 'l´Espagne',
    
        'SE' => 'la Suède',
    
        'UK' => 'le Royaume-Uni',
    
        'follow_us' => 'Suivez nous',
    
        'login_btn' => 'le logiciel',
    
        'register_btn' => 'connectez-vous',
    
        'search_info' => 'recherche',
    
        'company_plural' => 'Les sociétés',
    
        'institution_plural' => 'Les institutions',
    
        'student_plural' => 'Les étudiants',
    
        'company' => 'la société|Les sociétés',
    
        'institution' => 'L&apos;institution|Les institutions',
    
        'student' => 'L&apos;étudiant|Les étudiants',
    
        'more_btn' => 'voir plus',
    
        'home' => 'Accueil',
    
        'blog' => 'Blog',
    
        'cookies' => 'Informations sur les cookies',
    
        'privacy_policy' => 'Politique de confidentialité',
    
        'partners' => 'Partenaires',
    
        'cookie_text' => '',
    
        'cookie_accept' => 'fermer',
    
        'logout_btn' => 'Se déconnecter',
    
];