<?php
// Autogenerated by Translator Builder

return [
    
        'meta_title' => 'Talented Europe qui relie des jeunes talents et des employeurs dans toute l´Europe',
    
        'tagline' => 'qui relie<br/> <strong>des jeunes talents</strong> et <strong>des employeurs</strong><br/> dans toute <strong>l´Europe</strong>',
    
        'days' => 'jours',
    
        'hours' => 'heures',
    
        'minutes' => 'minutes',
    
        'seconds' => 'secondes',
    
        'more' => 'en savoir plus',
    
        'what_is_title' => 'Qu´est-ce que l´Europe des talents?',
    
        'what_is_cta' => '<strong>Découvrir plus.</strong> Recevoir la brochure.',
    
        'what_is_text_1' => 'Et si vous aviez l&apos;opportunité d&apos;embaucher les meilleurs étudiants d&apos;Europe?

Etudiants, et si vous aviez la possibilité de faire partie de l&apos;élite en Europe? 

Des milliers d´entreprises auront accès direct à vos coordonnées. 

Obtenez les meilleurs notes pour accéder à un plus grand choix d&apos;offres d&apos;emploi',
    
        'what_is_text_2' => 'C&apos;est ce que l&apos;Europe des talents vous offre.

Une vitrine du classement des meilleurs étudiants en Europe.  Une idée simple qui relie des employeurs et des étudiants. Le point de rencontre de l´excellence.',
    
        'subscribe_title' => 'Abonnez vous et suivez nos actualités',
    
        'subscribe_text' => 'Etre averti de tous les événements et nouveautés sur l´Europe des talents',
    
        'subscribe_form_placeholder' => 'Entrer une addresse électronique',
    
        'subscribe_btn_text' => 'Abonnez-vous',
    
        'subscribe_follow_text' => 'ou suivez-nous sur',
    
        'subscribe_text_question' => 'Recevez des nouvelles sur Talented Europe par mail',
    
        'meta_description' => 'Projet co-financé par le programme Erasmus Plus qui permet de faciliter l&apos; accès des excellents étudiants  à l&apos;emploi et aux stages en Europe',
    
        'coming_soon' => 'le contenu sera bientot ajouté',
    
        'search_placeholder' => 'Vous recherchez?',
    
        'search_where' => 'où',
    
        'search_btn' => 'Recherche',
    
        'statistics_title' => 'Statistiques',
    
        'contacts' => 'Contacts entre les étudiants et les entreprises',
    
        'companies_institutions' => 'Entreprises et Institutions',
    
        'students_title' => 'les étudiants doués',
    
        'no_students' => 'Aucun étudiant disponible',
    
        'join_talented_europe_today' => 'Rejoignez l&apos;Europe talentueuse dès aujourd&apos;hui!',
    
        'talented_for_students' => '<strong> Pour les étudiants </ strong> - Europe talentueuse améliorera votre employabilité avec l&apos;aval de vos tuteurs et vous mettra en contact avec les employeurs en Europe pour des stages ou des emplois de première carrière.',
    
        'talented_for_employers' => '<strong> Pour les étudiants </strong> - Europe talentueuse améliorera votre employabilité <strong> Pour les employeurs </strong> - Europe talentueuse vous liera avec de jeunes étudiants talentueux en Europe et vous aidera à trouver la bonne personne qui peut contribuer à l&apos;organisation de votre entreprise Réussir avec de vrais talents ayant les compétences que vous recherchez.',
    
        'go_to_app' => 'Aller à l&apos;application',
    
        'what_is_text_1_txt' => 'Et si vous aviez l&apos;opportunité d&apos;embaucher les meilleurs étudiants d&apos;Europe?

Etudiants, et si vous aviez la possibilité de faire partie de l&apos;élite en Europe? 

Des milliers d´entreprises auront accès direct à vos coordonnées. 

Obtenez les meilleurs notes pour accéder à un plus grand choix d&apos;offres d&apos;emploi',
    
        'what_is_text_2_txt' => 'C&apos;est ce que l&apos;Europe des talents vous offre.

Une vitrine du classement des meilleurs étudiants en Europe.  Une idée simple qui relie des employeurs et des étudiants. Le point de rencontre de l´excellence.',
    
];