<?php
// Autogenerated by Translator Builder

return [
    
        'looking_for' => 'Je cherche',
    
        'profile' => 'Profil',
    
        'alerts' => 'Alertes',
    
        'settings' => 'Paramètres',
    
];
