<?php
// Autogenerated by Translator Builder

return [
    
        'company_visited_student_subject' => 'A %s company visited your profile!',
    
        'company_visited_student_body' => 'Hopefully they\'ll get in contact with you ;)',
    
        'student_alerted_company_subject' => 'New Alerts from Talented Europe',
    
        'student_alerted_company_body' => 'Student %s sent you an alert',
    
        'new_validation_subject' => 'En attendant refeeral',
    
        'new_validation_body' => 'Vous avez dans l\'attente d\'un ou plusieurs refeeral étudiant',
    
];