<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'l´enseignement supérieur de type court',
    
        'studies_level_6' => 'le Baccalauréat ou équivalent',
    
        'studies_level_7' => 'la Maîtrise ou équivalent',
    
        'studies_level_8' => 'le Doctorat ou équivalent',
    
        'company_activity' => 'le domaine de l\' activité',
    
        'company_contact_person' => 'la personne a contacter',
    
        'company_representative' => 'le représentant légitime',
    
        'company_what_is_talent' => 'Qu\' est-ce que pour vous le talent?',
    
        'institution_certificate' => 'le certificat d \'originalité',
    
        'city' => 'la ville',
    
        'country' => 'le pays',
    
        'institution_certificate_template_download' => 'téléchargez le modèle',
    
        'fiscal_id' => 'le numéro national d\'identification',
    
        'institution_hei' => 'l\'institution de l\' éducation supérieure',
    
        'institution_ufa' => 'l\'université, la faculté',
    
        'insitution_his' => 'l\' école secondaire',
    
        'legal_representative' => 'le représentant légitime',
    
        'institution_pic' => 'la photo',
    
        'postal_code' => 'le code postal',
    
        'institution_sig_stamp_text' => 'la signature et le cachet',
    
        'institution_vet' => 'la formation professionnelle et les activités professionnelles',
    
        'student_academic_info' => 'les informations académiques',
    
        'address' => 'l\' adresse',
    
        'student_certificate' => 'le certificat ',
    
        'clear_btn' => 'supprimer',
    
        'student_experience_company' => 'la société/ les sociétés',
    
        'student_completed_studies' => 'le niveau d\' instruction',
    
        'student_course' => 'le cours',
    
        'student_date' => 'la date',
    
        'student_birthdate' => 'le lieu de naissance',
    
        'student_study_level' => 'le niveau',
    
        'student_describe_talent' => 'Présentez en bref de votre talent.',
    
        'email' => 'le mél / le mail',
    
        'student_europass' => 'le passeport européen',
    
        'student_study_field' => 'la branche d\' études',
    
        'student_study_from' => 'de',
    
        'student_study_grade_card' => 'le bulletin scolaire',
    
        'student_languages' => 'les langues',
    
        'load_btn' => 'chargement',
    
        'input_max_characters' => 'au maximum',
    
        'name' => 'le nom',
    
        'nationality' => 'la nationalité',
    
        'student_personal_information' => 'les coordonnées',
    
        'student_personal_skills' => 'les capacités personnelles',
    
        'phone' => 'le tétéphone',
    
        'position' => 'la position',
    
        'student_professional_skills' => 'les capacités professionnelles',
    
        'student_proposed_validator' => 'l\' évaluateur proposé',
    
        'save_btn' => 'sauvegarde /sauvegardez',
    
        'student_study_scanned_document' => 'le document numérisé',
    
        'student_validator' => 'Si vous ne présentez aucun évaluateur, il vous sera automatiquement incorporé',
    
        'surname' => 'le nom',
    
        'student_study_to' => 'à qui',
    
        'student_training' => 'l\'expérience',
    
        'upload_btn' => 'enregistrez',
    
        'student_work_experience' => 'les expériences de travail',
    
        'validator_department' => 'la section / la chaire',
    
        'password' => 'le mot de passe',
    
        'confirm_password' => 'Validez le mot de passe',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Je suis d\'accord avec les conditions',
    
        'i_agree_with' => 'I agree with',
    
        'the_terms_of_use' => 'the terms of use',
    
        'create_account' => 'créer un nouveau compte',
    
        'forgot_password' => 'Avez-vous oublié votre mot de passe?',
    
        'administration' => 'Administration',
    
        'architecture-amp-construction' => 'Architecture et construction',
    
        'art-amp-culture' => 'Art et culture',
    
        'banking-and-or-finance-amp-insurance' => 'Banque,finance et/ou assurance',
    
        'business-amp-consulting' => 'Activité commerciale et consultative',
    
        'communication-amp-media-amp-pr' => 'Communication et médias et PR',
    
        'consumer-goods' => 'Biens de consommation',
    
        'customer-service' => 'Service clients',
    
        'design' => 'Design',
    
        'education-amp-training' => 'Formation',
    
        'engineering' => 'Ingénierie',
    
        'hospitality-amp-tourism' => 'Tourisme',
    
        'human-resources' => 'Ressourses  humains',
    
        'it-amp-web' => 'IT et web',
    
        'legal' => 'Droits',
    
        'logistics' => 'Logistique',
    
        'manufacturing' => 'Production',
    
        'marketing-amp-advertising' => 'Marketing et publicité',
    
        'medicine-amp-pharmaceutics' => 'Médecine et pharmacie',
    
        'politics' => 'Politique',
    
        'quality-assurance-amp-safety' => 'Assurance de la qualité et de la sécurité',
    
        'real-estate' => 'Biens immobilers',
    
        'research-amp-development' => 'Recherche et développement',
    
        'retail-amp-wholesale' => 'Commerce de détail et de gros',
    
        'sales' => 'Vente',
    
        'social-work' => 'Service social',
    
        'sport-and-or-health-amp-wellness' => 'Sport et/ou santé et wellness',
    
        'technology-amp-telecommunications' => 'Technologie et télecommunications',
    
        'business-studies-and-or-management-science' => 'Ětudes commerciales et /ou management',
    
        'engineering-and-or-technology' => 'Ingénierie et/ou technologie',
    
        'social-sciences' => 'Sciences sociales',
    
        'languages-and-philological-sciences' => 'Langues et Sciences philologiques',
    
        'communication-and-information-sciences' => 'Communication et sciences d l\'information',
    
        'humanities' => 'Sciences humaines',
    
        'education-and-or-teacher-training' => 'Formation des enseignants',
    
        'law' => 'Droits',
    
        'art-and-design' => 'Art et Design',
    
        'architecture-and-or-urban-and-regional-planning' => 'Architecture et/ou aménagement urbain',
    
        'natural-sciences' => 'Sciences naturelles',
    
        'mathematics-and-or-informatics' => 'Mathématiques et/ou informatique',
    
        'medical-sciences' => 'Sciences médicales',
    
        'geography-and-or-geology' => 'Géographie et/ou géologie',
    
        'agriculture-sciences' => 'Science agricole',
    
        'Lang_level_A1' => 'A1: élémentaire',
    
        'Lang_level_A2' => 'A2:débutant',
    
        'Lang_level_B1' => 'B1: pre-intermediaire',
    
        'Lang_level_B2' => 'B2: intermédiaire',
    
        'Lang_level_C1' => 'C1: avancé',
    
        'Lang_level_C2' => 'C2: compétent',
    
        'logo' => 'Logo',
    
        'my_profile' => 'My profile',
    
        'profile' => 'Profile',
    
        'profile_visibility' => 'Profile Visibility',
    
        'profile_visibility_visible' => 'Visible. Can be searched, viewed',
    
        'profile_visibility_hidden' => 'Hidden. Cannot be searched or viewed',
    
        'notifications' => 'Notifications',
    
        'notifications_enabled' => 'Enabled. You\'ll receive emails once a day if a student wants to get in contact with you',
    
        'notifications_disabled' => 'Disabled. You won\'t receive any emails, except for announcements about the service',
    
        'about' => 'About',
    
        'company_logo' => 'Company Logo',
    
        'social_and_web' => 'Social networks and website',
    
        'facebook_page_url' => 'Facebook page url',
    
        'twitter_page_url' => 'Twitter page url',
    
        'linkedin_page_url' => 'Linkedin page url',
    
        'web_url' => 'Website url',
    
        'what_is_talent_for_you_in_a_few_words' => 'Explain us what is talent for you in a few words',
    
        'most_valuable_skills_for_company' => 'A list of the most valuable skills for the company',
    
        'setup_alternative_contact' => 'Setup an alternative contact user that will receive all the notifications instead of the main account',
    
        'update_settings' => 'Update settings',
    
        'change_your_password' => 'Change your password',
    
        'new_password' => 'New password',
    
        'repeat_new_password' => 'Repeat new password',
    
        'save_new_password' => 'Save new password',
    
        'career_and_skills' => 'Career and Skills',
    
        'my_photo' => 'My Photo',
    
        'download_curriculum' => 'Download curriculum',
    
        'my_talent' => 'My talent',
    
        'referee_name' => 'Referee name',
    
        'referee_email' => 'Referee email',
    
        'get_your_profile_refereed' => 'Get your profile refereed',
    
        'want_to_view_all_details_of_student' => 'Do you want to view all the details of this student?',
    
        'education' => 'Education',
    
        'lives_in' => 'Lives in',
    
        'born_on' => 'Born on',
    
        'studied_in' => 'Studied in',
    
        'skilled_in' => 'Skilled in',
    
        'refereed_by' => 'Refereed by',
    
        'refereeing_pending' => 'Refereeing pending',
    
        'skills' => 'Skills',
    
        'professional' => 'Professional',
    
        'personal' => 'Personal',
    
        'legend' => 'Legend',
    
        'set_by_both_parties' => 'Set by both parties',
    
        'set_by_referee_or_student' => 'Set by either the referee or the student',
    
        'study' => 'Study|Studies',
    
        'date_not_specified' => 'Date not specified',
    
        'get_in_contact' => 'Get in contact',
    
        'want_to_show_this_company_how_talented_you_are' => 'Do you want to show this company how talented you are?',
    
        'we_are_in' => 'We are in',
    
        'we_are_looking_for_people_skilled_in' => 'We\'re looking for people skilled in',
    
        'we_think_that_talent_is' => 'We think that talent is',
    
        'not_enough_information' => 'Not enough information',
    
        'fix_the_following_errors' => 'You\'ll need to fix the following errors',
    
        'click_on_button_to_fill_required_fields' => 'Please click the following button to fill the required fields.',
    
        'institution_fix_the_following_errors' => 'You\'ll need to fix the following errors or your referees won\'t be able to validate profiles',
    
        'my_institution' => 'My Institution',
    
        'required' => 'Required',
    
        'remove_btn' => 'Remove',
    
        'student_study_institution_name' => 'Institution name',
    
        'student_study_course_studies_name' => 'Course/Studies name',
    
        'student_download_certificate' => 'Download Certificate',
    
        'student_download_grade_card' => 'Download Gradecard',
    
        'student_study_add_more' => 'add more studies',
    
        'student_training_course_name' => 'Course name',
    
        'student_training_add' => 'add a training',
    
        'student_training_add_more' => 'add more trainings',
    
        'student_language' => 'Language',
    
        'student_language_name' => 'Language name',
    
        'student_language_level' => 'Language level',
    
        'student_language_add' => 'add a language',
    
        'student_language_add_more' => 'add more languages',
    
        'student_work_experience_to' => 'Work to',
    
        'student_work_experience_from' => 'Work from',
    
        'student_work_experience_add' => 'add a work experience',
    
        'student_work_experience_add_more' => 'add more work experiences',
    
        'add_btn' => 'Add',
    
        'student_professional_skills_remove' => 'Remove professional skill',
    
        'student_professional_skills_add' => 'Add a professional skill',
    
        'profile_readiness' => 'Profile readiness',
    
        'profile_readiness_explanation' => 'Getting your profile refereed gives a third party opinion of you and helps increasing the possibilities of contact from a company',
    
        'get_a_better_refeer' => 'Get a better refeer improving your profile readiness and improve possibility of company contact',
    
        'request_is_managed_by' => 'Your request is being managed by',
    
        'cant_find_your_institution' => 'Can\'t find your institution? ask your referee and institution to join Talented Europe',
    
        'this_step_sends_an_email_to_your_referee' => 'This step sends an email to your referee with instructions on how to join Talented Europe, automatically registers him as referee once his institution joins, and adds you to the refeeral queue',
    
        'send_invitation' => 'Send invitation',
    
        'profile_validated_successfully' => 'Your profile was validated successfully',
    
        'referee_said_about_you' => 'This is what your referee said about you',
    
        'profile_validated_denied' => 'Your profile was denied',
    
        'not_enough_data_to_do_a_refeer' => 'We don\'t have enough data from you to be able to do a refeer.',
    
        'progress_account_setup' => 'Account setup',
    
        'progress_refer_your_profile' => 'Refer your profile',
    
        'progress_not_refereed' => 'Not refereed',
    
        'progress_completed' => 'Completed',
    
        'you_must_put_referee_email' => '<strong>Please note:</strong> You must put the referee email, not the one form the institution',
    
        'leave_institution' => 'Leave institution?',
    
        'do_you_want_to_leave_institution' => 'Do you want to leave the institution? this will send the pending validation requests back to it, and you won\'t be able to validate anyone until another institution invites you back',
    
        'leave_institution_button' => 'Yes! Leave this academic institution',
    
        'your_profile_is_empty' => 'Your profile is empty!',
    
        'tab_changes_not_saved' => 'Tab changes haven\'t been saved, you may lose some data',
    
        'save_changes' => 'Save changes',
    
        'continue_without_saving' => 'Continue without saving',
    
        'im_here' => 'I\'m here!',
    
        'cannot_send_more_alerts_to_this_company_today' => 'You cannot send more alerts to this company today',
    
        'tell_the_company_that_you_be_interested' => 'Tell the company that you may be interested to work for them',
    
        'alert_sent_successfully' => 'Alert sent successfully to the company',
    
        'you_have_already_sent_an_alert_to_this_company' => 'You have already sent an alert to this company',
    
        'no_matches' => 'No matches',
    
        'find_your_academic_institution' => 'Find your Academic Institution',
    
        'choose_referee' => 'Choose referee',
    
        'refer_request' => 'Refer request',
    
        'any_referee' => 'Any referee',
    
        'institution_type' => 'Institution type',
    
];
