<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'Enseignement supérieur de type court',
    
        'studies_level_6' => 'Licence 3 ou équivalent
',
    
        'studies_level_7' => 'Maîtrise ou équivalent',
    
        'studies_level_8' => 'Doctorat ou équivalent',
    
        'company_activity' => 'Domaine de l\' activité',
    
        'company_contact_person' => 'la personne à contacter',
    
        'company_contact_person_name' => 'le nom de la personne à  contacter',
    
        'company_contact_person_email' => 'Email de la personne à contacer',
    
        'company_representative' => 'le représentant légitime',
    
        'company_what_is_talent' => 'Qu\' est-ce que pour vous le talent?',
    
        'institution_certificate' => 'Certificat d \'originalité',
    
        'city' => 'Ville',
    
        'country' => 'Pays',
    
        'countries' => 'Pays',
    
        'institution_certificate_template_download' => 'Téléchargez le modèle',
    
        'fiscal_id' => 'Numéro national d\'identification',
    
        'institution_hei' => 'Institution de l\' éducation supérieure',
    
        'institution_ufa' => 'Université, Faculté',
    
        'insitution_his' => 'L\' école secondaire',
    
        'legal_representative' => 'Le représentant légal',
    
        'institution_pic' => 'PIC',
    
        'postal_code' => 'Code postal',
    
        'institution_sig_stamp_text' => 'Signature et cachet',
    
        'institution_vet' => 'La formation professionnelle et les activités professionnelles',
    
        'student_academic_info' => 'Les informations académiques',
    
        'address' => 'Adresse',
    
        'student_certificate' => 'Certificat ',
    
        'clear_btn' => 'Supprimer',
    
        'student_experience_company' => 'La société/ les sociétés',
    
        'student_completed_studies' => 'Le niveau d\' instruction',
    
        'student_course' => 'Le cours',
    
        'student_date' => 'Date',
    
        'student_birthdate' => 'Lieu de naissance',
    
        'student_study_level' => 'Niveau',
    
        'student_describe_talent' => 'Présentez en bref votre talent.',
    
        'email' => 'Mail',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'La branche d\' études',
    
        'student_study_from' => 'de',
    
        'student_study_grade_card' => 'Bulletin scolaire',
    
        'student_languages' => 'Langues',
    
        'load_btn' => 'Chargement',
    
        'input_max_characters' => 'au maximum',
    
        'name' => 'Nom',
    
        'nationality' => 'Nationalité',
    
        'student_personal_information' => 'Coordonnées',
    
        'student_personal_skills' => 'Capacités personnelles',
    
        'phone' => 'Tétéphone',
    
        'position' => 'Position',
    
        'student_professional_skills' => 'Capacités professionnelles',
    
        'student_proposed_validator' => 'Évaluateur proposé',
    
        'save_btn' => 'Sauvegarde /sauvegardez',
    
        'student_study_scanned_document' => 'Le document numérisé',
    
        'student_validator' => 'Si vous ne présentez aucun évaluateur, il vous en sera affecté un automatiquement ',
    
        'surname' => 'Nom',
    
        'student_study_to' => 'à qui',
    
        'student_training' => 'Expériences',
    
        'upload_btn' => 'Enregistrer',
    
        'student_work_experience' => 'Expériences de travail',
    
        'validator_department' => 'Section ',
    
        'password' => 'Mot de passe',
    
        'confirm_password' => 'Validez le mot de passe',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Je suis d\'accord avec les conditionsd\'utilisation',
    
        'i_agree_with' => 'Je suis d\'accord avec ',
    
        'the_terms_of_use' => 'les conditions d\'utilisation',
    
        'the_cookies' => 'la politique de cookies',
    
        'the_privacy_policy' => 'la politique de confidentialité',
    
        'the_legal_warning' => 'la notice légale',
    
        'create_account' => 'Créer un nouveau compte',
    
        'forgot_password' => 'Avez-vous oublié votre mot de passe?',
    
        'administration' => 'Administration',
    
        'architecture-amp-construction' => 'Architecture et construction',
    
        'art-amp-culture' => 'Art et culture',
    
        'banking-and-or-finance-amp-insurance' => 'Banque,finance et/ou assurance',
    
        'business-amp-consulting' => 'Activité commerciale et consultative',
    
        'communication-amp-media-amp-pr' => 'Communication et médias et PR',
    
        'consumer-goods' => 'Biens de consommation',
    
        'customer-service' => 'Service clients',
    
        'design' => 'Design',
    
        'education-amp-training' => 'Formation',
    
        'engineering' => 'Ingénierie',
    
        'hospitality-amp-tourism' => 'Tourisme',
    
        'human-resources' => 'Ressourses  humains',
    
        'it-amp-web' => 'IT et web',
    
        'legal' => 'Droits',
    
        'logistics' => 'Logistique',
    
        'manufacturing' => 'Production',
    
        'marketing-amp-advertising' => 'Marketing et publicité',
    
        'medicine-amp-pharmaceutics' => 'Médecine et pharmacie',
    
        'politics' => 'Politique',
    
        'quality-assurance-amp-safety' => 'Assurance de la qualité et de la sécurité',
    
        'real-estate' => 'Biens immobilers',
    
        'research-amp-development' => 'Recherche et développement',
    
        'retail-amp-wholesale' => 'Commerce de détail et de gros',
    
        'sales' => 'Vente',
    
        'social-work' => 'Service social',
    
        'sport-and-or-health-amp-wellness' => 'Sport et/ou santé et wellness',
    
        'technology-amp-telecommunications' => 'Technologie et télecommunications',
    
        'business-studies-and-or-management-science' => 'Ětudes commerciales et /ou management',
    
        'engineering-and-or-technology' => 'Ingénierie et/ou technologie',
    
        'social-sciences' => 'Sciences sociales',
    
        'languages-and-philological-sciences' => 'Langues et Sciences philologiques',
    
        'communication-and-information-sciences' => 'Communication et sciences d l\'information',
    
        'humanities' => 'Sciences humaines',
    
        'education-and-or-teacher-training' => 'Formation des enseignants',
    
        'law' => 'Droits',
    
        'art-and-design' => 'Art et Design',
    
        'architecture-and-or-urban-and-regional-planning' => 'Architecture et/ou aménagement urbain',
    
        'natural-sciences' => 'Sciences naturelles',
    
        'mathematics-and-or-informatics' => 'Mathématiques et/ou informatique',
    
        'medical-sciences' => 'Sciences médicales',
    
        'geography-and-or-geology' => 'Géographie et/ou géologie',
    
        'agriculture-sciences' => 'Science agricole',
    
        'Lang_level_A1' => 'A1: élémentaire',
    
        'Lang_level_A2' => 'A2:débutant',
    
        'Lang_level_B1' => 'B1: pre-intermediaire',
    
        'Lang_level_B2' => 'B2: intermédiaire',
    
        'Lang_level_C1' => 'C1: avancé',
    
        'Lang_level_C2' => 'C2: compétent',
    
        'description' => 'Description',
    
        'logo' => 'Logo',
    
        'my_profile' => 'Mon profil',
    
        'profile' => 'Profil',
    
        'profile_visibility' => 'Visibilité du profil',
    
        'profile_visibility_visible' => 'Visible. Peut être  recherché, vu',
    
        'profile_visibility_hidden' => 'Caché. Impossible de chercher,regarder',
    
        'notifications' => 'Notifications',
    
        'notifications_enabled' => 'Activé. ',
    
        'notifications_disabled' => '

Désactivé. Vous ne recevrez aucun e-mail, sauf pour les annonces sur le service',
    
        'about' => '

Sur',
    
        'company_logo' => 'Logo d\'entreprise',
    
        'social_and_web' => 'Les réseaux sociaux et site Internet',
    
        'facebook_page_url' => 'URL de la page facebook',
    
        'twitter_page_url' => 'URL de la page twitter',
    
        'linkedin_page_url' => 'Linkedin URL de la page',
    
        'web_url' => 'URL de site web',
    
        'what_is_talent_for_you_in_a_few_words' => 'expliquer brièvement ce que signifie pour vous le talent',
    
        'most_valuable_skills_for_company' => 'Une liste des compétences les plus précieuses pour votre entreprise',
    
        'setup_alternative_contact' => 'Configurez un autre utilisateur de contact qui recevra toutes les notifications au lieu du compte principal',
    
        'update_settings' => 'Mettre à jour les paramètres',
    
        'change_your_password' => 'Changer votre mot de passe',
    
        'new_password' => 'Nouveau mot de passe',
    
        'repeat_new_password' => 'Répéter le nouveau mot de passe',
    
        'save_new_password' => 'Enregistrer nouveau mot de passe',
    
        'career_and_skills' => 'Carrière et compétences',
    
        'my_photo' => 'Ma photo',
    
        'download_curriculum' => 'Télécharger le curriculum',
    
        'my_talent' => 'Mon talent',
    
        'referee_name' => 'Nom de l\'évaluateur',
    
        'referee_email' => 'Le mail de l\'évaluateur',
    
        'get_your_profile_refereed' => 'Permettez - vous d\'évaluer votre profil',
    
        'want_to_view_all_details_of_student' => 'Voulez-vous voir tous les détails de cet étudiant?',
    
        'education' => 'Education',
    
        'lives_in' => 'Résidence',
    
        'born_on' => 'Né(e) le',
    
        'studied_in' => 'Études',
    
        'skilled_in' => 'Compétences en
',
    
        'refereed_by' => 'Référé par',
    
        'refereeing_pending' => 'Évaluation est en cours de traitement',
    
        'skills' => 'Compétences en
',
    
        'professional' => 'Professionnels',
    
        'personal' => 'Personnels',
    
        'legend' => 'Légende',
    
        'set_by_both_parties' => 'Fixé par les deux parties',
    
        'set_by_referee_or_student' => 'Établi par l\' évaluateur ou l\'étudiant',
    
        'study' => 'Études',
    
        'date_not_specified' => 'Date non précisée',
    
        'get_in_contact' => 'Entrez en contact',
    
        'want_to_show_this_company_how_talented_you_are' => 'Voulez-vous montrer à cette entreprise comment talentueux vous êtes?',
    
        'we_are_in' => 'Nous sommes dans',
    
        'we_are_looking_for_people_skilled_in' => 'Nous recherchons des personnes qualifiées',
    
        'we_think_that_talent_is' => 'Nous pensons que le talent est',
    
        'not_enough_information' => 'Pas suffisamment d\'informations',
    
        'fix_the_following_errors' => 'Vous devrez corriger les erreurs suivantes',
    
        'click_on_button_to_fill_required_fields' => 'Veuillez cliquer sur le bouton suivant pour remplir les champs obligatoires.',
    
        'institution_fix_the_following_errors' => 'Vous devrez corriger les erreurs suivantes ou vos évaluateurs ne pourront pas valider les profils',
    
        'my_institution' => 'Mon établissement',
    
        'required' => 'Champs obligatoires',
    
        'remove_btn' => 'Supprimer',
    
        'student_study_institution_name' => 'Nom de l\'établissement',
    
        'student_study_course_studies_name' => 'Nom du cours / études',
    
        'student_download_certificate' => 'Télécharger le certificat',
    
        'student_download_grade_card' => 'Télécharger le tableau d évaluation',
    
        'student_study_add_more' => 'Ajouter d\'autres études',
    
        'student_training_course_name' => 'Nom du cours / études',
    
        'student_training_add' => 'Ajouter une formation/ pratique',
    
        'student_training_add_more' => 'Ajouter une formation complémentaire/pratique',
    
        'student_language' => 'Langue',
    
        'student_language_name' => 'Nom de la langue',
    
        'student_language_level' => 'Niveau linguistique',
    
        'student_language_add' => 'Ajouter une langue',
    
        'student_language_add_more' => 'Ajouter d\'autres langues',
    
        'student_work_experience_to' => 'Travail à',
    
        'student_work_experience_from' => 'Travail de',
    
        'student_work_experience_add' => 'Ajouter une expérience de travail',
    
        'student_work_experience_add_more' => 'Ajouter plus d\'expériences de travail',
    
        'add_btn' => 'Ajouter',
    
        'student_professional_skills_remove' => 'Supprimer les compétences professionnelles',
    
        'student_professional_skills_add' => 'Ajouter une compétence professionnelle',
    
        'profile_readiness' => 'Préparation du profil',
    
        'profile_readiness_explanation' => 'L\' évaluation de votre profil  donne une opinion de tiers de vous et aide à augmenter les possibilités de contact d\'une entreprise',
    
        'get_a_better_refeer' => 'Obtenez un meilleur outil pour améliorer votre profil et améliorer la possibilité de contact de l\'entreprise',
    
        'request_is_managed_by' => 'Votre demande est gérée par',
    
        'cant_find_your_institution' => 'Vous ne trouvez pas votre établissement? Demandez à votre évaluateur et à votre institution de rejoindre l\'Europe talentueuse',
    
        'this_step_sends_an_email_to_your_referee' => 'Cette étape envoie un mail a votre évaluateur avec des instructions sur la façon de rejoindre Talented Europe, l\'enregistre automatiquement comme évaluateur une fois que son institution est validée  et vous ajoute à la file d\'attente évaluateur ',
    
        'send_invitation' => 'Envoyer une invitation',
    
        'profile_validated_successfully' => 'Votre profil a été validé avec succès',
    
        'referee_said_about_you' => 'C\'est ce que votre évaluateur a dit de vous',
    
        'profile_validated_denied' => 'Votre profil a été refusé',
    
        'not_enough_data_to_do_a_refeer' => 'Nous n\'avons pas assez de données de vous pour pouvoir faire un évaluateur',
    
        'progress_account_setup' => 'Configuration du compte',
    
        'progress_refer_your_profile' => 'Évaluer le profil',
    
        'progress_not_refereed' => 'Non évalué',
    
        'progress_completed' => 'Terminé',
    
        'you_must_put_referee_email' => '<strong>S\'il vous plaît noter</strong>Vous devez mettre le courriel de l\'évaluateur, et non celui de l\'établissement',
    
        'leave_institution' => 'Quitter l\' établissement?',
    
        'do_you_want_to_leave_institution' => 'Voulez-vous quitter l\'établissement? cela envoie les demandes de validation en attente de retour  et vous ne serez pas en mesure de valider quelqu\'un jusqu\'à ce qu\'une autre institution vous invite à un retour',
    
        'leave_institution_button' => 'Oui! Quitter cette institution académique',
    
        'your_profile_is_empty' => 'Votre profil est incomplet! ',
    
        'tab_changes_not_saved' => 'Les changements n ont pas été enregistrées, vous risquez de perdre des données',
    
        'save_changes' => 'Enregistrer les modifications',
    
        'continue_without_saving' => 'Continuer sans enregistrer',
    
        'im_here' => 'Je suis là!',
    
        'cannot_send_more_alerts_to_this_company_today' => 'Aujourd\'hui vous ne pouvez pas envoyer plus alertes à cette société ',
    
        'tell_the_company_that_you_be_interested' => 'Dites à l\'entreprise que vous souhaitez travailler pour eux',
    
        'alert_sent_successfully' => 'Alerte envoyé avec succès à l\'entreprise ',
    
        'you_have_already_sent_an_alert_to_this_company' => 'Vous avez déjà envoyé une alerte à cette entreprise',
    
        'no_matches' => 'Pas de correspondance
',
    
        'find_your_academic_institution' => 'Trouvez votre établissement d\'enseignement',
    
        'choose_referee' => 'Choisir un évaluateur',
    
        'refer_request' => 'Demande de référence',
    
        'any_referee' => 'Tout évaluateur',
    
        'institution_type' => 'Type d\'établissement',
    
        'complete_the_registration' => 'Complétez l\'enregistrement,en indiquant les informations suivantes',
    
        'changes_saved_successfully' => 'Modifications enregistrées avec succès',
    
        'warning_some_fields_has_errors' => 'Attention: Certains champs ne pouvaient pas être sauvés parce qu\'il y avait des erreurs. Vérifiez chaque champ pour voir les questions.',
    
        'successfully_requested_validation_request' => 'Une demande d\'évaluation envoyé avec succès',
    
        'invitation_sent_successfully' => 'Invitation envoyée avec succès',
    
        'referee_is_part_of_institution' => 'L\'évaluateur fait partie de% s mettez- vous en contact avec lui pour demander un changement d\'institution si nécessaire',
    
        'referee_isnt_part_of_any_institution' => 'L\'évaluateur ne fait partie d\'aucune institution. Demandez-lui de vous inviter par un',
    
        'this_email_user_cannot_be_a_referee' => 'Cette adresse électronique est enregistrée auprès d\'un utilisateur qui ne peut être évaluateur',
    
        'field' => 'Champ',
    
        'your_request_was_created' => 'Votre demande a été pris en compte',
    
        'if_request_hasnt_been_completed' => 'Si votre demande n\'a pas été remplie sou %s jours, vous pourrez en créer une nouvelle',
    
        'you_havent_set_any_personal_skills' => 'Vous n\'avez pas encore renseigné de compétences personnelles. Si vous sollicitez un évaluateur, vous ne pourrez plus les renseigner.',
    
        'to_see_more_details' => 'Pour voir plus de détails, vous devez vous créer un compte',
    
        'study_institution_name' => 'Nom de l\'institution',
    
        'study_name' => 'Intitulé du diplôme?',
    
        'study_level' => 'Niveau du diplôme',
    
        'study_field' => 'Champ d\'étude',
    
        'study_certificate' => 'Certificat d\'étude',
    
        'study_gradecard' => 'Étudier gradecard',
    
        'training_name' => 'Nom de la formation',
    
        'training_date' => 'Date de formation',
    
        'training_certificate' => 'Attestation de formation',
    
        'language_certificate' => 'Certificat de langue',
    
        'professional_skills_name' => 'Compétences professionnelles',
    
        'work_experience_company' => 'Entreprise de travail',
    
        'work_experience_from' => 'Expérience de travail de',
    
        'work_experience_until' => 'Expérience professionnelle jusqu\'à
',
    
        'work_experience_position' => 'Poste d\'expérience de travail',
    
        'about_me' => 'À propos de moi',
    
        'social_networks' => 'Réseaux sociaux',
    
        'account_activation_successful' => 'Votre compte vient d\'être activé',
    
        'account_has_not_been_verified' => 'Votre compte n\'a pas été validé. S\'il vous plaît, vérifiez dans votre boite mail si un e-mail avous a été envoyé pour activer votre compte',
    
        'at' => 'à',
    
        'remove_account_button' => 'Supprimer le compte',
    
        'remove_account_confirm' => 'Etes-vous certain de vouloir supprimer votre compte? Toutes vos données seront perdues.',
    
        'remove_account_button_ok' => 'Accepter',
    
        'remove_account_button_cancel' => 'Annuler',
    
        'refereed_students' => 'Etudiants référencés',
    
        'no_refereed_students' => 'Il n\'y a pas d\'étudiants référencés',
    
        'view_contact_details' => 'Voir détails du contact',
    
        'cant_send_alerts_until_you_fill_the_profile' => 'Pour pouvoir envoyer une "alerte" aux entreprises, vous devez remplir votre profil. Veuillez évaluer les informations que vous devriez fournir.',
    
        'institution_hei_vet' => 'La formation professionnelle et les activités professionnelles',
    
        'institution_hei_his' => 'L\' école secondaire',
    
        'required_cert_warning' => 'S\'il vous plaît noter: si vous ne téléchargez pas le certificat d\'authenticité de l\'institution ne sera pas apparaître sur la liste des institutions d\'arbitrage',
    
        'invalid_credentials' => 'Ces identifiants ne correspondent pas à nos enregistrements',
    
        'alert_already_sent' => 'Alert already sent',
    
        'delete_photo' => 'Supprimer la photo',
    
        'profile_not_available' => 'Ce profil n\'est pas disponible maintenant, s\'il vous plaît essayer plus tard',
    
        'passwords_dont_match' => 'Les mots de passe ne correspondent pas',
    
        'terms_required' => 'Vous devez accepter les conditions d\'utilisation',
    
        'user_type' => 'Type d\'utilisateur',
    
        'password_confirm' => 'Confirmation mot de passe',
    
        'user_type_required' => 'Vous devez sélectionner un type d\'utilisateur',
    
        'cant_find_institution_set_mail' => 'Vous ne trouvez pas votre institution, leur envoyer une invitation',
    
        'institution_name' => 'Nom de l\'établissement',
    
        'institution_email' => 'email Établissement éducatif',
    
        'search_institutions' => 'Institutions de recherche',
    
        'select_institution' => 'Institution Select',
    
        'save_institution' => 'Enregistrer établissement',
    
        'institution_data_required' => 'Vous devez remplir le nom et e-mail de l\'institution',
    
        'select_institution_required' => 'Vous devez sélectionner l\'institution à laquelle vous appartenez',
    
        'gdpr_text' => 'Pour Talented Europe, la sécurité des informations pouvant être manipulées est pertinente. Par conséquent, nous avons mis à jour la Politique de confidentialité conformément à GDPR (Règlement général sur la protection des données ).',
    
        'gdpr_data_text' => 'Vous pouvez télécharger vos données personnelles stockées dans notre base de données à partir du lien suivant :',
    
        'gdpr_data_download' => 'Télécharger des informations personnelles',
    
        'thanks_gdpr' => 'Vos paramètres de notification ont été mis à jour. <br/> Merci!',
    
];