<?php
// Autogenerated by Translator Builder

return [
    
        'loading' => 'Chargement',
    
        'toggle' => 'Afficher / masquer',
    
        'current_search' => 'Recherche actuelle',
    
        'refereed' => 'Évaluateur',
    
        'there_are_no_matching_the_selected_filters' => 'Il n\'y a aucuns correspondants aux filtres sélectionnés actuellement',
    
        'we_found' => 'Nous avons trouvé',
    
        'we_found_matching_your_needs' => 'Nous avons trouvé X% correspondant à vos besoins',
    
        'filters' => 'Filtres',
    
];
