<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Date of request',
    
        'pending' => 'Pending',
    
        'validated' => 'Validated',
    
        'not_validated' => 'Not validated',
    
];