<?php
// Autogenerated by Translator Builder

return [
    
        'AT' => 'Rakúsko',
    
        'BE' => 'Belgicko',
    
        'BG' => 'Bulharsko',
    
        'HR' => 'Chorvátsko',
    
        'CY' => 'Cyprus',
    
        'CZ' => 'Česká republika',
    
        'DK' => 'Dánsko',
    
        'EE' => 'Estónsko',
    
        'FI' => 'Fínsko',
    
        'FR' => 'Francúzsko',
    
        'DE' => 'Nemecko',
    
        'GR' => 'Grécko',
    
        'HU' => 'Maďarsko',
    
        'IE' => 'Írsko',
    
        'IT' => 'Taliansko',
    
        'LV' => 'Lotyšsko',
    
        'LT' => 'Litva',
    
        'LU' => 'Luxembursko',
    
        'MT' => 'Malta',
    
        'NL' => 'Holandsko',
    
        'PL' => 'Poľsko',
    
        'PT' => 'Portugalsko',
    
        'RO' => 'Rumunsko',
    
        'SK' => 'Slovensko',
    
        'SI' => 'Slovinsko',
    
        'SP' => 'Španielsko',
    
        'SE' => 'Švédsko',
    
        'UK' => 'Spojené kráľovstvo',
    
        'follow_us' => 'Följ oss',
    
        'login_btn' => 'Login',
    
        'register_btn' => 'Prihláste sa',
    
        'search_info' => 'vyhľadávaj',
    
        'company_plural' => 'Spoločnosti',
    
        'institution_plural' => 'Inštitúcie',
    
        'student_plural' => 'Študenti',
    
        'company' => 'Spoločnosť|Spoločnosti',
    
        'institution' => 'Inštitúcia|Inštitúcie',
    
        'student' => 'Študent|študenti',
    
        'more_btn' => 'Zobraz viac',
    
        'home' => 'Hemsida',
    
        'blog' => 'Blogg',
    
        'cookies' => 'Information om cookies',
    
        'privacy_policy' => 'Integritetspolicy',
    
        'footer_partners' => 'Partners',
    
        'cookie_text' => 'This website uses cookies to help us give you the best experience when you visit. By using this website you consent to our use of these cookies. Find out more about how we use cookies and how to manage them by reading our <a href="/privacy-policy">cookie notice</a>',
    
        'cookie_accept' => 'Zatvoriť',
    
        'logout_btn' => 'Odhlásiť sa',
    
        'less_btn' => 'View less',
    
        'status' => 'Status',
    
        'not_enough_data_to_show_profile' => 'We don&apos;t have enough data from you to be able to show your profile.',
    
        'click_on_link_to_fill_required_fields' => 'Please click on the following link to fill the required fields.',
    
        'set_up_my_profile' => 'Set up my profile',
    
        'or' => 'or',
    
        'error' => 'Error',
    
        'success' => 'Success',
    
];