<?php
// Autogenerated by Translator Builder

return [
    
        'meta_title' => 'Talented Europe | Spája mladé talenty so zamestnávateľmi v celej Európe ',
    
        'tagline' => 'Spája<br/> <strong>mladé talenty</strong> so <strong>zamestnávateľmi</strong><br/> v celej <strong>Európe</strong>',
    
        'days' => 'dni/dní',
    
        'hours' => 'hodiny/hodín',
    
        'minutes' => 'minúty/minút',
    
        'seconds' => 'sekundy/sekúnd',
    
        'more' => 'zisti viac',
    
        'what_is_title' => 'Čo je to Talentovaná Európa?',
    
        'what_is_cta' => '<strong>Zisti/te viac!</strong> Vyžiadaj/te si brožúru!',
    
        'what_is_text_1' => 'Viete si predstaviť možnosť prijať do zamestnania najlepších študentov z ktorejkoľvek európskej krajiny? Chcete byť súčasťou sektoru elitných európskych študentov? Tisícky spoločností budú mať priamy pístup k informáciám o vás, a čím lepšie hodnotenie získate, tým väčšie možnosti máte získať skvelú prácu.',
    
        'what_is_text_2' => 'Presne to ponúka Talentovaná Európa. Výklad plný najlepších študentov v Európe. Jednoduchú myšlienku, ktorá spája zamestnávateľov a študentov. Miesto stretnutia tých najlepších .',
    
        'subscribe_title' => 'Zaregistruj sa a sleduj naše  novinky.',
    
        'subscribe_text' => 'Dostávať upozornenia o všetkých udalostiach a novinkách na Talented Europe',
    
        'subscribe_form_placeholder' => 'Zadaj/te email adresu.',
    
        'subscribe_btn_text' => 'zaregistruj sa',
    
        'subscribe_follow_text' => 'alebo nás sleduj na:',
    
        'subscribe_text_question' => 'Dostávajte novinky o Talented Europe do svojej e-mailovej schránky',
    
        'meta_description' => 'Erasmus Plus projekt, ktorý uľahčuje prepájanie vynikajúcich študentov s prácou a stážami v Európe',
    
        'coming_soon' => 'Obsah bude pridaný čoskoro',
    
        'search_placeholder' => 'Čo hľadáte',
    
        'search_where' => 'kde',
    
        'search_btn' => 'Hľadaj',
    
        'statistics_title' => 'Štatistiky',
    
        'contacts' => 'Kontakterna mellan studenter och företag',
    
        'companies_institutions' => 'Företag och institutioner',
    
        'students_title' => 'Talentovaní študenti',
    
        'no_students' => 'Inga studenter tillgängliga',
    
        'join_talented_europe_today' => 'Pridajte sa k Talentovanej  Európe už dnes!',
    
        'talented_for_students' => '<strong>For students</strong> - Talented Europe will enhance your employability with the endorsement of your tutors and put you in touch with employers across Europe for internships or first career jobs.',
    
        'talented_for_employers' => '<strong>For employers</strong> - Talented Europe will link you with talented young students across Europe and help you find the right person who can contribute to your organisation’s success with the special talents and skills that you are looking for.',
    
];
