<?php
// Autogenerated by Translator Builder

return [
    
        'looking_for' => 'Hľadám',
    
        'profile' => 'Profil',
    
        'alerts' => 'Upozornenia',
    
        'settings' => 'Nastavenia',
    
];
