<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'krátkodobé terciálne vzdelanie ',
    
        'studies_level_6' => 'bakalár alebo ekvivalent',
    
        'studies_level_7' => 'magister alebo ekvivalent',
    
        'studies_level_8' => 'doktor/át alebo ekvivalent',
    
        'company_activity' => 'oblasť aktivity',
    
        'company_contact_person' => 'Kontaktná osoba',
    
        'company_representative' => 'Zákonný zástupca (oprávnená osoba)',
    
        'company_what_is_talent' => 'Čo je pre vás talent?',
    
        'institution_certificate' => 'certifikát originality',
    
        'city' => 'Mesto',
    
        'country' => 'Krajina',
    
        'institution_certificate_template_download' => 'Stiahnite si šablónu',
    
        'fiscal_id' => 'IČO',
    
        'institution_hei' => 'vyššia vzdelávacia inštitúcia',
    
        'institution_ufa' => 'Univerzita, fakulta',
    
        'insitution_his' => 'Stredná škola',
    
        'legal_representative' => 'Zákonný zástupca (oprávnená osoba)',
    
        'institution_pic' => 'foto',
    
        'postal_code' => 'PSČ',
    
        'institution_sig_stamp_text' => 'Podpis a pečiatka',
    
        'institution_vet' => 'odborné vzdelanie a prax',
    
        'student_academic_info' => 'akademické informácie',
    
        'address' => 'Adresa',
    
        'student_certificate' => 'Certifikát',
    
        'clear_btn' => 'vymazať',
    
        'student_experience_company' => 'Spoločnosť',
    
        'student_completed_studies' => 'Ukončené vzdelanie',
    
        'student_course' => 'Kurz',
    
        'student_date' => 'Dátum',
    
        'student_birthdate' => 'Dátum narodenia',
    
        'student_study_level' => 'Úroveň',
    
        'student_describe_talent' => 'V krátkosti opíšte svoj talent',
    
        'email' => 'E-mail',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Študijný odbor',
    
        'student_study_from' => 'Z',
    
        'student_study_grade_card' => 'Vysvedčenie?',
    
        'student_languages' => 'Jazyky',
    
        'load_btn' => 'Načítaj(te)',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Meno',
    
        'nationality' => 'Národnosť',
    
        'student_personal_information' => 'Osobné informácie',
    
        'student_personal_skills' => 'Osobné zručnosti',
    
        'phone' => 'Telefón',
    
        'position' => 'Pozícia',
    
        'student_professional_skills' => 'Profesijné zručnosti',
    
        'student_proposed_validator' => 'Navrhovaný hodnotiteľ',
    
        'save_btn' => 'Ulož(te)',
    
        'student_study_scanned_document' => 'Zoskenovaný dokument',
    
        'student_validator' => 'Ak neuvediete hodnotiteľa, bude vám pridelený automaticky',
    
        'surname' => 'Priezvisko',
    
        'student_study_to' => 'Komu',
    
        'student_training' => 'prax',
    
        'upload_btn' => 'Nahraj(te)',
    
        'student_work_experience' => 'Pracovné skúsenosti',
    
        'validator_department' => 'Oddelenie/Katedra',
    
        'password' => 'Heslo',
    
        'confirm_password' => 'Potvrď(te) heslo',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Súhlasím s podmienkami',
    
        'i_agree_with' => 'I agree with',
    
        'the_terms_of_use' => 'the terms of use',
    
        'create_account' => 'Vytvoriť nový účet',
    
        'forgot_password' => 'Zabudli ste heslo?',
    
        'administration' => 'Administratíva',
    
        'architecture-amp-construction' => 'Architektúra a stavebníctvo',
    
        'art-amp-culture' => 'Umenie a kultúra',
    
        'banking-and-or-finance-amp-insurance' => 'Bankovníctvo a/alebo Financie a Poisťovníctvo',
    
        'business-amp-consulting' => '
Obchodná a poradenská činnosť',
    
        'communication-amp-media-amp-pr' => 'Komunikácia a médiá a PR',
    
        'consumer-goods' => 'Spotrebný tovar',
    
        'customer-service' => 'Zákaznícky servis',
    
        'design' => 'Dizajn',
    
        'education-amp-training' => 'Vzdelávanie',
    
        'engineering' => 'Inžinierstvo',
    
        'hospitality-amp-tourism' => 'Cestovný ruch a turizmus',
    
        'human-resources' => 'Ľudské zdroje',
    
        'it-amp-web' => 'IT a web',
    
        'legal' => 'Právo',
    
        'logistics' => 'Logistika',
    
        'manufacturing' => 'Výroba',
    
        'marketing-amp-advertising' => 'Marketing a reklama',
    
        'medicine-amp-pharmaceutics' => 'Medicína a farmácia',
    
        'politics' => 'Politika',
    
        'quality-assurance-amp-safety' => 'Zabezpečenie kvality a bezpečnosti',
    
        'real-estate' => 'Nehnuteľnosti',
    
        'research-amp-development' => 'Výskum a  vývoj',
    
        'retail-amp-wholesale' => 'Maloobchod a veľkoobchod',
    
        'sales' => 'Predaj',
    
        'social-work' => 'Sociálna práca',
    
        'sport-and-or-health-amp-wellness' => 'Šport a/alebo zdravie a wellness',
    
        'technology-amp-telecommunications' => 'Technológie a telekomunikácie',
    
        'business-studies-and-or-management-science' => 'Obchodné štúdia a/alebo manažment ',
    
        'engineering-and-or-technology' => 'Inžinierstvo a/alebo technológie',
    
        'social-sciences' => 'Spoločenské vedy',
    
        'languages-and-philological-sciences' => 'Jazyky a filologické vedy',
    
        'communication-and-information-sciences' => 'Komunikácia a informačné vedy ',
    
        'humanities' => 'Humanitné vedy',
    
        'education-and-or-teacher-training' => 'Vzdelávanie a /alebo príprava učiteľov',
    
        'law' => 'Právo',
    
        'art-and-design' => 'Umenie a dizajn',
    
        'architecture-and-or-urban-and-regional-planning' => 'Architektúra a/alebo územné a regionálne plánovanie',
    
        'natural-sciences' => 'Prírodné vedy',
    
        'mathematics-and-or-informatics' => 'Matematika a/alebo informatika',
    
        'medical-sciences' => 'Lekárske vedy',
    
        'geography-and-or-geology' => 'Geografia a/alebo geológia',
    
        'agriculture-sciences' => 'Poľnohospodárske vedy',
    
        'Lang_level_A1' => 'A1: úplný začiatočník',
    
        'Lang_level_A2' => 'A2: začiatočník',
    
        'Lang_level_B1' => 'B1: mierne pokročilý',
    
        'Lang_level_B2' => 'B2: stredne pokročilý',
    
        'Lang_level_C1' => 'C1: pokročilý',
    
        'Lang_level_C2' => 'C2: expert',
    
        'logo' => 'Logo',
    
        'my_profile' => 'My profile',
    
        'profile' => 'Profile',
    
        'profile_visibility' => 'Profile Visibility',
    
        'profile_visibility_visible' => 'Visible. Can be searched, viewed',
    
        'profile_visibility_hidden' => 'Hidden. Cannot be searched or viewed',
    
        'notifications' => 'Notifications',
    
        'notifications_enabled' => 'Enabled. You&apos;ll receive emails once a day if a student wants to get in contact with you',
    
        'notifications_disabled' => 'Disabled. You won&apos;t receive any emails, except for announcements about the service',
    
        'about' => 'About',
    
        'company_logo' => 'Company Logo',
    
        'social_and_web' => 'Social networks and website',
    
        'facebook_page_url' => 'Facebook page url',
    
        'twitter_page_url' => 'Twitter page url',
    
        'linkedin_page_url' => 'Linkedin page url',
    
        'web_url' => 'Website url',
    
        'what_is_talent_for_you_in_a_few_words' => 'Explain us what is talent for you in a few words',
    
        'most_valuable_skills_for_company' => 'A list of the most valuable skills for the company',
    
        'setup_alternative_contact' => 'Setup an alternative contact user that will receive all the notifications instead of the main account',
    
        'update_settings' => 'Update settings',
    
        'change_your_password' => 'Change your password',
    
        'new_password' => 'New password',
    
        'repeat_new_password' => 'Repeat new password',
    
        'save_new_password' => 'Save new password',
    
        'career_and_skills' => 'Career and Skills',
    
        'my_photo' => 'My Photo',
    
        'download_curriculum' => 'Download curriculum',
    
        'my_talent' => 'My talent',
    
        'referee_name' => 'Referee name',
    
        'referee_email' => 'Referee email',
    
        'get_your_profile_refereed' => 'Get your profile refereed',
    
        'want_to_view_all_details_of_student' => 'Do you want to view all the details of this student?',
    
        'education' => 'Education',
    
        'lives_in' => 'Lives in',
    
        'born_on' => 'Born on',
    
        'refereed_by' => 'Refereed by',
    
        'refereeing_pending' => 'Refereeing pending',
    
        'skills' => 'Skills',
    
        'professional' => 'Professional',
    
        'personal' => 'Personal',
    
        'legend' => 'Legend',
    
        'set_by_both_parties' => 'Set by both parties',
    
        'set_by_referee_or_student' => 'Set by either the referee or the student',
    
        'study' => 'Study|Studies',
    
        'date_not_specified' => 'Date not specified',
    
        'get_in_contact' => 'Get in contact',
    
        'want_to_show_this_company_how_talented_you_are' => 'Do you want to show this company how talented you are?',
    
        'we_are_in' => 'We are in',
    
        'we_are_looking_for_people_skilled_in' => 'We&apos;re looking for people skilled in',
    
        'we_think_that_talent_is' => 'We think that talent is',
    
        'not_enough_information' => 'Not enough information',
    
        'fix_the_following_errors' => 'You&apos;ll need to fix the following errors',
    
        'click_on_button_to_fill_required_fields' => 'Please click the following button to fill the required fields.',
    
        'institution_fix_the_following_errors' => 'You&apos;ll need to fix the following errors or your referees won&apos;t be able to validate profiles',
    
        'my_institution' => 'My Institution',
    
        'required' => 'Required',
    
        'remove_btn' => 'Remove',
    
        'student_study_institution_name' => 'Institution name',
    
        'student_study_course_studies_name' => 'Course/Studies name',
    
        'student_download_certificate' => 'Download Certificate',
    
        'student_download_grade_card' => 'Download Gradecard',
    
        'student_study_add_more' => 'add more studies',
    
        'student_training_course_name' => 'Course name',
    
        'student_training_add' => 'add a training',
    
        'student_training_add_more' => 'add more trainings',
    
        'student_language' => 'Language',
    
        'student_language_name' => 'Language name',
    
        'student_language_level' => 'Language level',
    
        'student_language_add' => 'add a language',
    
        'student_language_add_more' => 'add more languages',
    
        'student_work_experience_to' => 'Work to',
    
        'student_work_experience_from' => 'Work from',
    
        'student_work_experience_add' => 'add a work experience',
    
        'student_work_experience_add_more' => 'add more work experiences',
    
        'add_btn' => 'Add',
    
        'student_professional_skills_remove' => 'Remove professional skill',
    
        'student_professional_skills_add' => 'Add a professional skill',
    
        'profile_readiness' => 'Profile readiness',
    
        'profile_readiness_explanation' => 'Getting your profile refereed gives a third party opinion of you and helps increasing the possibilities of contact from a company',
    
        'get_a_better_refeer' => 'Get a better refeer improving your profile readiness and improve possibility of company contact',
    
        'request_is_managed_by' => 'Your request is being managed by',
    
        'cant_find_your_institution' => 'Can&apos;t find your institution? ask your referee and institution to join Talented Europe',
    
        'this_step_sends_an_email_to_your_referee' => 'This step sends an email to your referee with instructions on how to join Talented Europe, automatically registers him as referee once his institution joins, and adds you to the refeeral queue',
    
        'send_invitation' => 'Send invitation',
    
        'profile_validated_successfully' => 'Your profile was validated successfully',
    
        'referee_said_about_you' => 'This is what your referee said about you',
    
        'profile_validated_denied' => 'Your profile was denied',
    
        'not_enough_data_to_do_a_refeer' => 'We don&apos;t have enough data from you to be able to do a refeer.',
    
        'progress_account_setup' => 'Account setup',
    
        'progress_refer_your_profile' => 'Refer your profile',
    
        'progress_not_refereed' => 'Not refereed',
    
        'progress_completed' => 'Completed',
    
        'you_must_put_referee_email' => '<strong>Please note:</strong> You must put the referee email, not the one form the institution',
    
];