<?php
// Autogenerated by Translator Builder

return [
    
        'delete_photo' => 'zmazať fotografie',
    
        'profile_not_available' => 'Tento profil nie je k dispozícii, skúste to prosím neskôr',
    
        'passwords_dont_match' => 'Heslá sa nezhodujú',
    
        'terms_required' => 'Musíte akceptovať podmienky používania',
    
        'user_type' => 'typ užívateľa',
    
        'password_confirm' => 'potvrdenie hesla',
    
];