<?php
// Autogenerated by Translator Builder

return [
    
        'thank_you_for_signing_up' => 'Ďakujeme za vašu registráciu!',
    
        'you_will_receive_an_email' => 'O nikeľoko minút obdržíte mail s inštrukciami pre potvrdenie vášho účtu.',
    
        'go_back_to_home' => 'Návrat na domovskú stránku',
    
        'search_students' => 'Vyhľdávaj študentov',
    
        'search_companies' => 'Vyhľadávaj spoločnosti',
    
        'register_as_validator' => 'Zaregistruj sa ako hodnotiteľ',
    
        'there_have_been_some_errors' => 'Vyskytli sa nejaké chyby',
    
        'i_am_a' => 'Som',
    
        'all_fields_are_required' => 'Potrebné vyplniť všetky políčka',
    
        'confirmation_email_may_take_few_minutes' => 'Your confirmation email may take a few minutes to arrive, make sure you also check out your spam folder',
    
        'registration_complete_successfully' => 'Registration complete successfully you may log in now.',
    
        'register_success' => 'Register success',
    
        'register' => 'Registrujte sa',
    
        'invited_by' => 'Pozval vás...',
    
];