<?php
// Autogenerated by Translator Builder

return [
    
        'reset_password' => 'Obnov heslo',
    
        'send_password_reset' => 'Pošli link na obnovenie hesla',
    
        'set_password' => 'Nastaviť heslo',
    
];