<?php
// Autogenerated by Translator Builder

return [
    
        'loading' => 'Načítavanie',
    
        'toggle' => 'Ukázať/Skryť',
    
        'current_search' => 'Aktuálne vyhľadávanie ',
    
        'refereed' => 'Hodnotil',
    
        'there_are_no_matching_the_selected_filters' => 'Nie sú žiadni/žiadne',
    
        'we_found' => 'spĺňa vaše potreby',
    
        'we_found_matching_your_needs' => 'Našli sme...',
    
        'filters' => 'Filtre',
    
];
