<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Dátum požiadavky',
    
        'pending' => 'Čakajúci',
    
        'validated' => 'Ohodnotený',
    
        'not_validated' => 'Neohodnotený',
    
        'no_students' => 'Žiadni študenti',
    
        'confirm_validation' => 'Potvrďte hodnotenie',
    
        'are_you_sure_you_want_to_finish_refereeing' => 'Skutočne chcete ukončiť hodnotenie tohto študenta?',
    
        'reason' => 'Dôvod',
    
        'criteria' => 'Študent nespĺňa kritériá.',
    
        'nostudent' => 'Študent nenavštevoval túto školu/inštitúciu.  ',
    
];
