<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Dátum požiadavky',
    
        'pending' => 'Čakajúci',
    
        'validated' => 'Ohodnotený',
    
        'not_validated' => 'Neohodnotený',
    
];