<?php
// Autogenerated by Translator Builder

return [
    
        'my_students' => 'Moji študenti',
    
        'enable' => 'Povoľ',
    
        'disable' => 'Nepovoľ/Zruš',
    
        'add_new' => 'Pridaj nového hodnotiteľa',
    
        'send_invitation' => 'Pošli pozvanie hodnotiteľovi',
    
        'validating' => 'V proceae hodnotenia.',
    
        'student_already_validated' => 'Tento študent už bol validovaný.',
    
        'jump_to_results' => 'Prejdi k výsledkom.',
    
        'you_are_validating_following_student' => 'Hodnotíte nasledujúceho študenta.',
    
        'jump_to_validation' => 'Prejdi k hodnoteniu.',
    
        'student_validation' => 'Hodnotenie študenta.',
    
        'valid' => 'Validovaný',
    
        'student_passed_validation_successfully' => 'Študent bol úspešne hodnotený.',
    
        'your_comments' => 'Váš komentár.',
    
        'your_chosen_skills' => 'Vaše zvolené zručnosti.',
    
        'invalid' => 'Neplatný.',
    
        'student_didnt_meet_criteria' => 'Študent nespĺňa kritériá.',
    
        'make_sure_you_have_reviewed_student' => 'Uistite sa prosím, že ste profil študenta  dôkladne vyplnili pred jeho validáciou.',
    
        'this_student_is' => 'Tento študent je...',
    
        'finish_validation' => 'Ukončiť hodnotenie.',
    
        'give_us_explanation_of_student_is_not_valid' => 'Prosíme vás aby ste nám vysvetlili, prečo je študentov profil neplatný.',
    
        'note_if_validation_is_passed_as_no_student' => 'Ak je validácia ukončená ako "žiaden študent", študentov profil bude môcť byť znovu validovaný.',
    
        'user_hasnt_complete_filling_its_profile' => 'Neukončený profil. Ak je profil nekompletný, nemožno hodnotiť žiadneho študenta.',
    
        'manage_validators' => 'Správa hodnotiteľov.',
    
        'validators' => 'Hodnotitelia',
    
        'invites_pending' => 'Čakajúce pozvania',
    
        'date_sent' => 'Zaslané údaje',
    
        'note_invites_are_only_valid_14_days' => 'Pozvania sú platné 14 dní po ich zaslaní, potom budú zo zoznamu odstránené.',
    
        'cancel' => 'Zrušiť',
    
        'cannot_change_institution' => 'Zmena inštitúcie nemožná',
    
        'invitation_is_not_valid_or_you_accepted_it' => 'Vaše pozvanie je neplatné alebo už akceptované',
    
        'changed_institution_successfully' => 'Inštitúcia úspešne zmenená',
    
        'youll_receive_notifications_from' => 'Odteraz budete dostávať notifikácie o validácii od...',
    
        'cannot_complete_invitation' => 'Nemožno ukončiť pozvanie',
    
        'no_alerts_found' => 'Nenašli sme žiadne upozornenia',
    
        'study_level' => 'Úroveň štúdia',
    
        'when_it_was_sent' => 'Kedy to bolo zaslané?',
    
        'no_referees' => 'No referees',
    
        'remove_referee' => 'Remove referee',
    
        'do_you_want_to_remove_referee' => 'Do you want to remove %s from your institution?',
    
        'remove' => 'Remove',
    
        'removing' => 'Removing',
    
];
