<?php
// Autogenerated by Translator Builder

return [
    
        'accountActivated_subject_1' => 'Aktiviere dein Konto',
    
        'accountActivated_line_2' => 'Vielen Dank für die Registrierung bei Talented Europe',
    
        'accountActivated_line_3' => 'Bitte bestätige deine E-Mail-Adresse. Klicke auf den folgenden Link.',
    
        'accountActivated_action_4' => 'Mein Konto bestätigen.',
    
        'accountActivated_line_5' => 'Danke, dass Sie unsere App nutzen.',
    
        'changeInstitution_subject_1' => '%s hat Sie als Gutachter in Talented Europe eingeladen',
    
        'changeInstitution_line_2' => '%s hat Sie als Gutachter in Talented Europe eingeladen',
    
        'changeInstitution_line_3' => 'Da Sie bereits Gutachter bei Talented Europe sind, müssen Sie diese Änderung bestätigen.',
    
        'changeInstitution_action_4' => 'Änderung bestätigen.',
    
        'changeInstitution_line_5' => 'Danke, dass Sie unsere App nutzen.',
    
        'institutionRemoved.subject_1' => '%s hat dich aus Ihrer Institution bei Talented Europe ausgeschieden.',
    
        'institutionRemoved.line_2' => '%s hat dich aus Ihrer Institution bei Talented Europe ausgeschieden. Wenn es ein Versehen war, tritt mit ihm in Kontakt, um die Situation rückgängig zu machen.',
    
        'institutionRemoved.line_3' => 'Danke, dass Sie unsere App nutzen.',
    
        'inviteCreated_subject_1' => '%s hat Sie als Gutachter in Talented Europe eingeladen.',
    
        'inviteCreated_line_2' => '%s hat Sie als Gutachter in Talented Europe eingeladen.',
    
        'inviteCreated_line_3' => 'Um Ihr Konto zu erstellen, klicken Sie den folgenden Link an.',
    
        'inviteCreated_action_4' => 'Mein Konto erstellen.',
    
        'inviteCreated_line_5' => 'Danke, dass Sie unsere App nutzen.',
    
        'validatorRequested_subject_1' => '%s hat Sie als Gutachter in Talented Europe eingeladen.',
    
        'validatorRequested_line_2' => 'Hallo %s',
    
        'validatorRequested_line_3' => '%s hat Sie als Gutachter in Talented Europe eingeladen.',
    
        'validatorRequested_line_4' => 'Leiten Sie diesen Link an die Instittion weiter, für die Sie arbeiten, damit sich die Institution registrieren kann.',
    
        'validatorRequested_line_5' => 'Sobald Ihre Institution registriert ist, werden Sie automatisch in diese Institution eingeladen.',
    
        'validatorRequested_action_6' => 'Das Konto für die Institution erstellen.',
    
        'validatorRequested_line_7' => 'Danke, dass Sie unsere App nutzen.',
    
        'newAlerts_subject_1' => 'Neue Nachrichten von Studenten.',
    
        'newAlerts_line_2' => 'Wir geben Ihnen Bescheid, dass manche Studenten Ihnen auf der Platform eine Nahricht gesendet haben.',
    
        'newAlerts_line_3' => 'Zur Anmeldung klicken Sie das folgende Fenster an und sehen Sie Ihr Informationspanel durch.',
    
        'validationsPending_subject_1' => 'Wartende Bewerter bei Talented Europe ',
    
        'validationsPending_line_2' => 'Wir geben Ihnen Bescheid, dass sich auf der Platform mehrere wartende Bewerter befinden.',
    
        'validationsPending_line_3' => 'Zur Anmeldung klicken Sie das folgende Fenster an und sehen Sie Ihr Informationspanel durch',
    
];
