<?php
// Autogenerated by Translator Builder

return [
    
        'accountActivated_subject_1' => '',
    
        'accountActivated_line_2' => '',
    
        'accountActivated_line_3' => '',
    
        'accountActivated_action_4' => '',
    
        'accountActivated_line_5' => '',
    
        'changeInstitution_subject_1' => '',
    
        'changeInstitution_line_2' => '',
    
        'changeInstitution_line_3' => '',
    
        'changeInstitution_action_4' => '',
    
        'changeInstitution_line_5' => '',
    
        'institutionRemoved.subject_1' => '',
    
        'institutionRemoved.line_2' => '',
    
        'institutionRemoved.line_3' => '',
    
        'inviteCreated_subject_1' => '',
    
        'inviteCreated_line_2' => '',
    
        'inviteCreated_line_3' => '',
    
        'inviteCreated_action_4' => '',
    
        'inviteCreated_line_5' => '',
    
        'validatorRequested_subject_1' => '',
    
        'validatorRequested_line_2' => '',
    
        'validatorRequested_line_3' => '',
    
        'validatorRequested_line_4' => '',
    
        'validatorRequested_line_5' => '',
    
        'validatorRequested_action_6' => '',
    
        'validatorRequested_line_7' => '',
    
];