<?php
// Autogenerated by Translator Builder

return [
    
        'not_allowed' => 'Nich erlaubt',
    
        'not_allowed_to_do_this_action' => 'Dieser vorgang ist erlaubt',
    
        'can_try_searching_for' => 'Suchen Sie...',
    
        'page_not_found' => 'Seite nicht gefunden',
    
        'we_didnt_find_the_page' => 'Haben Sie die Seite, die Sie suchen, nicht gefunden.',
    
        'internal_server_error' => 'Fehler - interner Server',
    
        'an_error_happened' => 'Es ist ein Fehler aufgetreten, die Administratoren wurde benachrichtigt. Der Fehler wird im kürzem behoben, versuchen Sie es später.',
    
        'meanwhile_can_searching_for' => 'Sie können das Suchen probieren...',
    
        'be_right_back' => 'Wir melden uns gleich.',
    
        'not_found' => 'Nicht gefunden.',
    
        'unauthorized_action' => 'Unerlaubter Schritt',
    
];