<?php
// Autogenerated by Translator Builder

return [
    
        'BE' => 'Belgien',
    
        'BG' => 'Bulgarien',
    
        'HR' => 'Kroatien',
    
        'CY' => 'Zypern',
    
        'CZ' => 'Tschechische Republik',
    
        'DK' => 'Dänemark',
    
        'EE' => 'Estland',
    
        'FI' => 'Finnland',
    
        'FR' => 'Frankreich',
    
        'DE' => 'Deutschland',
    
        'GR' => 'Griechenland',
    
        'HU' => 'Ungarn',
    
        'IE' => 'Irland',
    
        'IT' => 'Italien',
    
        'LV' => 'Lettland',
    
        'LT' => 'Litauen',
    
        'LU' => 'Luxemburg',
    
        'MT' => 'Malta',
    
        'NL' => 'Niederlande',
    
        'PL' => 'Polen',
    
        'PT' => 'Portugal',
    
        'RO' => 'Rumänien',
    
        'SK' => 'Slowakei',
    
        'SI' => 'Slowenien',
    
        'SP' => 'Spanien',
    
        'SE' => 'Schweden',
    
        'UK' => 'Vereinigtes Königreich',
    
        'login_btn' => 'Anmelden',
    
        'register_btn' => 'Bitte anmelden',
    
        'search_info' => 'suchen',
    
        'company' => 'Unternehmen',
    
        'institution' => 'Institution',
    
        'student' => 'Student/Studenten',
    
        'more_btn' => 'mehr erfahren',
    
        'cookie_text' => '',
    
        'cookie_accept' => 'Schliessen',
    
        'logout_btn' => 'Ausloggen',
    
];