<?php
// Autogenerated by Translator Builder

return [
    
        'meta_title' => 'Talented Europe | Verbindet junge Talente mit Arbeitgebern in ganz Europa.',
    
        'tagline' => 'Verbindet<br/> <strong>junge Talente</strong> mit <strong>Arbeitgebern</strong><br/> in ganz <strong>Europa</strong>',
    
        'days' => 'Tage',
    
        'hours' => 'Stunden',
    
        'minutes' => 'Minuten',
    
        'seconds' => 'Sekunden',
    
        'more' => 'Erfahre mehr',
    
        'what_is_title' => 'Was ist talentiertes Europa?',
    
        'what_is_cta' => '<strong>Erfahre mehr!</strong> Eine Broschühre anfordern!',
    
        'what_is_text_1' => 'Können Sie sich vorstellen, die besten Studenten aus einem beliebigen europäische Land einzustellen? Möchten Sie ein Teil der europäischen Top-Studenten sein? Tausende Unternehmen gewinnen einen direkten Zugang zu Informationen über Sie und je besser Ihre Bewertung, desto mehr Möglichkeiten haben Sie, eine bessere Arbeit zu finden.',
    
        'what_is_text_2' => 'Genau das bietet Talentiertes Europa an. Ein Ausstellfenster voller besten Studenten in Europa. Eine einfache Idee, die Arbeitgeber mit Studenten verbindet. Der Treffpunkt für die Besten.',
    
        'subscribe_title' => 'Registriere dich und verfolge unsere Neuigkeiten.',
    
        'subscribe_text' => 'Alle Benachrichtigungen über die Ereignisse und Neuigkeiten auf Talented Europe. ',
    
        'subscribe_form_placeholder' => 'Bitte E-mailadresse angeben.',
    
        'subscribe_btn_text' => 'Registrieren',
    
        'subscribe_follow_text' => 'Bitte folgen auf:',
    
        'subscribe_text_question' => 'Neuigkeiten über Talented Europe per E-Mail bekommen',
    
        'meta_description' => 'Erasmus plus Projekt, das die Verbindung von exzellenten Studenten mit der Arbeit und Praktika in Europa verbindet.',
    
        'coming_soon' => 'Inhalt in Bearbeitung',
    
        'search_placeholder' => 'Was suchen Sie?',
    
        'search_where' => 'Wo',
    
        'search_btn' => 'suchen',
    
        'statistics_title' => 'Statistik',
    
        'contacts' => 'Kontakte zwischen Studenten und Unternehmen',
    
        'companies_institutions' => 'Unternehmen und Institutionen',
    
        'students_title' => 'talentierte Studenten',
    
        'no_students' => 'Keine Studenten zur Verfügung',
    
        'join_talented_europe_today' => 'Join Talented Europe today!',
    
        'talented_for_students' => '<strong>For students</strong> - Talented Europe will enhance your employability with the endorsement of your tutors and put you in touch with employers across Europe for internships or first career jobs.',
    
        'talented_for_employers' => '<strong>For employers</strong> - Talented Europe will link you with talented young students across Europe and help you find the right person who can contribute to your organisation’s success with the special talents and skills that you are looking for.',
    
];