<?php
// Autogenerated by Translator Builder

return [
    
        'remember_me' => 'Merken',
    
        'sign_in' => 'Anmelden',
    
        'login_title' => 'Benutzername',
    
        'login_btn' => 'Anmelden',
    
];
