<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => '',
    
        'studies_level_6' => '',
    
        'studies_level_7' => '',
    
        'studies_level_8' => '',
    
];