<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'kurzfristige tertiäre Ausbildung',
    
        'studies_level_6' => 'Bachelor oder Äquivalent',
    
        'studies_level_7' => 'Magister oder Äquivalent',
    
        'studies_level_8' => 'Doktor oder Äquivalent',
    
        'company_activity' => 'Wirtschaftssektor',
    
        'company_contact_person' => 'Kontaktperson',
    
        'company_contact_person_name' => 'Name der Kontaktperson',
    
        'company_contact_person_email' => 'E-Mail der Kontaktperson',
    
        'company_representative' => 'Erziehungsberechtigte',
    
        'company_what_is_talent' => 'Was verstehen Sie unter Talent?',
    
        'institution_certificate' => 'Originalitätsbecheinigung',
    
        'city' => 'Stadt',
    
        'country' => 'Land',
    
        'countries' => 'Länder',
    
        'institution_certificate_template_download' => 'Muster herunterladen',
    
        'fiscal_id' => 'Steueridentifikationsnummer',
    
        'institution_hei' => 'Höhere Bildungsinstitution',
    
        'institution_ufa' => 'Universität, Fakultät',
    
        'insitution_his' => 'Mittelschule',
    
        'legal_representative' => 'Rechtliche Vertretung (Verantwortliche Person)',
    
        'institution_pic' => 'PIC',
    
        'postal_code' => 'PLZ',
    
        'institution_sig_stamp_text' => 'Unterschrift und Stempel',
    
        'institution_vet' => 'Fachausbildung und Praktikum',
    
        'student_academic_info' => 'Informationen über Ausbildung',
    
        'address' => 'Anschrift',
    
        'student_certificate' => 'Zertifikat',
    
        'clear_btn' => 'löschen',
    
        'student_experience_company' => 'Unternehmen',
    
        'student_completed_studies' => 'abgeschlossene Ausbildung',
    
        'student_course' => 'Kurs',
    
        'student_date' => 'Datum',
    
        'student_birthdate' => 'Geburtsdatum',
    
        'student_study_level' => 'Niveau',
    
        'student_describe_talent' => 'Beschreibe kurz dein Talent',
    
        'email' => 'E-mail',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Studienrichtung',
    
        'student_study_from' => 'aus',
    
        'student_study_grade_card' => 'Zeugnis',
    
        'student_languages' => 'Sprachen',
    
        'load_btn' => 'Laden',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Name',
    
        'nationality' => 'Nationalität',
    
        'student_personal_information' => 'Persönliche Angaben',
    
        'student_personal_skills' => 'Persönliche Fähigkeiten',
    
        'phone' => 'Telefon',
    
        'position' => 'Position',
    
        'student_professional_skills' => 'Professionelle  Fähigkeiten',
    
        'student_proposed_validator' => 'Vorgeschlagener Gutachter',
    
        'save_btn' => 'Speichern',
    
        'student_study_scanned_document' => 'Gescanntes Dokument',
    
        'student_validator' => 'Falls Sie den Gutachter nicht angeben, wird Ihnen ein Gutachter automatisch zugeteilt',
    
        'surname' => 'Nachname',
    
        'student_study_to' => 'Wem',
    
        'student_training' => 'Praktikum',
    
        'upload_btn' => 'Hochladen',
    
        'student_work_experience' => 'Arbeitserfahrungen',
    
        'validator_department' => 'Abteilung',
    
        'password' => 'Passwort',
    
        'confirm_password' => 'Passwort bestätigen',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Ich bin mit den Nutzungsbedingungen einverstanden',
    
        'i_agree_with' => 'Ich bin einverstanden',
    
        'the_terms_of_use' => 'nutzungsbedingungen',
    
        'the_cookies' => 'cookies',
    
        'the_privacy_policy' => 'Datenschutz-Bestimmungen',
    
        'the_legal_warning' => 'the legal warning',
    
        'create_account' => 'Ein Konto erstellen',
    
        'forgot_password' => 'Passwort vergessen?',
    
        'administration' => 'Administration',
    
        'architecture-amp-construction' => 'Architektur und Bauwesen',
    
        'art-amp-culture' => 'Kunst und Kultur',
    
        'banking-and-or-finance-amp-insurance' => 'Bankwesen, Finanzen und Versicherungswesen',
    
        'business-amp-consulting' => 'Handels- und Beratungstätigkeit',
    
        'communication-amp-media-amp-pr' => 'Kommunikation, Medien und PR',
    
        'consumer-goods' => 'Verbrauchsware',
    
        'customer-service' => 'Kundenservice',
    
        'design' => 'Design',
    
        'education-amp-training' => 'Bildung und Unterrichten',
    
        'engineering' => 'Ingenieurwesen',
    
        'hospitality-amp-tourism' => 'Hotellerie und Tourismus',
    
        'human-resources' => 'Human Resources',
    
        'it-amp-web' => 'IT und Web',
    
        'legal' => 'Recht',
    
        'logistics' => 'Logistik',
    
        'manufacturing' => 'Produktion',
    
        'marketing-amp-advertising' => 'Marketing und Werbung',
    
        'medicine-amp-pharmaceutics' => 'Medizin und Pharmazie',
    
        'politics' => 'Politik',
    
        'quality-assurance-amp-safety' => 'Qualitäts- und Sicherheitsmanagement',
    
        'real-estate' => 'Immobilien',
    
        'research-amp-development' => 'Forschung und Entwicklung',
    
        'retail-amp-wholesale' => 'Einzel- und Großhandel',
    
        'sales' => 'Verkauf',
    
        'social-work' => 'Soziale Arbeit',
    
        'sport-and-or-health-amp-wellness' => 'Sport, Gesundheit und Wellness',
    
        'technology-amp-telecommunications' => 'Technologie und Telekommunikation',
    
        'business-studies-and-or-management-science' => 'Betriebswirtschaft oder Management',
    
        'engineering-and-or-technology' => 'Ingenieurwesen und Technologien',
    
        'social-sciences' => 'Gesellschaftswissenschaften',
    
        'languages-and-philological-sciences' => 'Sprache und Philologie',
    
        'communication-and-information-sciences' => 'Kommunikation und Informationswissenschaften',
    
        'humanities' => 'Geisteswissenschaften',
    
        'education-and-or-teacher-training' => 'Ausbildung und Vorbereitung von Lehrern',
    
        'law' => 'Recht',
    
        'art-and-design' => 'Kunst und Design',
    
        'architecture-and-or-urban-and-regional-planning' => 'Achitektur und/oder urbane und regionale Plannung',
    
        'natural-sciences' => 'Naturwissenschaften',
    
        'mathematics-and-or-informatics' => 'Mathematik und Informatik',
    
        'medical-sciences' => 'Medizinwissenschaften',
    
        'geography-and-or-geology' => 'Geografie und/oder Geologie',
    
        'agriculture-sciences' => 'Landwirtschaftswissenschaften',
    
        'Lang_level_A1' => 'A1: Anfänger',
    
        'Lang_level_A2' => 'A2: Grundkenntnisse',
    
        'Lang_level_B1' => 'B1: Leicht Fortgeschritten',
    
        'Lang_level_B2' => 'B2: Mäßig Fortgeschritten',
    
        'Lang_level_C1' => 'C1: Fortgeschritten',
    
        'Lang_level_C2' => 'C2: Experte',
    
        'description' => 'Description',
    
        'logo' => 'Logo',
    
        'my_profile' => 'Mein Profil',
    
        'profile' => 'Profil',
    
        'profile_visibility' => 'Sichtbarkeit des Profils',
    
        'profile_visibility_visible' => 'Sichtbar. Kann ausgesucht und gesehen werden.',
    
        'profile_visibility_hidden' => 'Versteckt. Kann nicht ausgesucht und gesehen werden.',
    
        'notifications' => 'Benachrichtigungen',
    
        'notifications_enabled' => 'Aktiviert. ',
    
        'notifications_disabled' => 'Deaktiviert. Sie bekommen keine E-Mails außer Service-Benachrichtigungen.',
    
        'about' => 'Inhalt',
    
        'company_logo' => 'Unternehmenslogo',
    
        'social_and_web' => 'Soziale Netzwerke und die Webseite',
    
        'facebook_page_url' => 'Facebook url',
    
        'twitter_page_url' => 'Twitter url',
    
        'linkedin_page_url' => 'Linkedin url',
    
        'web_url' => 'Webseite url',
    
        'what_is_talent_for_you_in_a_few_words' => 'Erläutern Sie kurz, was für Sie Talent bedeutet.',
    
        'most_valuable_skills_for_company' => 'Liste der Fähigkeiten, die für Sie als Unternehmen wichtig sind.',
    
        'setup_alternative_contact' => 'Geben Sie einen alternativen Konatakt des Users an, der alle Benachrichtungen bekommt.',
    
        'update_settings' => 'Update der Eisntellungen.',
    
        'change_your_password' => 'Password ändern',
    
        'new_password' => 'Neues Password',
    
        'repeat_new_password' => 'Wiederholen Sie das neue Password',
    
        'save_new_password' => 'Das neue Password speichern',
    
        'career_and_skills' => 'Karriere und Fähigkeiten',
    
        'my_photo' => 'Mein Foto',
    
        'download_curriculum' => 'Lebenslauf herunterladen',
    
        'my_talent' => 'Mein Talent',
    
        'referee_name' => 'Name des Begutachters',
    
        'referee_email' => 'E-Mail des Begutachters',
    
        'get_your_profile_refereed' => 'Dein Profil begutachten',
    
        'want_to_view_all_details_of_student' => 'Möchten Sie  detailierte Infos über den Studenten sehen?',
    
        'education' => 'Bildung',
    
        'lives_in' => 'Wohnort',
    
        'born_on' => 'Geboren',
    
        'studied_in' => 'Studium',
    
        'skilled_in' => 'Fähigkeiten im Bereich',
    
        'refereed_by' => 'Bewertet von',
    
        'refereeing_pending' => 'Bewertung wird verarbeitet',
    
        'skills' => 'Fähigkeiten ',
    
        'professional' => 'Professionell',
    
        'personal' => 'Persönlich',
    
        'legend' => 'Legende',
    
        'set_by_both_parties' => 'Von beiden Seiten angeführt',
    
        'set_by_referee_or_student' => 'Von Begutachter oder Studenten/Azubi ausgewählt',
    
        'study' => 'Studium|Aussbildung',
    
        'date_not_specified' => 'Datum nicht angegeben',
    
        'get_in_contact' => 'Kontakt aufnehmen',
    
        'want_to_show_this_company_how_talented_you_are' => 'Möchten Sie diesem Unternehmen zeigen, wie talentiert Sie sind?',
    
        'we_are_in' => 'Wir sind in',
    
        'we_are_looking_for_people_skilled_in' => 'Wir suchen Menschen mit Fähigkeiten in',
    
        'we_think_that_talent_is' => 'Ich denke, Talent ist',
    
        'not_enough_information' => 'Ungenügende Informationen.',
    
        'fix_the_following_errors' => 'Es ist nötig, den/die folgenden Fehler zu korrigieren.',
    
        'click_on_button_to_fill_required_fields' => 'Bitte den Button anklicken, um die benötigten Felder auszufüllen.',
    
        'institution_fix_the_following_errors' => 'Es ist nötig den/die folgenden Fehler zu korrigieren, sonst können Ihre Begutachter Ihr Profil nicht validieren.',
    
        'my_institution' => 'Meine Institution',
    
        'required' => 'Benötigt',
    
        'remove_btn' => 'Löschen',
    
        'student_study_institution_name' => 'Name der Institution',
    
        'student_study_course_studies_name' => 'Name der Ausbildung/des Studiums',
    
        'student_download_certificate' => 'Zertifikat herunterladen',
    
        'student_download_grade_card' => 'Bewertungstabelle herunterladen',
    
        'student_study_add_more' => 'Studium hinzufügen',
    
        'student_training_course_name' => 'Name des Kurses',
    
        'student_training_add' => 'Praktikum, Aus-/Weiterbildung hinzufügen',
    
        'student_training_add_more' => 'weiteres Praktikum, Aus-/Weiterbildung hinzufügen',
    
        'student_language' => 'Sprache',
    
        'student_language_name' => 'Name der Sprache',
    
        'student_language_level' => 'Niveau der Sprache',
    
        'student_language_add' => 'Sprache hinzufügen',
    
        'student_language_add_more' => 'weitere Sprachen hinzufügen',
    
        'student_work_experience_to' => 'Arbeit von',
    
        'student_work_experience_from' => 'Arbeit bis',
    
        'student_work_experience_add' => 'Arbeitserfahrung hinzufügen',
    
        'student_work_experience_add_more' => 'weitere Arbeitserfahrungen hinzufügen',
    
        'add_btn' => 'hinzufügen',
    
        'student_professional_skills_remove' => 'Professionelle Fähigkeit löschen',
    
        'student_professional_skills_add' => 'Professionelle Fähigkeit hinzufügen',
    
        'profile_readiness' => 'Vorbereitung des Profils',
    
        'profile_readiness_explanation' => 'Die Bewertung des Profil erlaubt es Anderen sich über Sie eine Meinung zu bilden und erhöht die Möglichkeit, dass ein Unternehmen Sie kontaktiert.',
    
        'get_a_better_refeer' => 'Bekommen Sie eine bessere Bewertung Ihres Profils. Das verbessert Ihr Profil und erhöht die Möglichkeit, dass ein Unternehmen Sie kontaktiert.',
    
        'request_is_managed_by' => 'Ihre Anfrage wird bearbeitet.',
    
        'cant_find_your_institution' => 'Können Sie Ihre Institution nicht finden? Bitten Sie Ihren Gutachter und Ihre Institution, bei Talented Europe mitzumachen.',
    
        'this_step_sends_an_email_to_your_referee' => 'In diesem Schritt bekommt Ihr Gutachter eine E-Mail mit der Anleitung bei Talented Europe mitzumachen.Der Gutachter wird automatisch registriert nachdem seine Institution bei uns mitmacht. Ihre Bewertungsanfrage wird automatisch hinzugefügt.',
    
        'send_invitation' => 'Einladung senden.',
    
        'profile_validated_successfully' => 'Ihr Profil wurde erfolgreich validiert.',
    
        'referee_said_about_you' => 'Das hat Ihr Gutachter über Sie gesagt.',
    
        'profile_validated_denied' => 'Ihr Profil wurde verweigert.',
    
        'not_enough_data_to_do_a_refeer' => 'Wir haben nicht genügend Angaben zum Erstellen einer Begutachtung.',
    
        'progress_account_setup' => 'Kontoeinstellungen',
    
        'progress_refer_your_profile' => 'Profil bewerten',
    
        'progress_not_refereed' => 'Nicht bewertet',
    
        'progress_completed' => 'Beendet',
    
        'you_must_put_referee_email' => '<strong>Achtung:</strong>.Geben Sie die E-Mail des Begutachters an, nicht die der Institution.',
    
        'leave_institution' => 'Die Insitution verlassen?',
    
        'do_you_want_to_leave_institution' => 'Möchten Sie die Institution verlassen? Die nicht beendeten Anträge zur Bewertung werden zurückgeschickt und Sie können niemanden bewerten, bis Sie von der Institution nicht eingeladen werden.',
    
        'leave_institution_button' => 'Ja! Diese akademische Institutiion verlassen.',
    
        'your_profile_is_empty' => 'Ihr Profil ist leer!',
    
        'tab_changes_not_saved' => 'Die Änderungen wurden nicht gespeichert, es kann zum Datenverlust kommen.',
    
        'save_changes' => 'Änderungen speichern',
    
        'continue_without_saving' => 'Weitermachen ohne Speichern.',
    
        'im_here' => 'Ich bin hier!',
    
        'cannot_send_more_alerts_to_this_company_today' => 'Sie können keine weiteren Benachrichtigungen an dieses Unternehmen senden.',
    
        'tell_the_company_that_you_be_interested' => 'Sagen Sie dem Unternehmen, dass Sie Interesse haben, bei ihm zu arbeiten.',
    
        'alert_sent_successfully' => 'Die Benachrichtigung wurde erfolgreich an das Unternehmen gesendet.',
    
        'you_have_already_sent_an_alert_to_this_company' => 'Diesem Unternehmen haben Sie bereits eine Benachrichtigung gesendet.',
    
        'no_matches' => 'Kein Übereinstimmung',
    
        'find_your_academic_institution' => 'Finden Sie Ihre akademische Institution',
    
        'choose_referee' => 'Wählen Sie den Gutachter',
    
        'refer_request' => 'Antrag zur Begutachtung',
    
        'any_referee' => 'Jeder Begutachter',
    
        'institution_type' => 'Typ der Institution',
    
        'complete_the_registration' => 'Beenden Sie die Registrierung, indem Sie folgende Informationen anführen.',
    
        'changes_saved_successfully' => 'Die Änderungen wurden erfolgreich gespeichert.',
    
        'warning_some_fields_has_errors' => 'Vorsicht: Manche Angaben wurden wegen Fehlern nicht beendet. Kontrollieren Sie gründlich jede Angabe.',
    
        'successfully_requested_validation_request' => 'Erfolgreich versendeter Antrag zur Bewertung.',
    
        'invitation_sent_successfully' => 'Einladung erfolgreich gesendet.',
    
        'referee_is_part_of_institution' => 'Der Gutachter ist ein Mitglied %s, treten Sie mit Ihn in Kontakt wegen einer möglichen Änderung der Institution.',
    
        'referee_isnt_part_of_any_institution' => 'Der Gutachter ist kein Mitglied einer Institution. Bitten Sie ihn, dass er sich von einer Institution einladen lässt. ',
    
        'this_email_user_cannot_be_a_referee' => 'Unter dieser E-Mail Adresse ist ein Nutzer registriert, der kein Gutachter sein kann.',
    
        'field' => 'Feld',
    
        'your_request_was_created' => 'Ihre Anfrage wurde erstellt %s',
    
        'if_request_hasnt_been_completed' => 'Falls die Anfrage nicht innerhalb von %s Tagen vervollständigt wurde, können Sie eine neue Anfrage erstellen.',
    
        'you_havent_set_any_personal_skills' => 'Sie haben keine persönlichen Fähigkeiten angegeben. Wenn Sie die Validierung anfordern, können Sie diese nicht bearbeiten.',
    
        'to_see_more_details' => 'Um mehr Details zu sehen, müssen Sie registriert sein.',
    
        'study_institution_name' => 'Name der Bildungsinstitution',
    
        'study_name' => 'Studienname',
    
        'study_level' => 'Studienstufe',
    
        'study_field' => 'Studienfach',
    
        'study_certificate' => 'Studienzertifikat',
    
        'study_gradecard' => 'Tabelle der Studienbewertung',
    
        'training_name' => 'Name der Ausbildung',
    
        'training_date' => 'Datum der Ausbildung',
    
        'training_certificate' => 'Zeugnis',
    
        'language_certificate' => 'Sprachzertifikat',
    
        'professional_skills_name' => 'Profesionelle Fähigkeiten ',
    
        'work_experience_company' => 'Arbeitserfahrung in Unternehmen',
    
        'work_experience_from' => 'Arbeitserfahrung von',
    
        'work_experience_until' => 'Arbeitserfahrung bis',
    
        'work_experience_position' => 'Tätigkeit/Position im Unternehmen',
    
        'about_me' => 'Über mich',
    
        'social_networks' => 'Soziale Netzwerke',
    
        'account_activation_successful' => 'Die Konto-Aktivierung war erfolgreich, Sie können sich jetzt anmelden.',
    
        'account_has_not_been_verified' => 'Das Konto wurde nicht bestätigt. Bitte prüfen Sie, ob Sie eine E-Mail von uns erhalten haben und aktivieren Sie das Konto.',
    
        'at' => 'und',
    
        'remove_account_button' => 'Das Konto löschen.',
    
        'remove_account_confirm' => 'Wollen Sie Ihr Konto wirklich entfernen? Alle Ihre Informationen werden gelöscht.',
    
        'remove_account_button_ok' => 'Ja',
    
        'remove_account_button_cancel' => 'Abbrechen',
    
        'refereed_students' => 'Bewertete Studenten',
    
        'no_refereed_students' => 'Es existieren keine bewerteten Studenten',
    
        'view_contact_details' => 'Sehe die Kontaktangaben durch',
    
        'cant_send_alerts_until_you_fill_the_profile' => 'Um den Unternehmen eine "Bemerkung" zu schicken, muss das ganze Profil ausgefüllt sein. Bitte sehen Sie nach, ob alle Angaben ausgefüllt sind.',
    
        'institution_hei_vet' => 'Ausbildung und Praktikum',
    
        'institution_hei_his' => 'Mittelschule',
    
        'required_cert_warning' => 'Bitte beachten Sie, dass die Institution nicht auf der Liste der Gutachterinsitutionen erscheint, wenn Sie das Zertifikat zur Authentifizierung nicht hochladen.',
    
        'invalid_credentials' => 'Diese Zugangsdaten wurden nicht in unserer Datenbank gefunden',
    
        'alert_already_sent' => 'Alert already sent',
    
        'delete_photo' => 'Foto löschen',
    
        'profile_not_available' => 'Dieses Profil ist momentan nicht verfügbar, bitte versuchen Sie es später',
    
        'passwords_dont_match' => 'Passwörter stimmen nicht überein',
    
        'terms_required' => 'Sie müssen die Nutzungsbedingungen akzeptieren',
    
        'user_type' => 'Benutzertyp',
    
        'password_confirm' => 'Passwort Bestätigung',
    
        'user_type_required' => 'Sie müssen einen Benutzertyp auswählen',
    
        'cant_find_institution_set_mail' => 'Kann nicht Ihre Institution finden, ihnen eine Einladung schicken',
    
        'institution_name' => 'Name der Institution',
    
        'institution_email' => 'Bildungseinrichtung E-Mail',
    
        'search_institutions' => 'Suchen Institutionen',
    
        'select_institution' => 'Wählen Institution',
    
        'save_institution' => 'Speichern Institution',
    
        'institution_data_required' => 'Sie müssen die Namen und die E-Mail von der Institution füllen',
    
        'select_institution_required' => 'Sie müssen die Institution auswählen, denen Sie angehören',
    
        'gdpr_text' => 'Für Talented Europe ist der Datenschutz von Informationen, die wir verarbeiten, sehr wichtig. Aus diesem Grund haben wir die Datenschutz-Grundverordnung in Übereinstimmung mit der GDPR (die Datenschutz-Grundverordnung) aktualisiert.',
    
        'gdpr_data_text' => 'Ihre Personalangaben, die in unserer Database gespeichert sind, können Sie unter dem folgenden Link herunterladen.',
    
        'gdpr_data_download' => 'Personalangaben herunterladen',
    
        'thanks_gdpr' => 'Ihre Benachrichtigungseinstellungen aktualisiert wurden. <br/> Dank!',
    
        'we_are_ngo' => 'Wir sind eine Nichtregierungsorganisation',
    
        'ngo' => 'Nicht-staatliche Organisation',
    
        'job_offers' => 'Jobangebote',
    
        'has_job_offers' => 'Hat Jobangebote',
    
        'offer_add_more' => 'Fügen Sie ein Jobangebot',
    
        'offer' => 'Jobangebot',
    
        'offer_title' => 'Titel',
    
        'offer_describe_description' => 'Schreiben Sie die Jobangebot Beschreibung',
    
        'offer_description' => 'Beschreibung',
    
        'no_job_offers' => 'Es sind keine Jobangebote',
    
        'offer_url' => 'Website mit Unternehmen Jobangebote',
    
        'job_offers_in_te' => 'Stellenangebote in Talented Europe',
    
        'external_job_offers' => 'Schauen Sie sich unser externes Jobportal',
    
        'has_job_portal' => 'Hat ein Jobportal',
    
        'we_have_portal' => 'Aber wir haben ein Job-Portal.',
    
        'portal_check_it_out' => 'Hör zu',
    
        'contact_email' => 'Öffentlicher Kontakt E-Mail',
    
        'load_excel' => 'Laden Einladungen eine Excel-Datei hochladen',
    
        'download_template' => 'Vorlage herunterladen',
    
        'send_invitations' => 'Einladungen verschicken',
    
];