<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'kurzfristige tertiäre Ausbildung',
    
        'studies_level_6' => 'Bachelor oder Ekvivalent',
    
        'studies_level_7' => 'Magister oder Ekvivalent',
    
        'studies_level_8' => 'Doktor oder Ekvivalent',
    
        'company_activity' => 'Feld',
    
        'company_contact_person' => 'Kontaktperson',
    
        'company_representative' => 'Erziehungsberechtigte',
    
        'company_what_is_talent' => 'Was verstehen Sie unter Talent?',
    
        'institution_certificate' => 'Originalitätsbecheinigung',
    
        'city' => 'Stadt',
    
        'country' => 'Land',
    
        'institution_certificate_template_download' => 'Muster herunterladen',
    
        'fiscal_id' => 'Steueridentifikationsnummer',
    
        'institution_hei' => 'Höhere Bildungsinstitution',
    
        'institution_ufa' => 'Universität, Fakultät',
    
        'insitution_his' => 'Mittelschule',
    
        'legal_representative' => 'Erziehungsberechtigte',
    
        'institution_pic' => 'Bild',
    
        'postal_code' => 'PLZ',
    
        'institution_sig_stamp_text' => 'Unterschrift und Stempel',
    
        'institution_vet' => 'Fachausbildung und Praktikum',
    
        'student_academic_info' => 'akademische Informationen',
    
        'address' => 'Anschrift',
    
        'student_certificate' => 'Zertifikat',
    
        'clear_btn' => 'löschen',
    
        'student_experience_company' => 'Unternehmen',
    
        'student_completed_studies' => 'abgeschlossene Ausbildung',
    
        'student_course' => 'Kurs',
    
        'student_date' => 'Datum',
    
        'student_birthdate' => 'Geburtsdatum',
    
        'student_study_level' => 'Niveau',
    
        'student_describe_talent' => 'Beschreiben Sie kurz euer Talent',
    
        'email' => 'E-mail',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Studienrichtung',
    
        'student_study_from' => 'aus',
    
        'student_study_grade_card' => 'Zeugnis',
    
        'student_languages' => 'Sprachen',
    
        'load_btn' => 'Laden',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Name',
    
        'nationality' => 'Nationalität',
    
        'student_personal_information' => 'Persönliche Angaben',
    
        'student_personal_skills' => 'Persönliche Fähigkeiten',
    
        'phone' => 'Telefon',
    
        'position' => 'Position',
    
        'student_professional_skills' => 'Professionelle  Fähigkeite',
    
        'student_proposed_validator' => 'Vorgeschlagener Gutachter',
    
        'save_btn' => 'Speichern',
    
        'student_study_scanned_document' => 'Gescannte Dokument',
    
        'student_validator' => 'Falls Sie den Gutachter nich angeben, wird Ihnen ein Gutachter automatisch zugeteilt',
    
        'surname' => 'Nachname',
    
        'student_study_to' => 'Wem',
    
        'student_training' => 'Praktikum',
    
        'upload_btn' => 'Hochladen',
    
        'student_work_experience' => 'Arbeitserfahrungen',
    
        'validator_department' => 'Abteilung/ Lehrstuhl',
    
        'password' => 'Password',
    
        'confirm_password' => 'Password bestätigen',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Ich bin mit den Bedingungen einverstanden',
    
        'create_account' => 'Ein Konto erstellen',
    
        'forgot_password' => 'Password vergessen?',
    
        'administration' => '',
    
        'architecture-amp-construction' => '',
    
        'art-amp-culture' => '',
    
        'banking-and-or-finance-amp-insurance' => '',
    
        'business-amp-consulting' => '',
    
        'communication-amp-media-amp-pr' => '',
    
        'consumer-goods' => '',
    
        'customer-service' => '',
    
        'design' => '',
    
        'education-amp-training' => '',
    
        'engineering' => '',
    
        'hospitality-amp-tourism' => '',
    
        'human-resources' => '',
    
        'it-amp-web' => '',
    
        'legal' => '',
    
        'logistics' => '',
    
        'manufacturing' => '',
    
        'marketing-amp-advertising' => '',
    
        'medicine-amp-pharmaceutics' => '',
    
        'politics' => '',
    
        'quality-assurance-amp-safety' => '',
    
        'real-estate' => '',
    
        'research-amp-development' => '',
    
        'retail-amp-wholesale' => '',
    
        'sales' => '',
    
        'social-work' => '',
    
        'sport-and-or-health-amp-wellness' => '',
    
        'technology-amp-telecommunications' => '',
    
        'business-studies-and-or-management-science' => '',
    
        'engineering-and-or-technology' => '',
    
        'social-sciences' => '',
    
        'languages-and-philological-sciences' => '',
    
        'communication-and-information-sciences' => '',
    
        'humanities' => '',
    
        'education-and-or-teacher-training' => '',
    
        'law' => '',
    
        'art-and-design' => '',
    
        'architecture-and-or-urban-and-regional-planning' => '',
    
        'natural-sciences' => '',
    
        'mathematics-and-or-informatics' => '',
    
        'medical-sciences' => '',
    
        'geography-and-or-geology' => '',
    
        'agriculture-sciences' => '',
    
        'Lang_level_A1' => '',
    
        'Lang_level_A2' => '',
    
        'Lang_level_B1' => '',
    
        'Lang_level_B2' => '',
    
        'Lang_level_C1' => '',
    
        'Lang_level_C2' => '',
    
];