<?php
// Autogenerated by Translator Builder

return [
    
        'thank_you_for_signing_up' => 'Danke für Ihre Registrierung!',
    
        'you_will_receive_an_email' => 'In einpaar Minuten bekommen Sie eine E-Mail mit den Instruktionen für die Validierung Ihres Kontos.',
    
        'go_back_to_home' => 'Zurück zur Hauptseite',
    
        'search_students' => 'Studenten/Azubis suchen',
    
        'search_companies' => 'Unternehmen suchen',
    
        'register_as_validator' => 'Als Gutachter registrieren',
    
        'there_have_been_some_errors' => 'Es ist ein Fehler aufgetreten.',
    
        'i_am_a' => 'Ich bin ein ',
    
        'all_fields_are_required' => 'Alle Felder müssen ausgefüllt sein',
    
        'confirmation_email_may_take_few_minutes' => 'Sie bekommen die Bestätigungs-Mail in wenigen Minuten. Kontrollieren Sie ggf. auch Ihren Spam-Ordner.',
    
        'registration_complete_successfully' => 'Registrierung erfolgreich beendet.',
    
        'register_success' => 'Registrierung erfolgreich.',
    
        'register' => 'Bitte registrieren',
    
        'invited_by' => 'Eingeladen von...',
    
        'complete_register' => 'Abschließen der Registrierung',
    
];