<?php
// Autogenerated by Translator Builder

return [
    
        'reset_password' => 'Das Password erneuern ',
    
        'send_password_reset' => 'Sende Link zum Erneuern des Paswords',
    
        'set_password' => 'Passwort festlegen',
    
];