<?php
// Autogenerated by Translator Builder

return [
    
        'loading' => 'Laden',
    
        'toggle' => 'Zeigen/Verstecken',
    
        'current_search' => 'Aktuelle Suche',
    
        'refereed' => 'Begutachtet',
    
        'there_are_no_matching_the_selected_filters' => 'Im Moment gibt es keine %s mit den ausgewählten Filtern.',
    
        'we_found' => 'Erfüllt die Bedürfnisse',
    
        'we_found_matching_your_needs' => 'Wir haben gefunden %number% %collective%, die Ihren Angaben entsprechen.',
    
        'filters' => 'Filter',
    
];