<?php
// Autogenerated by Translator Builder

return [
    
        'loading' => 'Laden',
    
        'toggle' => 'Zeigen/Verstecken',
    
        'current_search' => 'Aktuelle Suche',
    
        'refereed' => 'hat begutachtet',
    
        'there_are_no_matching_the_selected_filters' => 'Im Moment gibt es keine  % mit den ausgewählten Filtern.',
    
        'we_found' => 'Erfüllt die Bedürfnisse',
    
        'we_found_matching_your_needs' => 'Wir haben gefunden % Nummer % Kolektiv %, die IHren Bedürfnissen entsprechen.',
    
        'filters' => 'Filter',
    
];