<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'ersucht am',
    
        'pending' => 'wartend',
    
        'validated' => 'begutachtet',
    
        'not_validated' => 'nicht begutachtet',
    
        'no_students' => 'Keine Studente',
    
        'confirm_validation' => 'Gutachtung bestätigen',
    
        'are_you_sure_you_want_to_finish_refereeing' => 'Möchten SIe die Bewertung des Studenten beenden?',
    
        'reason' => 'Grund',
    
        'criteria' => 'Der Student erfüllt die Kriterien nicht',
    
        'nostudent' => 'Der Student besuchte diese Schule/Institution nicht',
    
];
