<?php
// Autogenerated by Translator Builder

return [
    
        'accountActivated_subject_1' => 'Acción requerida: activa tu cuenta',
    
        'accountActivated_line_2' => 'Gracias por inscribirte en Talented Europe.',
    
        'accountActivated_line_3' => 'Por favor, verifica tu dirección de correo electrónico haciendo clic en el enlace a continuación.',
    
        'accountActivated_action_4' => 'Confirmar mi cuenta',
    
        'accountActivated_line_5' => 'Gracias por usar nuestra aplicación',
    
        'changeInstitution_subject_1' => '%s te ha invitado como validador en Talented Europe.',
    
        'changeInstitution_line_2' => '%s te ha invitado como validador en Talented Europe.',
    
        'changeInstitution_line_3' => 'Puesto que ya eres validador de Talented Europe, necesitamos que confirmes este cambio.',
    
        'changeInstitution_action_4' => 'Confirmar cambio',
    
        'changeInstitution_line_5' => '¡Gracias por usar nuestra aplicación!',
    
        'institutionRemoved.subject_1' => '%s te ha eliminado de su institución en Talented Europe',
    
        'institutionRemoved.line_2' => '%s te ha eliminado de su institución en Talented Europe. Si fuiste eliminado por error, por favor, ponte en contacto con ellos para solucionar esta situación.',
    
        'institutionRemoved.line_3' => '¡Gracias por usar nuestra aplicación!',
    
        'inviteCreated_subject_1' => '%s te ha invitado como validador en Talented Europe.',
    
        'inviteCreated_line_2' => '%s te ha invitado como validador en Talented Europe.',
    
        'inviteCreated_line_3' => 'Crea tu cuenta haciendo clic en el siguiente enlace',
    
        'inviteCreated_action_4' => 'Crear mi cuenta',
    
        'inviteCreated_line_5' => '¡Gracias por usar nuestra aplicación!',
    
        'validatorRequested_subject_1' => '%s te ha invitado como validador en Talented Europe.',
    
        'validatorRequested_line_2' => 'Hola %s',
    
        'validatorRequested_line_3' => '%s te ha invitado como validador en Talented Europe.',
    
        'validatorRequested_line_4' => 'Reenvía este correo electrónico a la institución para la que trabajas para que puedan registrarse a través del siguiente enlace',
    
        'validatorRequested_line_5' => 'Si se registra tu institución haciendo clic en el siguiente enlace, automáticamente estarás invitado',
    
        'validatorRequested_action_6' => 'Crear cuenta de institución',
    
        'validatorRequested_line_7' => '¡Gracias por usar nuestra aplicación!',
    
        'newAlerts_subject_1' => 'Nuevas alertas de los estudiantes',
    
        'newAlerts_line_2' => '¡Hola! te recordamos que algunos estudiantes te han enviado alertas en nuestra plataforma',
    
        'newAlerts_line_3' => 'Haga clic en el siguiente botón para iniciar sesión y ver su panel',
    
        'validationsPending_subject_1' => 'Validaciones pendientes en Talented Europe',
    
        'validationsPending_line_2' => '¡Hola! te recordamos que tienes algunas validaciones de estudiantes o recien titulados pendientes en nuestra plataforma',
    
        'validationsPending_line_3' => 'Haga clic en el siguiente botón para iniciar sesión y ver su panel',
    
        'disclaimer' => '<strong> RENUNCIA </ strong>: Este mensaje se dirige exclusivamente a su destinatario y puede contener información que es <strong> CONFIDENCIAL </ strong>, y protegida por el secreto profesional. Si usted no es el destinatario indicado, queda notificado de que cualquier divulgación, copia o divulgación de esta comunicación está estrictamente prohibida por la ley. Si este mensaje se ha recibido por error, por favor notifique inmediatamente por correo electrónico a (% s) y eliminarlo.',
    
        'hello' => '¡Hola!',
    
        'regards' => 'Saludos',
    
        'disclaimer_plain' => 'Exención de responsabilidad: Este mensaje se dirige exclusivamente a su dirección y puede contener información confidencial y protegida por el secreto profesional. Si usted no es el destinatario indicado, queda notificado de que cualquier divulgación, copia o divulgación de esta comunicación está estrictamente prohibida por la ley. Si este mensaje se ha recibido por error, por favor notifique inmediatamente por correo electrónico a% s y eliminarlo.\'',
    
        'profile_not_filled_subject' => 'Su perfil no está completo',
    
        'profile_not_filled_line_1' => 'Hemos visto que su perfil no está completo, por lo que queríamos recordarle que a menos de que llene toda la información requerida no será capaz de acceder a todas las características de nuestra aplicación.',
    
];