<?php
// Autogenerated by Translator Builder

return [
    
        'BE' => 'Bélgica',
    
        'BG' => 'Bulgaria',
    
        'HR' => 'Croacia',
    
        'CY' => 'Chipre',
    
        'CZ' => 'República Checa',
    
        'DK' => 'Dinamarca',
    
        'EE' => 'Estonia',
    
        'FI' => 'Finlandia',
    
        'FR' => 'Francia',
    
        'DE' => 'Alemania',
    
        'GR' => 'Grecia',
    
        'HU' => 'Hungría',
    
        'IE' => 'Irlanda',
    
        'IT' => 'Italia',
    
        'LV' => 'Letonia',
    
        'LT' => 'Lituania',
    
        'LU' => 'Luxemburgo',
    
        'MT' => 'Malta',
    
        'NL' => 'Países Bajos',
    
        'PL' => 'Polonia',
    
        'PT' => 'Portugal',
    
        'RO' => 'Rumania',
    
        'SK' => 'Eslovaquia',
    
        'SI' => 'Eslovenia',
    
        'SP' => 'España',
    
        'SE' => 'Suecia',
    
        'UK' => 'Reino Unido',
    
        'login_btn' => '',
    
        'register_button' => '',
    
        'search_info' => '',
    
        'company' => '',
    
        'institution' => '',
    
        'student' => '',
    
        'more_btn' => '',
    
        'cookie_text' => '',
    
        'cookie_accept' => '',
    
];