<?php
// Autogenerated by Translator Builder

return [
    
        'BE' => 'Bélgica',
    
        'BG' => 'Bulgaria',
    
        'HR' => 'Croacia',
    
        'CY' => 'Chipre',
    
        'CZ' => 'República Checa',
    
        'DK' => 'Dinamarca',
    
        'EE' => 'Estonia',
    
        'FI' => 'Finlandia',
    
        'FR' => 'Francia',
    
        'DE' => 'Alemania',
    
        'GR' => 'Grecia',
    
        'HU' => 'Hungría',
    
        'IE' => 'Irlanda',
    
        'IT' => 'Italia',
    
        'LV' => 'Letonia',
    
        'LT' => 'Lituania',
    
        'LU' => 'Luxemburgo',
    
        'MT' => 'Malta',
    
        'NL' => 'Países Bajos',
    
        'PL' => 'Polonia',
    
        'PT' => 'Portugal',
    
        'RO' => 'Rumania',
    
        'SK' => 'Eslovaquia',
    
        'SI' => 'Eslovenia',
    
        'SP' => 'España',
    
        'SE' => 'Suecia',
    
        'UK' => 'Reino Unido',
    
        'login_btn' => 'Iniciar sesión',
    
        'register_btn' => 'Regístrate',
    
        'search_info' => 'Buscar',
    
        'company' => 'Empresa|Empresas',
    
        'institution' => 'Institución|Instituciones',
    
        'student' => 'Estudiante|Estudiantes',
    
        'more_btn' => 'Ver más',
    
        'cookie_text' => 'Este sitio web utiliza cookies para ayudarnos a darle la mejor experiencia al visitar nuestro sitio web. Al continuar utilizando este sitio web, usted da su consentimiento a nuestro uso de estas cookies . Para saber más sobre cómo utilizamos las cookies y cómo manejarlas  lea <a href="/privacy-policy">cookie notice</a>',
    
        'cookie_accept' => 'cerrar',
    
        'logout_btn' => 'Cerrar Sesión',
    
];