<?php
// Autogenerated by Translator Builder

return [
    
        'remember_me' => 'Recuérdame',
    
        'sign_in' => 'Registrarse',
    
        'login_title' => 'Iniciar sesión',
    
        'login_btn' => 'Acceder',
    
];