<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'Educación terciaria de ciclo corto',
    
        'studies_level_6' => 'Grado en educación terciaria o nivel equivalente ',
    
        'studies_level_7' => 'Nivel de maestría, especialización o equivalente',
    
        'studies_level_8' => 'Nivel de doctorado o equivalente',
    
        'company_activity' => 'Sector de actividad',
    
        'company_contact_person' => 'Persona de contacto',
    
        'company_representative' => 'Representante legal (Persona a cargo)',
    
        'company_what_is_talent' => '¿Qué es el talento para ti?',
    
        'institution_certificate' => 'Certificado de autenticidad',
    
        'city' => 'Ciudad',
    
        'country' => 'País',
    
        'institution_certificate_template_download' => 'Descargar plantilla',
    
        'fiscal_id' => 'Número de identificación fiscal',
    
        'institution_hei' => 'Institución de educación superior',
    
        'institution_ufa' => 'Universidad, facultad',
    
        'insitution_his' => 'Escuela secundaria',
    
        'legal_representative' => 'Representante legal (Persona a cargo)',
    
        'institution_pic' => 'Foto',
    
        'postal_code' => 'Código postal',
    
        'institution_sig_stamp_text' => 'Firma y sello',
    
        'institution_vet' => 'Formación profesional y prácticas',
    
        'student_academic_info' => 'Información académica',
    
        'address' => 'Dirección',
    
        'student_certificate' => 'Certificado',
    
        'clear_btn' => 'Borrar',
    
        'student_experience_company' => 'Empresa',
    
        'student_completed_studies' => 'Estudios terminados',
    
        'student_course' => 'Curso',
    
        'student_date' => 'Fecha',
    
        'student_birthdate' => 'Fecha de nacimiento',
    
        'student_study_level' => 'Nivel',
    
        'student_describe_talent' => 'Describe brevemente tu talento',
    
        'email' => 'Email',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Campo de estudios',
    
        'student_study_from' => 'De',
    
        'student_study_grade_card' => 'Tarjeta de calificación',
    
        'student_languages' => 'Idiomas',
    
        'load_btn' => 'Cargar',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Nombre',
    
        'nationality' => 'Nacionalidad',
    
        'student_personal_information' => 'Información personal',
    
        'student_personal_skills' => 'Habilidades personales',
    
        'phone' => 'Teléfono',
    
        'position' => 'Posición',
    
        'student_professional_skills' => 'Habilidades profesionales',
    
        'student_proposed_validator' => 'Validador propuesto',
    
        'save_btn' => 'Guardar',
    
        'student_study_scanned_document' => 'Documento escaneado',
    
        'student_validator' => 'Si no se especifica un validador será asignado automáticamente',
    
        'surname' => 'Apellido',
    
        'student_study_to' => 'A',
    
        'student_training' => 'Prácticas',
    
        'upload_btn' => 'Subir',
    
        'student_work_experience' => 'Experiencia laboral',
    
        'validator_department' => 'Departamento',
    
        'password' => 'Contraseña',
    
        'confirm_password' => 'Confirmar contraseña',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Estoy de acuerdo con los términos de uso',
    
        'create_account' => 'Crear una cuenta nueva',
    
        'forgot_password' => '¿Olvidaste tu contraseña?',
    
        'administration' => '',
    
        'architecture-amp-construction' => '',
    
        'art-amp-culture' => '',
    
        'banking-and-or-finance-amp-insurance' => '',
    
        'business-amp-consulting' => '',
    
        'communication-amp-media-amp-pr' => '',
    
        'consumer-goods' => '',
    
        'customer-service' => '',
    
        'design' => '',
    
        'education-amp-training' => '',
    
        'engineering' => '',
    
        'hospitality-amp-tourism' => '',
    
        'human-resources' => '',
    
        'it-amp-web' => '',
    
        'legal' => '',
    
        'logistics' => '',
    
        'manufacturing' => '',
    
        'marketing-amp-advertising' => '',
    
        'medicine-amp-pharmaceutics' => '',
    
        'politics' => '',
    
        'quality-assurance-amp-safety' => '',
    
        'real-estate' => '',
    
        'research-amp-development' => '',
    
        'retail-amp-wholesale' => '',
    
        'sales' => '',
    
        'social-work' => '',
    
        'sport-and-or-health-amp-wellness' => '',
    
        'technology-amp-telecommunications' => '',
    
        'business-studies-and-or-management-science' => '',
    
        'engineering-and-or-technology' => '',
    
        'social-sciences' => '',
    
        'languages-and-philological-sciences' => '',
    
        'communication-and-information-sciences' => '',
    
        'humanities' => '',
    
        'education-and-or-teacher-training' => '',
    
        'law' => '',
    
        'art-and-design' => '',
    
        'architecture-and-or-urban-and-regional-planning' => '',
    
        'natural-sciences' => '',
    
        'mathematics-and-or-informatics' => '',
    
        'medical-sciences' => '',
    
        'geography-and-or-geology' => '',
    
        'agriculture-sciences' => '',
    
        'Lang_level_A1' => '',
    
        'Lang_level_A2' => '',
    
        'Lang_level_B1' => '',
    
        'Lang_level_B2' => '',
    
        'Lang_level_C1' => '',
    
        'Lang_level_C2' => '',
    
];