<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'Educación terciaria de ciclo corto',
    
        'studies_level_6' => 'Grado en educación terciaria o nivel equivalente ',
    
        'studies_level_7' => 'Nivel de maestría, especialización o equivalente',
    
        'studies_level_8' => 'Nivel de doctorado o equivalente',
    
        'company_activity' => 'Sector de actividad',
    
        'company_contact_person' => 'Persona de contacto',
    
        'company_contact_person_name' => 'Contact person name',
    
        'company_contact_person_email' => 'Contact person email',
    
        'company_representative' => 'Representante legal (Persona a cargo)',
    
        'company_what_is_talent' => '¿Qué es el talento para ti?',
    
        'institution_certificate' => 'Certificado de autenticidad',
    
        'city' => 'Ciudad',
    
        'country' => 'País',
    
        'countries' => 'Países',
    
        'institution_certificate_template_download' => 'Descargar plantilla',
    
        'fiscal_id' => 'Número de identificación fiscal',
    
        'institution_hei' => 'Institución de educación superior',
    
        'institution_ufa' => 'Universidad, facultad',
    
        'insitution_his' => 'Escuela secundaria',
    
        'legal_representative' => 'Representante legal (Persona a cargo)',
    
        'institution_pic' => 'Foto',
    
        'postal_code' => 'Código postal',
    
        'institution_sig_stamp_text' => 'Firma y sello',
    
        'institution_vet' => 'Formación profesional y prácticas',
    
        'student_academic_info' => 'Información académica',
    
        'address' => 'Dirección',
    
        'student_certificate' => 'Certificado',
    
        'clear_btn' => 'Borrar',
    
        'student_experience_company' => 'Empresa',
    
        'student_completed_studies' => 'Estudios terminados',
    
        'student_course' => 'Curso',
    
        'student_date' => 'Fecha',
    
        'student_birthdate' => 'Fecha de nacimiento',
    
        'student_study_level' => 'Nivel',
    
        'student_describe_talent' => 'Describe brevemente tu talento',
    
        'email' => 'Email',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Campo de estudios',
    
        'student_study_from' => 'De',
    
        'student_study_grade_card' => 'Tarjeta de calificación',
    
        'student_languages' => 'Idiomas',
    
        'load_btn' => 'Cargar',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Nombre',
    
        'nationality' => 'Nacionalidad',
    
        'student_personal_information' => 'Información personal',
    
        'student_personal_skills' => 'Habilidades personales',
    
        'phone' => 'Teléfono',
    
        'position' => 'Posición',
    
        'student_professional_skills' => 'Habilidades profesionales',
    
        'student_proposed_validator' => 'Validador propuesto',
    
        'save_btn' => 'Guardar',
    
        'student_study_scanned_document' => 'Documento escaneado',
    
        'student_validator' => 'Si no se especifica un validador será asignado automáticamente',
    
        'surname' => 'Apellido',
    
        'student_study_to' => 'A',
    
        'student_training' => 'Prácticas',
    
        'upload_btn' => 'Subir',
    
        'student_work_experience' => 'Experiencia laboral',
    
        'validator_department' => 'Departamento',
    
        'password' => 'Contraseña',
    
        'confirm_password' => 'Confirmar contraseña',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Estoy de acuerdo con los términos de uso',
    
        'i_agree_with' => 'Estoy de acuerdo con',
    
        'the_terms_of_use' => 'los términos de uso',
    
        'create_account' => 'Crear una cuenta nueva',
    
        'forgot_password' => '¿Olvidaste tu contraseña?',
    
        'administration' => 'Administración',
    
        'architecture-amp-construction' => 'Arquitectura y Construcción',
    
        'art-amp-culture' => 'Arte y Cultura',
    
        'banking-and-or-finance-amp-insurance' => 'Banca y/o finanzas y seguros',
    
        'business-amp-consulting' => 'Comercio y Consultoría',
    
        'communication-amp-media-amp-pr' => 'Comunicación, medios de comunicación y RR.PP.',
    
        'consumer-goods' => 'Bienes de consumo',
    
        'customer-service' => 'Servicio al cliente',
    
        'design' => 'Diseño',
    
        'education-amp-training' => 'Educación y Formación',
    
        'engineering' => 'Ingeniería',
    
        'hospitality-amp-tourism' => 'Hostelería y turismo',
    
        'human-resources' => 'Recursos humanos',
    
        'it-amp-web' => 'IT y web',
    
        'legal' => 'Derecho',
    
        'logistics' => 'Logística',
    
        'manufacturing' => 'Producción',
    
        'marketing-amp-advertising' => 'Marketing y Publicidad',
    
        'medicine-amp-pharmaceutics' => 'Medicina y Farmacia',
    
        'politics' => 'Política',
    
        'quality-assurance-amp-safety' => 'Aseguramiento de Calidad y Seguridad',
    
        'real-estate' => 'Bienes inmuebles',
    
        'research-amp-development' => 'Investigación y desarrollo',
    
        'retail-amp-wholesale' => 'Comercio al por menor y al por mayor',
    
        'sales' => 'Ventas',
    
        'social-work' => 'Trabajo social',
    
        'sport-and-or-health-amp-wellness' => 'Deporte y/o Salud y bienestar',
    
        'technology-amp-telecommunications' => 'Tecnología y Telecomunicaciones',
    
        'business-studies-and-or-management-science' => 'Estudios de negocios y/o Ciencias de la Gestión',
    
        'engineering-and-or-technology' => 'Ingeniería y/o Tecnología',
    
        'social-sciences' => 'Ciencias Sociales',
    
        'languages-and-philological-sciences' => 'Lenguas y Ciencias Filológicas',
    
        'communication-and-information-sciences' => 'Comunicación y Ciencias de la Información',
    
        'humanities' => 'Humanidades',
    
        'education-and-or-teacher-training' => 'Educación y /o Formación del profesorado',
    
        'law' => 'Derecho',
    
        'art-and-design' => 'Arte y diseño',
    
        'architecture-and-or-urban-and-regional-planning' => 'Arquitectura y/o Planificación Urbana y Regional',
    
        'natural-sciences' => 'Ciencias Naturales',
    
        'mathematics-and-or-informatics' => 'Matemáticas y/o Informática',
    
        'medical-sciences' => 'Ciencias Médicas',
    
        'geography-and-or-geology' => 'Geografía y/o Geología',
    
        'agriculture-sciences' => 'Ciencias Agrarias',
    
        'Lang_level_A1' => 'A1: Acceso o principiante',
    
        'Lang_level_A2' => 'A2: Plataforma o básico',
    
        'Lang_level_B1' => 'B1: Umbral o intermedio',
    
        'Lang_level_B2' => 'B2: Avanzado o intermedio alto',
    
        'Lang_level_C1' => 'C1: Dominio operativo eficaz o superior bajo',
    
        'Lang_level_C2' => 'C2: Maestría o superior',
    
        'logo' => 'Logo',
    
        'my_profile' => 'Mi perfil',
    
        'profile' => 'Perfil',
    
        'profile_visibility' => 'Visibilidad del perfil',
    
        'profile_visibility_visible' => 'Visible. Puede ser buscado, visto',
    
        'profile_visibility_hidden' => 'Oculto. No puede ser buscado ni visto',
    
        'notifications' => 'Notificaciones',
    
        'notifications_enabled' => 'Enabled. You\'ll receive emails once a day if a student wants to get in contact with you',
    
        'notifications_disabled' => 'Disabled. You won\'t receive any emails, except for announcements about the service',
    
        'about' => 'Acerca de',
    
        'company_logo' => 'Logotipo de la empresa',
    
        'social_and_web' => 'Redes sociales y página web personal',
    
        'facebook_page_url' => 'URL de la página de Facebook',
    
        'twitter_page_url' => 'URL de la página de Twitter',
    
        'linkedin_page_url' => 'URL de la página de Linkedin',
    
        'web_url' => 'Dirección de la página Web',
    
        'what_is_talent_for_you_in_a_few_words' => 'Explícanos brevemente qué es talento para ti.',
    
        'most_valuable_skills_for_company' => 'Un listado de las habilidades más valoradas por la empresa',
    
        'setup_alternative_contact' => 'Seleccione un usuario de contacto alternativo para que reciba las notificaciones en lugar de la cuenta principal de la institución',
    
        'update_settings' => 'Modificar mi configuración',
    
        'change_your_password' => 'Cambiar la contraseña',
    
        'new_password' => 'Contraseña nueva',
    
        'repeat_new_password' => 'Repetir la contraseña nueva',
    
        'save_new_password' => 'Guardar la contraseña nueva',
    
        'career_and_skills' => 'Estudios y habilidades',
    
        'my_photo' => 'Mi fotografía de perfil',
    
        'download_curriculum' => 'Descargar curriculum',
    
        'my_talent' => 'Mi talento',
    
        'referee_name' => 'Nombre del validador',
    
        'referee_email' => 'Email del validador',
    
        'get_your_profile_refereed' => 'Obtén tu perfil validado',
    
        'want_to_view_all_details_of_student' => '¿Quiere ver todos los detalles del estudiante?',
    
        'education' => 'Educación',
    
        'lives_in' => 'Vive en',
    
        'born_on' => 'Nacido en',
    
        'studied_in' => 'Estudió en',
    
        'skilled_in' => 'Competente en',
    
        'refereed_by' => 'Validado por',
    
        'refereeing_pending' => 'Pendiente de validación',
    
        'skills' => 'Habilidades',
    
        'professional' => 'Profesional',
    
        'personal' => 'Personal',
    
        'legend' => 'Leyenda',
    
        'set_by_both_parties' => 'Seleccionado por ambas partes',
    
        'set_by_referee_or_student' => 'Selecionando por el validador o el estudiante',
    
        'study' => 'Estudio|Estudios',
    
        'date_not_specified' => 'Fecha no especificada',
    
        'get_in_contact' => 'Mantente en contacto',
    
        'want_to_show_this_company_how_talented_you_are' => '¿Quieres mostrar a esta empresa tu talento?',
    
        'we_are_in' => 'Estamos en',
    
        'we_are_looking_for_people_skilled_in' => 'Estamos buscando personas con habilidades en',
    
        'we_think_that_talent_is' => 'Creemos que el talento es',
    
        'not_enough_information' => 'No hay suficiente información',
    
        'fix_the_following_errors' => 'Necesitas corregir los siguientes errores',
    
        'click_on_button_to_fill_required_fields' => 'Haz click en el siguiente botón para rellenar los campos requeridos.',
    
        'institution_fix_the_following_errors' => 'Corrige los siguientes errores o los validadores no podrán validar perfiles',
    
        'my_institution' => 'Mi institución',
    
        'required' => 'Requerido',
    
        'remove_btn' => 'Eliminar',
    
        'student_study_institution_name' => 'Nombre de la institución',
    
        'student_study_course_studies_name' => 'Nombre del Curso / Estudios',
    
        'student_download_certificate' => 'Descargar certificado',
    
        'student_download_grade_card' => 'Descargar la tabla de valuación',
    
        'student_study_add_more' => 'Añadir más estudios',
    
        'student_training_course_name' => 'Nombre del curso',
    
        'student_training_add' => 'Añadir un curso',
    
        'student_training_add_more' => 'Añadir más cursos',
    
        'student_language' => 'Idioma',
    
        'student_language_name' => 'Nombre del idioma',
    
        'student_language_level' => 'Nivel de idioma',
    
        'student_language_add' => 'añadir un idioma',
    
        'student_language_add_more' => 'añadir más idiomas',
    
        'student_work_experience_to' => 'Trabajó hasta',
    
        'student_work_experience_from' => 'Trabajó desde',
    
        'student_work_experience_add' => 'añadir experiencia laboral',
    
        'student_work_experience_add_more' => 'añadir más experiencia laboral',
    
        'add_btn' => 'Añadir',
    
        'student_professional_skills_remove' => 'Eliminar una habilidad profesional',
    
        'student_professional_skills_add' => 'Añadir una habilidad profesional',
    
        'profile_readiness' => 'Preparación del perfil',
    
        'profile_readiness_explanation' => 'La validación de tu perfil ayuda a terceros a formar una opinión de ti y aumenta las posibilidades de que una empresa se ponga en contacto contigo',
    
        'get_a_better_refeer' => 'Obtén mejor validación de tu perfil aumentando su preparación y al mismo tiempo aumentando las posibilidades que estar contactado por la empresa',
    
        'request_is_managed_by' => 'Tu solicitud está siendo gestionada por',
    
        'cant_find_your_institution' => '¿No puedes encontrar tu institución? Pide a tu validador y a la institución que se unan a Talented Europe',
    
        'this_step_sends_an_email_to_your_referee' => 'Este paso envía un correo electrónico a su validador con instrucciones sobre cómo unirse a Talented Europe, lo registra automáticamente como validador una vez que su institución se una también a Talented Europe y te agrega ti a la lista de validaciones pendientes de revisar de ese validador',
    
        'send_invitation' => 'Enviar invitación',
    
        'profile_validated_successfully' => 'Tu perfil ha sido validado',
    
        'referee_said_about_you' => 'Esto ha dicho tu validador sobre ti',
    
        'profile_validated_denied' => 'Tu perfil fue rechazado',
    
        'not_enough_data_to_do_a_refeer' => 'No tenemos suficientes datos para hacer la validación.',
    
        'progress_account_setup' => 'Configuración de la cuenta',
    
        'progress_refer_your_profile' => 'Validar tu perfil',
    
        'progress_not_refereed' => 'No validado',
    
        'progress_completed' => 'Completado',
    
        'you_must_put_referee_email' => '<strong>Por favor, tenga en cuenta:</strong> Tiene que introducir el correo electrónico del validador no de la institución',
    
        'leave_institution' => '¿Abandonas la institución educativa?',
    
        'do_you_want_to_leave_institution' => '¿Quieres abandonar la institución? Las solicitudes de validación pendientes serán devueltas y usted no podrá validar a nadie hasta que otra institución no lo invite de nuevo',
    
        'leave_institution_button' => 'Sí. Abandono la institución académica',
    
        'your_profile_is_empty' => '¡Tu perfil está vacío!',
    
        'tab_changes_not_saved' => 'Los cambios no se han guardado, es posible que se pierdan algunos datos',
    
        'save_changes' => 'Guardar los cambios',
    
        'continue_without_saving' => 'Continuar sin guardar',
    
        'im_here' => '¡Estoy aquí!',
    
        'cannot_send_more_alerts_to_this_company_today' => 'No se pueden enviar más alertas a esta empresa hoy.',
    
        'tell_the_company_that_you_be_interested' => 'Dile a la empresa que estás interesado en trabajar para ellos',
    
        'alert_sent_successfully' => 'Alerta enviada satisfactoriamente a la empresa',
    
        'you_have_already_sent_an_alert_to_this_company' => 'Ya has enviado una alerta a esta empresa',
    
        'no_matches' => 'No se cumplen los requisitos',
    
        'find_your_academic_institution' => 'Filtrar tu Institución Académica',
    
        'choose_referee' => 'Elegir validador',
    
        'refer_request' => 'Solicitar validador',
    
        'any_referee' => 'Cualquier validador',
    
        'institution_type' => 'Tipo de institución',
    
        'complete_the_registration' => 'Complete el registro añadiendo la siguiente información',
    
        'changes_saved_successfully' => 'Changes saved successfully',
    
        'warning_some_fields_has_errors' => 'Warning: Some fields couldn\'t be saved because there were errors, check each field to see the issues',
    
        'successfully_requested_validation_request' => 'Successfully requested validation request',
    
        'invitation_sent_successfully' => 'Invitation sent successfully',
    
        'referee_is_part_of_institution' => 'Referee is part of %s get in contact with him to ask a institution change if required',
    
        'referee_isnt_part_of_any_institution' => 'Referee isn\'t part of any institution. Please ask him to get invited by one',
    
        'this_email_user_cannot_be_a_referee' => 'This email address is registered to an user that cannot be a referee',
    
        'field' => 'Field',
    
];
