<?php
// Autogenerated by Translator Builder

return [
    
        'studies_level_5' => 'Educación terciaria de ciclo corto',
    
        'studies_level_6' => 'Grado en educación terciaria o nivel equivalente ',
    
        'studies_level_7' => 'Nivel de maestría, especialización o equivalente',
    
        'studies_level_8' => 'Nivel de doctorado o equivalente',
    
        'company_activity' => 'Sector de actividad',
    
        'company_contact_person' => 'Persona de contacto',
    
        'company_representative' => 'Representante legal (Persona a cargo)',
    
        'company_what_is_talent' => '¿Qué es el talento para ti?',
    
        'institution_certificate' => 'Certificado de autenticidad',
    
        'city' => 'Ciudad',
    
        'country' => 'País',
    
        'institution_certificate_template_download' => 'Descargar plantilla',
    
        'fiscal_id' => 'Número de identificación fiscal',
    
        'institution_hei' => 'Institución de educación superior',
    
        'institution_ufa' => 'Universidad, facultad',
    
        'insitution_his' => 'Escuela secundaria',
    
        'legal_representative' => 'Representante legal (Persona a cargo)',
    
        'institution_pic' => 'Foto',
    
        'postal_code' => 'Código postal',
    
        'institution_sig_stamp_text' => 'Firma y sello',
    
        'institution_vet' => 'Formación profesional y prácticas',
    
        'student_academic_info' => 'Información académica',
    
        'address' => 'Dirección',
    
        'student_certificate' => 'Certificado',
    
        'clear_btn' => 'Borrar',
    
        'student_experience_company' => 'Empresa',
    
        'student_completed_studies' => 'Estudios terminados',
    
        'student_course' => 'Curso',
    
        'student_date' => 'Fecha',
    
        'student_birthdate' => 'Fecha de nacimiento',
    
        'student_study_level' => 'Nivel',
    
        'student_describe_talent' => 'Describe brevemente tu talento',
    
        'email' => 'Email',
    
        'student_europass' => 'Europass',
    
        'student_study_field' => 'Campo de estudios',
    
        'student_study_from' => 'De',
    
        'student_study_grade_card' => 'Tarjeta de calificación',
    
        'student_languages' => 'Idiomas',
    
        'load_btn' => 'Cargar',
    
        'input_max_characters' => 'max.',
    
        'name' => 'Nombre',
    
        'nationality' => 'Nacionalidad',
    
        'student_personal_information' => 'Información personal',
    
        'student_personal_skills' => 'Habilidades personales',
    
        'phone' => 'Teléfono',
    
        'position' => 'Posición',
    
        'student_professional_skills' => 'Habilidades profesionales',
    
        'student_proposed_validator' => 'Validador propuesto',
    
        'save_btn' => 'Guardar',
    
        'student_study_scanned_document' => 'Documento escaneado',
    
        'student_validator' => 'Si no se especifica un validador será asignado automáticamente',
    
        'surname' => 'Apellido',
    
        'student_study_to' => 'A',
    
        'student_training' => 'Prácticas',
    
        'upload_btn' => 'Subir',
    
        'student_work_experience' => 'Experiencia laboral',
    
        'validator_department' => 'Departamento',
    
        'password' => 'Contraseña',
    
        'confirm_password' => 'Confirmar contraseña',
    
        'captcha' => 'Captcha',
    
        'terms_of_use' => 'Estoy de acuerdo con los términos de uso',
    
        'i_agree_with' => 'Estoy de acuerdo con',
    
        'the_terms_of_use' => 'los términos de uso',
    
        'create_account' => 'Crear una cuenta nueva',
    
        'forgot_password' => '¿Olvidaste tu contraseña?',
    
        'administration' => 'Administración',
    
        'architecture-amp-construction' => 'Arquitectura y Construcción',
    
        'art-amp-culture' => 'Arte y Cultura',
    
        'banking-and-or-finance-amp-insurance' => 'Banca y/o finanzas y seguros',
    
        'business-amp-consulting' => 'Comercio y Consultoría',
    
        'communication-amp-media-amp-pr' => 'Comunicación, medios de comunicación y RR.PP.',
    
        'consumer-goods' => 'Bienes de consumo',
    
        'customer-service' => 'Servicio al cliente',
    
        'design' => 'Diseño',
    
        'education-amp-training' => 'Educación y Formación',
    
        'engineering' => 'Ingeniería',
    
        'hospitality-amp-tourism' => 'Hostelería y turismo',
    
        'human-resources' => 'Recursos humanos',
    
        'it-amp-web' => 'IT y web',
    
        'legal' => 'Derecho',
    
        'logistics' => 'Logística',
    
        'manufacturing' => 'Producción',
    
        'marketing-amp-advertising' => 'Marketing y Publicidad',
    
        'medicine-amp-pharmaceutics' => 'Medicina y Farmacia',
    
        'politics' => 'Política',
    
        'quality-assurance-amp-safety' => 'Aseguramiento de Calidad y Seguridad',
    
        'real-estate' => 'Bienes inmuebles',
    
        'research-amp-development' => 'Investigación y desarrollo',
    
        'retail-amp-wholesale' => 'Comercio al por menor y al por mayor',
    
        'sales' => 'Ventas',
    
        'social-work' => 'Trabajo social',
    
        'sport-and-or-health-amp-wellness' => 'Deporte y/o Salud y bienestar',
    
        'technology-amp-telecommunications' => 'Tecnología y Telecomunicaciones',
    
        'business-studies-and-or-management-science' => 'Estudios de negocios y/o Ciencias de la Gestión',
    
        'engineering-and-or-technology' => 'Ingeniería y/o Tecnología',
    
        'social-sciences' => 'Ciencias Sociales',
    
        'languages-and-philological-sciences' => 'Lenguas y Ciencias Filológicas',
    
        'communication-and-information-sciences' => 'Comunicación y Ciencias de la Información',
    
        'humanities' => 'Humanidades',
    
        'education-and-or-teacher-training' => 'Educación y /o Formación del profesorado',
    
        'law' => 'Derecho',
    
        'art-and-design' => 'Arte y diseño',
    
        'architecture-and-or-urban-and-regional-planning' => 'Arquitectura y/o Planificación Urbana y Regional',
    
        'natural-sciences' => 'Ciencias Naturales',
    
        'mathematics-and-or-informatics' => 'Matemáticas y/o Informática',
    
        'medical-sciences' => 'Ciencias Médicas',
    
        'geography-and-or-geology' => 'Geografía y/o Geología',
    
        'agriculture-sciences' => 'Ciencias Agrarias',
    
        'Lang_level_A1' => 'A1: Acceso o principiante',
    
        'Lang_level_A2' => 'A2: Plataforma o básico',
    
        'Lang_level_B1' => 'B1: Umbral o intermedio',
    
        'Lang_level_B2' => 'B2: Avanzado o intermedio alto',
    
        'Lang_level_C1' => 'C1: Dominio operativo eficaz o superior bajo',
    
        'Lang_level_C2' => 'C2: Maestría o superior',
    
        'logo' => 'Logo',
    
        'my_profile' => 'My profile',
    
        'profile' => 'Profile',
    
        'profile_visibility' => 'Profile Visibility',
    
        'profile_visibility_visible' => 'Visible. Can be searched, viewed',
    
        'profile_visibility_hidden' => 'Hidden. Cannot be searched or viewed',
    
        'notifications' => 'Notifications',
    
        'notifications_enabled' => 'Enabled. You&apos;ll receive emails once a day if a student wants to get in contact with you',
    
        'notifications_disabled' => 'Disabled. You won&apos;t receive any emails, except for announcements about the service',
    
        'about' => 'About',
    
        'company_logo' => 'Company Logo',
    
        'social_and_web' => 'Social networks and website',
    
        'facebook_page_url' => 'Facebook page url',
    
        'twitter_page_url' => 'Twitter page url',
    
        'linkedin_page_url' => 'Linkedin page url',
    
        'web_url' => 'Website url',
    
        'what_is_talent_for_you_in_a_few_words' => 'Explain us what is talent for you in a few words',
    
        'most_valuable_skills_for_company' => 'A list of the most valuable skills for the company',
    
        'setup_alternative_contact' => 'Setup an alternative contact user that will receive all the notifications instead of the main account',
    
        'update_settings' => 'Update settings',
    
        'change_your_password' => 'Change your password',
    
        'new_password' => 'New password',
    
        'repeat_new_password' => 'Repeat new password',
    
        'save_new_password' => 'Save new password',
    
        'career_and_skills' => 'Career and Skills',
    
        'my_photo' => 'My Photo',
    
        'download_curriculum' => 'Download curriculum',
    
        'my_talent' => 'My talent',
    
        'referee_name' => 'Referee name',
    
        'referee_email' => 'Referee email',
    
        'get_your_profile_refereed' => 'Get your profile refereed',
    
        'want_to_view_all_details_of_student' => 'Do you want to view all the details of this student?',
    
        'education' => 'Education',
    
        'lives_in' => 'Lives in',
    
        'born_on' => 'Born on',
    
        'refereed_by' => 'Refereed by',
    
        'refereeing_pending' => 'Refereeing pending',
    
        'skills' => 'Skills',
    
        'professional' => 'Professional',
    
        'personal' => 'Personal',
    
        'legend' => 'Legend',
    
        'set_by_both_parties' => 'Set by both parties',
    
        'set_by_referee_or_student' => 'Set by either the referee or the student',
    
        'study' => 'Study|Studies',
    
        'date_not_specified' => 'Date not specified',
    
        'get_in_contact' => 'Get in contact',
    
        'want_to_show_this_company_how_talented_you_are' => 'Do you want to show this company how talented you are?',
    
        'we_are_in' => 'We are in',
    
        'we_are_looking_for_people_skilled_in' => 'We&apos;re looking for people skilled in',
    
        'we_think_that_talent_is' => 'We think that talent is',
    
        'not_enough_information' => 'Not enough information',
    
        'fix_the_following_errors' => 'You&apos;ll need to fix the following errors',
    
        'click_on_button_to_fill_required_fields' => 'Please click the following button to fill the required fields.',
    
        'institution_fix_the_following_errors' => 'You&apos;ll need to fix the following errors or your referees won&apos;t be able to validate profiles',
    
        'my_institution' => 'My Institution',
    
        'required' => 'Required',
    
        'remove_btn' => 'Remove',
    
        'student_study_institution_name' => 'Institution name',
    
        'student_study_course_studies_name' => 'Course/Studies name',
    
        'student_download_certificate' => 'Download Certificate',
    
        'student_download_grade_card' => 'Download Gradecard',
    
        'student_study_add_more' => 'add more studies',
    
        'student_training_course_name' => 'Course name',
    
        'student_training_add' => 'add a training',
    
        'student_training_add_more' => 'add more trainings',
    
        'student_language' => 'Language',
    
        'student_language_name' => 'Language name',
    
        'student_language_level' => 'Language level',
    
        'student_language_add' => 'add a language',
    
        'student_language_add_more' => 'add more languages',
    
        'student_work_experience_to' => 'Work to',
    
        'student_work_experience_from' => 'Work from',
    
        'student_work_experience_add' => 'add a work experience',
    
        'student_work_experience_add_more' => 'add more work experiences',
    
        'add_btn' => 'Add',
    
        'student_professional_skills_remove' => 'Remove professional skill',
    
        'student_professional_skills_add' => 'Add a professional skill',
    
        'profile_readiness' => 'Profile readiness',
    
        'profile_readiness_explanation' => 'Getting your profile refereed gives a third party opinion of you and helps increasing the possibilities of contact from a company',
    
        'get_a_better_refeer' => 'Get a better refeer improving your profile readiness and improve possibility of company contact',
    
        'request_is_managed_by' => 'Your request is being managed by',
    
        'cant_find_your_institution' => 'Can&apos;t find your institution? ask your referee and institution to join Talented Europe',
    
        'this_step_sends_an_email_to_your_referee' => 'This step sends an email to your referee with instructions on how to join Talented Europe, automatically registers him as referee once his institution joins, and adds you to the refeeral queue',
    
        'send_invitation' => 'Send invitation',
    
        'profile_validated_successfully' => 'Your profile was validated successfully',
    
        'referee_said_about_you' => 'This is what your referee said about you',
    
        'profile_validated_denied' => 'Your profile was denied',
    
        'not_enough_data_to_do_a_refeer' => 'We don&apos;t have enough data from you to be able to do a refeer.',
    
        'progress_account_setup' => 'Account setup',
    
        'progress_refer_your_profile' => 'Refer your profile',
    
        'progress_not_refereed' => 'Not refereed',
    
        'progress_completed' => 'Completed',
    
        'you_must_put_referee_email' => '<strong>Please note:</strong> You must put the referee email, not the one form the institution',
    
];