<?php
// Autogenerated by Translator Builder

return [
    
        'thank_you_for_signing_up' => '¡Gracias por registrarte!',
    
        'you_will_receive_an_email' => 'Recibirás un correo electrónico con instrucciones sobre cómo confirmar tu cuenta en unos minutos.',
    
        'go_back_to_home' => 'Volver a la página principal',
    
        'search_students' => 'Buscar estudiantes',
    
        'search_companies' => 'Buscar empresas',
    
        'register_as_validator' => 'Registro como validador',
    
        'there_have_been_some_errors' => 'Hay más de un error',
    
        'i_am_a' => 'Soy un',
    
        'all_fields_are_required' => 'Todos los campos son obligatorios',
    
        'confirmation_email_may_take_few_minutes' => 'El correo electrónico de confirmación puede tardar unos minutos en llegar, no se olvide de controlar su carpeta de spam también',
    
        'registration_complete_successfully' => 'Registro completado satisfactoriamente',
    
        'register_success' => 'Registro completado',
    
        'register' => 'Registro',
    
        'invited_by' => 'Has sido invitado por',
    
];
