<?php
// Autogenerated by Translator Builder

return [
    
        'loading' => 'Cargando',
    
        'toggle' => 'Show/Hide',
    
        'current_search' => 'Búsqueda actual',
    
        'refereed' => 'Refereed',
    
];