<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Fecha de solicitud',
    
        'pending' => 'Pendiente',
    
        'validated' => 'Validado',
    
        'not_validated' => 'No validado',
    
        'no_students' => 'No students',
    
        'confirm_validation' => 'Confirm refereeing',
    
        'are_you_sure_you_want_to_finish_refereeing' => 'Are you sure you want to finish refereeing this student?',
    
];
