<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Fecha de solicitud',
    
        'status' => 'Estado',
    
        'pending' => 'Pendiente',
    
        'validated' => 'Validated',
    
        'not_validated' => 'Not validated',
    
];