<?php
// Autogenerated by Translator Builder

return [
    
        'date_of_request' => 'Fecha de solicitud',
    
        'pending' => 'Pendiente',
    
        'validated' => 'Validado',
    
        'not_validated' => 'No validado',
    
];