<?php
// Autogenerated by Translator Builder

return [
    
        'my_students' => 'Mis estudiantes',
    
        'enable' => 'Habilitado',
    
        'disable' => 'Deshabilitado',
    
        'add_new' => 'Añadir un nuevo validador',
    
        'send_invitation' => 'Enviar invitación a un validador',
    
        'validating' => 'Validando',
    
        'student_already_validated' => 'Has validado ya a este estudiante',
    
        'jump_to_results' => 'Ir a los resultados',
    
        'you_are_validating_following_student' => 'Estás validando el siguiente estudiante',
    
        'jump_to_validation' => 'Ir a la validación',
    
        'student_validation' => 'Validación de Estudiante',
    
        'valid' => 'Válido',
    
        'student_passed_validation_successfully' => 'El estudiante pasó tu validación correctamente',
    
        'your_comments' => 'Tus comentarios',
    
        'your_chosen_skills' => 'Tus habilidades elegidas',
    
        'invalid' => 'No válido',
    
        'student_didnt_meet_criteria' => 'El estudiante no cumplió con los criterios',
    
        'make_sure_you_have_reviewed_student' => 'Por favor, asegúrese de revisar cuidadosamente el perfil del estudiante antes de validarlo',
    
        'this_student_is' => 'Este estudiante es',
    
        'finish_validation' => 'Validación finalizada',
    
        'give_us_explanation_of_student_is_not_valid' => 'Por favor, proporciona un motivo por el que el/la estudiante no es válido',
    
        'note_if_validation_is_passed_as_no_student' => 'Nota: Si la validación se concluye como "Ningún estudiante" el estudiante podrá validar su perfil otra vez.',
    
        'user_hasnt_complete_filling_its_profile' => 'Perfil no acabado. Si el perfil no está completo, no se puede validar a ningún estudiante. ',
    
        'manage_validators' => 'Gestionar validadores',
    
        'validators' => 'Validadores',
    
        'invites_pending' => 'Invitaciones pendientes',
    
        'date_sent' => 'Fecha de envío',
    
        'note_invites_are_only_valid_14_days' => 'Nota: las invitaciones son válidas solamente 14 días después de ser enviadas, y después desaparecerán de esta lista',
    
        'cancel' => 'Cancelar',
    
        'cannot_change_institution' => 'No se puede cambiar la institución',
    
        'invitation_is_not_valid_or_you_accepted_it' => 'Either your invitation is not valid anymore, or you already accepted it',
    
        'changed_institution_successfully' => 'La institución se ha cambiado satisfactoriamente',
    
        'youll_receive_notifications_from' => 'A partir de ahora recibirás notificaciones de validación de',
    
        'cannot_complete_invitation' => 'No se puede completar la invitación',
    
        'no_alerts_found' => 'No se han encontrado alertas',
    
        'study_level' => 'Nivel de estudios',
    
        'when_it_was_sent' => '¿Cuando se envió?',
    
        'no_referees' => 'Sin validadores',
    
        'remove_referee' => 'Eliminar validador',
    
        'do_you_want_to_remove_referee' => '¿Desea eliminar a %s de tu institución?',
    
        'remove' => 'Eliminar',
    
        'removing' => 'Eliminando',
    
];
