<?php
// Autogenerated by Translator Builder

return [
    
        'my_students' => 'Mis estudiantes',
    
        'enable' => 'Habilitado',
    
        'disable' => 'Deshabilitado',
    
        'add_new' => 'Añadir un nuevo validador',
    
        'send_invitation' => 'Enviar invitación a un validador',
    
        'validating' => 'Validando',
    
        'student_already_validated' => 'Has validado ya a este estudiante',
    
        'jump_to_results' => 'Ir a los resultados',
    
        'you_are_validating_following_student' => 'You&apos;re validating the following student',
    
        'jump_to_validation' => 'Ir a la validación',
    
        'student_validation' => 'Validación de Estudiante',
    
        'valid' => 'Válido',
    
        'student_passed_validation_successfully' => 'El estudiante pasó tu validación correctamente',
    
        'your_comments' => 'Tus comentarios',
    
        'your_chosen_skills' => 'Tus habilidades elegidas',
    
        'invalid' => 'No válido',
    
        'student_didnt_meet_criteria' => 'El estudiante no cumplió con los criterios',
    
        'make_sure_you_have_reviewed_student' => 'Please make sure you have reviewed the student profile carefully before validating it',
    
        'this_student_is' => 'Este estudiante es',
    
        'finish_validation' => 'Validación finalizada',
    
        'give_us_explanation_of_student_is_not_valid' => 'Por favor, proporciona un motivo por el que el/la estudiante no es válido',
    
        'note_if_validation_is_passed_as_no_student' => 'Note: If the validation is passed as "No student" the student will be able to validate his profile again.',
    
        'user_hasnt_complete_filling_its_profile' => 'hasn&apos;t complete filling it&apos;s profile. Until this process is complete you cannot validate any student',
    
        'manage_validators' => 'gestionar validadores',
    
        'validators' => 'validadores',
    
        'invites_pending' => 'Invitaciones pendientes',
    
        'date_sent' => 'Fecha de envío',
    
        'note_invites_are_only_valid_14_days' => 'Note: invites are only valid 14 days after being sent, and they will disapear from this list afterwards',
    
        'cancel' => 'Cancelar',
    
        'cannot_change_institution' => 'Cannot change institution',
    
        'invitation_is_not_valid_or_you_accepted_it' => 'Either your invitation is not valid anymore, or you already accepted it',
    
        'changed_institution_successfully' => 'Changed Institution successfully',
    
        'youll_receive_notifications_from' => 'From now on you&apos;ll receive validation notifications from',
    
        'cannot_complete_invitation' => 'Cannot complete invitation',
    
];